-- Shared by the commercial edition and ZTATTUZ. Existing timestamps stay unchanged.
begin;
set local lock_timeout='8s';
set local statement_timeout='90s';
alter table public.gyms add column if not exists timezone text not null default 'America/Bogota';
create or replace function private.validate_gym_timezone() returns trigger
language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from pg_catalog.pg_timezone_names where name=new.timezone) then
  raise exception 'Selecciona una zona horaria IANA válida.' using errcode='22023';
 end if; return new;
end $$;
drop trigger if exists validate_gym_timezone on public.gyms;
create trigger validate_gym_timezone before insert or update of timezone on public.gyms
for each row execute function private.validate_gym_timezone();
create or replace function private.gym_timezone(p_gym_id uuid) returns text
language sql stable security definer set search_path='' as $$
 select timezone from public.gyms where id=p_gym_id
$$;
create or replace function private.gym_server_now() returns timestamptz
language sql stable set search_path='' as $$ select now() $$;
create or replace function private.gym_local_date(p_gym_id uuid) returns date
language sql stable security definer set search_path='' as $$
 select (private.gym_server_now() at time zone private.gym_timezone(p_gym_id))::date
$$;
alter table public.checkins add column if not exists local_date date,
 add column if not exists ticket_consumed boolean,
 add column if not exists already_consumed_today boolean;
-- Archive is populated only in backups/imports; the ledger remains the source of truth.
alter table public.memberships add column if not exists ticket_consumption_archive jsonb;
create table if not exists public.ticket_daily_consumptions (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id) on delete cascade,
 client_id bigint not null references public.clients(id) on delete cascade,
 membership_id bigint not null references public.memberships(id) on delete cascade,
 local_date date not null,
 checkin_id bigint references public.checkins(id) on delete set null deferrable initially deferred,
 units bigint not null default 1 check(units>0),
 legacy boolean not null default false,
 created_at timestamptz not null default now(),
 unique(gym_id,client_id,membership_id,local_date),
 check(legacy or units=1)
);
create index if not exists daily_tickets_membership on public.ticket_daily_consumptions(gym_id,membership_id);
create index if not exists daily_tickets_client on public.ticket_daily_consumptions(client_id);
create index if not exists daily_tickets_checkin on public.ticket_daily_consumptions(checkin_id);
alter table public.ticket_daily_consumptions enable row level security;
revoke all on public.ticket_daily_consumptions from public,anon,authenticated;
grant select on public.ticket_daily_consumptions to authenticated;
drop policy if exists daily_tickets_read on public.ticket_daily_consumptions;
create policy daily_tickets_read on public.ticket_daily_consumptions for select to authenticated
 using(private.user_has_gym_role(gym_id,array['admin','receptionist']));
-- Private transaction-scoped marker, usable only by the existing authorized import RPCs.
create table if not exists private.ticket_import_context (
 transaction_id bigint not null, gym_id uuid not null, primary key(transaction_id,gym_id)
);
alter table private.ticket_import_context enable row level security;
revoke all on private.ticket_import_context from public,anon,authenticated;
lock table public.checkins in share row exclusive mode;
-- Preserve the exact pre-upgrade balance, including historical repeated entries.
insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,checkin_id,units,legacy,created_at)
select ch.gym_id,ch.client_id,ch.membership_id,(ch.checkin_at at time zone private.gym_timezone(ch.gym_id))::date,
 min(ch.id),count(*),true,min(ch.checkin_at)
from public.checkins ch join public.memberships m on m.id=ch.membership_id and m.gym_id=ch.gym_id
join public.plans p on p.id=m.plan_id and p.gym_id=m.gym_id
where ch.result='PERMITIDA' and ch.ticket_consumed is null and coalesce(m.entry_limit,p.entry_limit) is not null
group by ch.gym_id,ch.client_id,ch.membership_id,(ch.checkin_at at time zone private.gym_timezone(ch.gym_id))::date
on conflict(gym_id,client_id,membership_id,local_date) do nothing;
create or replace function private.ticket_consumption_units(p_gym_id uuid,p_membership_id bigint) returns bigint
language sql stable security definer set search_path='' as $$
 select coalesce(sum(units),0)::bigint from public.ticket_daily_consumptions
 where gym_id=p_gym_id and membership_id=p_membership_id
$$;
create or replace function private.ticket_consumed_on(p_gym_id uuid,p_client_id bigint,p_membership_id bigint,p_day date) returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.ticket_daily_consumptions where gym_id=p_gym_id
 and client_id=p_client_id and membership_id=p_membership_id and local_date=p_day)
$$;
create or replace function private.restore_ticket_archive() returns trigger
language plpgsql security definer set search_path='' as $$
declare item jsonb;
begin
 if new.ticket_consumption_archive is null then return new; end if;
 if jsonb_typeof(new.ticket_consumption_archive)<>'array' or jsonb_array_length(new.ticket_consumption_archive)>10000 then
  raise exception 'El respaldo de consumo de tiquetera no es válido.';
 end if;
 for item in select value from jsonb_array_elements(new.ticket_consumption_archive) loop
  insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,units,legacy,created_at)
  values(new.gym_id,new.client_id,new.id,(item->>'local_date')::date,(item->>'units')::bigint,
   coalesce((item->>'legacy')::boolean,false),coalesce((item->>'created_at')::timestamptz,now()));
 end loop; return new;
end $$;
drop trigger if exists restore_ticket_archive on public.memberships;
create trigger restore_ticket_archive after insert on public.memberships
for each row execute function private.restore_ticket_archive();
create or replace function private.consume_daily_ticket() returns trigger
language plpgsql security definer set search_path='' as $$
declare m record; used bigint; importing boolean; first_id bigint;
begin
 importing:=exists(select 1 from private.ticket_import_context where transaction_id=txid_current() and gym_id=new.gym_id);
 new.local_date:=coalesce(case when importing then new.local_date end,
  (new.checkin_at at time zone private.gym_timezone(new.gym_id))::date);
 if not importing then new.ticket_consumed:=false; new.already_consumed_today:=false; end if;
 if new.result<>'PERMITIDA' or new.membership_id is null then return new; end if;
 perform pg_catalog.pg_advisory_xact_lock(new.client_id);
 select mm.*,coalesce(mm.entry_limit,p.entry_limit) as quota into m
 from public.memberships mm join public.plans p on p.id=mm.plan_id and p.gym_id=mm.gym_id
 where mm.id=new.membership_id and mm.gym_id=new.gym_id and mm.client_id=new.client_id for update of mm;
 if not found then raise exception 'La membresía no pertenece a este cliente y gimnasio.'; end if;
 if m.quota is null then return new; end if;
 if importing then
  if m.ticket_consumption_archive is null then
   -- Older backup: each historical approved visit consumed one entry. Preserve that balance.
   insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,checkin_id,legacy,created_at)
   values(new.gym_id,new.client_id,new.membership_id,new.local_date,new.id,true,new.checkin_at)
   on conflict(gym_id,client_id,membership_id,local_date) do update set units=public.ticket_daily_consumptions.units+1;
  end if;
  return new;
 end if;
 if new.notes='Autorización manual del administrador' then return new; end if;
 if m.payment_status<>'posted' or new.local_date not between m.start_date and m.end_date
 or not exists(select 1 from public.clients where id=new.client_id and gym_id=new.gym_id and active) then
  raise exception 'El cliente o su tiquetera no permiten el ingreso.';
 end if;
 if private.ticket_consumed_on(new.gym_id,new.client_id,new.membership_id,new.local_date) then
  new.already_consumed_today:=true; return new;
 end if;
 used:=private.ticket_consumption_units(new.gym_id,new.membership_id)+m.initial_entries_used;
 if used>=m.quota then raise exception 'La tiquetera no tiene entradas disponibles.'; end if;
 insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,checkin_id,created_at)
 values(new.gym_id,new.client_id,new.membership_id,new.local_date,new.id,new.checkin_at)
 on conflict(gym_id,client_id,membership_id,local_date) do nothing returning id into first_id;
 new.ticket_consumed:=first_id is not null;
 new.already_consumed_today:=first_id is null;
 return new;
end $$;
drop trigger if exists consume_daily_ticket on public.checkins;
create trigger consume_daily_ticket before insert on public.checkins for each row execute function private.consume_daily_ticket();
create or replace function private.preserve_ticket_history() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 if (old.ticket_consumed is not null or exists(select 1 from public.ticket_daily_consumptions where checkin_id=old.id))
 and row(new.gym_id,new.client_id,new.membership_id,new.checkin_at,new.result,new.local_date,new.ticket_consumed,new.already_consumed_today)
 is distinct from row(old.gym_id,old.client_id,old.membership_id,old.checkin_at,old.result,old.local_date,old.ticket_consumed,old.already_consumed_today) then
  raise exception 'No se puede cambiar el consumo de una entrada registrada. Añade una nota de corrección para conservar la trazabilidad.';
 end if; return new;
end $$;
drop trigger if exists preserve_ticket_history on public.checkins;
create trigger preserve_ticket_history before update on public.checkins for each row execute function private.preserve_ticket_history();
-- Wrap the existing import helpers. No public caller can set the import context.
do $wrap$
declare n text;
begin
 foreach n in array array['ztattuz_import_insert','gymsoft_import_insert'] loop
  if to_regprocedure('private.'||n||'(text,uuid,jsonb)') is not null
  and to_regprocedure('private.'||n||'_before_daily(text,uuid,jsonb)') is null then
   execute format('alter function private.%I(text,uuid,jsonb) rename to %I',n,n||'_before_daily');
   execute format($sql$
    create function private.%1$I(p_table text,p_gym_id uuid,p_row jsonb) returns bigint
    language plpgsql security definer set search_path='' as $body$
    declare result bigint;
    begin
     insert into private.ticket_import_context values(txid_current(),p_gym_id) on conflict do nothing;
     result:=private.%2$I(p_table,p_gym_id,p_row);
     delete from private.ticket_import_context where transaction_id=txid_current() and gym_id=p_gym_id;
     return result;
    end $body$;
    revoke all on function private.%1$I(text,uuid,jsonb) from public,anon,authenticated;
   $sql$,n,n||'_before_daily');
  end if;
 end loop;
end $wrap$;
