-- Additive upgrade. All new capabilities remain disabled until explicitly configured.
begin;
set local lock_timeout='8s';
set local statement_timeout='90s';
alter table public.marketing_settings
 add column if not exists online_payments_enabled boolean not null default false,
 add column if not exists chatbot_enabled boolean not null default false,
 add column if not exists marketing_automation_enabled boolean not null default false,
 add column if not exists human_pause_minutes integer not null default 120 check(human_pause_minutes between 5 and 10080),
 add column if not exists bot_session_minutes integer not null default 30 check(bot_session_minutes between 5 and 120),
 add column if not exists setup_completed_at timestamptz;
alter table public.clients add column if not exists whatsapp_opt_in_source text not null default '';
alter table public.memberships add column if not exists payment_source text not null default 'MANUAL';
create table if not exists public.marketing_audit(
 id bigint generated by default as identity primary key, gym_id uuid not null references public.gyms(id) on delete cascade,
 actor_id uuid, action text not null, entity_type text not null, entity_id text, details jsonb not null default '{}', created_at timestamptz not null default now());
create index if not exists marketing_audit_gym_date on public.marketing_audit(gym_id,created_at desc);
create table if not exists public.marketing_connections(
 gym_id uuid not null references public.gyms(id) on delete cascade, provider text not null check(provider in ('META','WOMPI')),
 status text not null default 'DISCONNECTED' check(status in ('DISCONNECTED','CONNECTING','CONNECTED','ATTENTION')),
 mode text not null default 'test' check(mode in ('test','prod')), display_number text not null default '',
 provider_account_id text not null default '', phone_number_id text not null default '', coexistence boolean not null default false,
 metadata jsonb not null default '{}', last_checked_at timestamptz, last_error text not null default '', updated_at timestamptz not null default now(), primary key(gym_id,provider));
create unique index if not exists marketing_meta_phone on public.marketing_connections(phone_number_id) where provider='META' and phone_number_id<>'';
create table if not exists private.marketing_credentials(
 gym_id uuid not null references public.gyms(id) on delete cascade,provider text not null check(provider in ('META','WOMPI')),
 secret_id uuid not null, updated_at timestamptz not null default now(),primary key(gym_id,provider));
create table if not exists private.marketing_platform(
 singleton boolean primary key default true check(singleton),production_allowed boolean not null default false,
 meta_config_secret_id uuid,scheduler_secret_id uuid);
insert into private.marketing_platform(singleton) values(true) on conflict do nothing;
create table if not exists public.whatsapp_templates(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 name text not null check(name ~ '^[a-z0-9_]+$' and length(name)<=512), language text not null default 'es_CO',
 category text not null default 'UTILITY' check(category in ('UTILITY','MARKETING','AUTHENTICATION')),
 body text not null check(length(body) between 1 and 1024), variables text[] not null default '{}',
 status text not null default 'DRAFT' check(status in ('DRAFT','PENDING','APPROVED','REJECTED','PAUSED','DISABLED')),
 provider_id text,rejection_reason text,components jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(gym_id,name,language));
create table if not exists public.marketing_automations(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 name text not null check(length(trim(name)) between 1 and 120),enabled boolean not null default false,
 trigger_type text not null check(trigger_type in ('MEMBERSHIP_BEFORE','MEMBERSHIP_TODAY','MEMBERSHIP_AFTER','MEMBERSHIP_OVERDUE_REPEAT','MEMBERSHIP_RENEWED','TICKET_REMAINING','TICKET_EXPIRING','TICKET_CONSUMED','CHECK_IN_SUCCESS','FIRST_CHECK_IN_DAY','EVERY_N_CHECKINS','FIRST_CHECK_IN_RENEWAL','INACTIVITY','BIRTHDAY','BIRTHDAY_BEFORE','MANUAL_PAYMENT','ONLINE_APPROVED','ONLINE_DECLINED','PAYMENT_PENDING','UNUSED_PAYMENT_LINK','CUSTOM_DATE','DAILY','WEEKLY','MONTHLY')),
 trigger_options jsonb not null default '{}',conditions jsonb not null default '[]' check(jsonb_typeof(conditions)='array' and jsonb_array_length(conditions)<=20),
 body text not null check(length(body) between 1 and 4096),include_payment_link boolean not null default false,
 template_id uuid references public.whatsapp_templates(id) on delete restrict,
 frequency jsonb not null default '{"count":1,"hours":24}',created_by uuid,revision integer not null default 1,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_run_at timestamptz,deleted_at timestamptz);
create index if not exists marketing_rules_active on public.marketing_automations(gym_id,trigger_type) where enabled and deleted_at is null;
create index if not exists marketing_rules_template on public.marketing_automations(template_id);
create table if not exists public.payment_requests(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 client_id bigint references public.clients(id) on delete set null,membership_id bigint references public.memberships(id) on delete set null,
 plan_id bigint references public.plans(id) on delete set null,plan_snapshot jsonb not null,
 provider text not null default 'WOMPI' check(provider='WOMPI'),mode text not null check(mode in ('test','prod')),
 amount_in_cents bigint not null check(amount_in_cents>0 and amount_in_cents<=10000000000),currency text not null default 'COP' check(currency='COP'),
 reference text not null unique,idempotency_key text not null,status text not null default 'PENDING' check(status in ('PENDING','APPROVED','DECLINED','EXPIRED','VOIDED','ERROR')),
 checkout_url text,expires_at timestamptz not null,created_at timestamptz not null default now(),opened_at timestamptz,paid_at timestamptz,
 renewed_membership_id bigint references public.memberships(id) on delete set null,unique(gym_id,idempotency_key));
create index if not exists payment_requests_gym_date on public.payment_requests(gym_id,created_at desc);
create table if not exists public.payment_transactions(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 payment_request_id uuid not null references public.payment_requests(id) on delete restrict,
 provider_transaction_id text not null,mode text not null check(mode in ('test','prod')),
 status text not null check(status in ('PENDING','APPROVED','DECLINED','VOIDED','ERROR')),
 amount_in_cents bigint not null,currency text not null,reference text not null,provider_created_at timestamptz,processed_at timestamptz not null default now(),
 requires_review boolean not null default false, unique(mode,provider_transaction_id));
create index if not exists payment_transactions_gym_date on public.payment_transactions(gym_id,processed_at desc);
create index if not exists payment_transactions_request on public.payment_transactions(payment_request_id);
create table if not exists public.whatsapp_conversations(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 sender_number text not null check(sender_number ~ '^[1-9][0-9]{7,14}$'),client_id bigint references public.clients(id) on delete set null,
 mode text not null default 'BOT' check(mode in ('BOT','HUMAN','PAUSED')),
 verification_state text not null default 'NEW' check(verification_state in ('NEW','DOB','LINK_REQUEST','VERIFIED','LOCKED')),
 verified_until timestamptz,verified_phone text,pending_action text,failed_attempts integer not null default 0,locked_until timestamptz,
 last_inbound_at timestamptz,last_human_at timestamptz,pause_until timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(gym_id,sender_number));
create table if not exists public.chatbot_link_requests(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 conversation_id uuid not null references public.whatsapp_conversations(id) on delete cascade,supplied_name text not null,birth_date date,
 status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED')),client_id bigint references public.clients(id) on delete set null,
 reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now());
create unique index if not exists chatbot_one_pending_link on public.chatbot_link_requests(conversation_id) where status='PENDING';
create index if not exists chatbot_link_gym on public.chatbot_link_requests(gym_id,created_at desc);
create table if not exists private.marketing_events(
 id bigint generated by default as identity primary key,gym_id uuid not null references public.gyms(id) on delete cascade,
 client_id bigint references public.clients(id) on delete cascade,event_type text not null,entity_id text not null,
 occurred_at timestamptz not null default now(),payload jsonb not null default '{}',processed_at timestamptz,unique(gym_id,event_type,entity_id));
create index if not exists marketing_events_pending on private.marketing_events(gym_id,id) where processed_at is null;
create table if not exists public.automation_runs(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 automation_id uuid references public.marketing_automations(id) on delete set null,client_id bigint references public.clients(id) on delete set null,
 dedupe_key text not null,status text not null check(status in ('QUEUED','SENT','SKIPPED','NO_CONSENT','FAILED','UNCERTAIN')),
 reason text,executed_at timestamptz not null default now(),unique(gym_id,dedupe_key));
create index if not exists automation_frequency on public.automation_runs(gym_id,automation_id,client_id,executed_at desc);
alter table public.marketing_messages
 add column if not exists automation_id uuid references public.marketing_automations(id) on delete set null,
 add column if not exists conversation_id uuid references public.whatsapp_conversations(id) on delete set null,
 add column if not exists payment_request_id uuid references public.payment_requests(id) on delete set null,
 add column if not exists dedupe_key text,add column if not exists direction text not null default 'OUT' check(direction in ('IN','OUT','HUMAN')),
 add column if not exists body text not null default '',add column if not exists message_payload jsonb not null default '{}',
 add column if not exists claim_id uuid,add column if not exists claimed_at timestamptz,
 add column if not exists delivered_at timestamptz,add column if not exists read_at timestamptz;
do $$declare c record;begin
 for c in select conname from pg_constraint where conrelid='public.marketing_messages'::regclass and
 ((contype='c' and (pg_get_constraintdef(oid) like '%automation_type%' or pg_get_constraintdef(oid) like '%status%')) or (contype='u' and pg_get_constraintdef(oid) like '%automation_type%')) loop
 execute format('alter table public.marketing_messages drop constraint %I',c.conname);end loop;
end$$;
alter table public.marketing_messages add constraint marketing_messages_status_v2 check(status in ('PENDING','PROCESSING','SENT','FAILED','SKIPPED','QUEUED','DELIVERED','READ','NO_CONSENT','UNCERTAIN','RECEIVED'));
create unique index if not exists marketing_messages_legacy_unique on public.marketing_messages(gym_id,client_id,automation_type,source_date) where dedupe_key is null;
create unique index if not exists marketing_messages_dedupe on public.marketing_messages(gym_id,dedupe_key) where dedupe_key is not null;
create unique index if not exists marketing_messages_provider on public.marketing_messages(gym_id,whatsapp_message_id) where whatsapp_message_id<>'';
create table if not exists private.marketing_oauth_states(state_hash text primary key,gym_id uuid not null references public.gyms(id) on delete cascade,user_id uuid not null,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now());
create table if not exists private.marketing_webhook_events(provider text not null,event_key text not null,gym_id uuid references public.gyms(id) on delete cascade,received_at timestamptz not null default now(),processed_at timestamptz,payload jsonb not null default '{}',primary key(provider,event_key));
create index if not exists marketing_delivery_lookup on private.marketing_webhook_events(gym_id,(payload->>'message_id')) where provider='META_STATUS';
create table if not exists private.marketing_rate_limits(gym_id uuid not null references public.gyms(id) on delete cascade,bucket text not null,window_start timestamptz not null,hits integer not null,primary key(gym_id,bucket,window_start));
create table if not exists private.marketing_sandbox_clients(gym_id uuid primary key references public.gyms(id) on delete cascade,client_id bigint not null references public.clients(id) on delete cascade,created_by uuid,created_at timestamptz not null default now());
-- References are checked even for backend requests; a foreign id never changes tenant.
create or replace function private.marketing_tenant_guard() returns trigger language plpgsql set search_path='' as $$
declare j jsonb:=to_jsonb(new);k text;t text;v boolean;ty text;begin
 if tg_op='UPDATE' and new.gym_id<>old.gym_id then raise exception 'No se puede cambiar el gimnasio.';end if;
 for k,t,ty in select * from (values('client_id','clients','bigint'),('plan_id','plans','bigint'),('membership_id','memberships','bigint'),('renewed_membership_id','memberships','bigint'),('automation_id','marketing_automations','uuid'),('template_id','whatsapp_templates','uuid'),('conversation_id','whatsapp_conversations','uuid'),('payment_request_id','payment_requests','uuid')) a(k,t,ty) loop
 if j->>k is not null then execute format('select exists(select 1 from public.%I where id=$1::%s and gym_id=$2)',t,ty) into v using j->>k,new.gym_id;
 if not v then raise exception 'La relación no pertenece al gimnasio.' using errcode='23503';end if;end if;end loop;return new;end$$;
do $$declare t text;begin
 foreach t in array array['marketing_audit','marketing_connections','whatsapp_templates','marketing_automations','payment_requests','payment_transactions','whatsapp_conversations','chatbot_link_requests','automation_runs'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from public,anon,authenticated',t);
 execute format('grant select on public.%I to authenticated',t);
 execute format('drop policy if exists marketing_admin_read on public.%I',t);
 execute format('create policy marketing_admin_read on public.%I for select to authenticated using(private.user_has_gym_role(gym_id,array[''admin'']))',t);
 end loop;
 foreach t in array array['whatsapp_conversations','chatbot_link_requests'] loop
 execute format('drop policy if exists marketing_reception_read on public.%I',t);
 execute format('create policy marketing_reception_read on public.%I for select to authenticated using(private.user_has_gym_role(gym_id,array[''receptionist'']))',t);end loop;
 foreach t in array array['marketing_credentials','marketing_platform','marketing_oauth_states','marketing_webhook_events','marketing_rate_limits','marketing_events','marketing_sandbox_clients'] loop
 execute format('alter table private.%I enable row level security',t);execute format('revoke all on private.%I from public,anon,authenticated',t);end loop;
 foreach t in array array['marketing_automations','payment_requests','payment_transactions','whatsapp_conversations','chatbot_link_requests','automation_runs','marketing_messages'] loop
 execute format('drop trigger if exists marketing_tenant_guard on public.%I',t);
 execute format('create trigger marketing_tenant_guard before insert or update on public.%I for each row execute function private.marketing_tenant_guard()',t);end loop;
end$$;
