-- Shared by the commercial edition and ZTATTUZ. Existing timestamps stay unchanged.
begin;
set local lock_timeout='8s';
set local statement_timeout='90s';
alter table public.gyms add column if not exists timezone text not null default 'America/Bogota';
create or replace function private.validate_gym_timezone() returns trigger
language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from pg_catalog.pg_timezone_names where name=new.timezone) then
  raise exception 'Selecciona una zona horaria IANA válida.' using errcode='22023';
 end if; return new;
end $$;
drop trigger if exists validate_gym_timezone on public.gyms;
create trigger validate_gym_timezone before insert or update of timezone on public.gyms
for each row execute function private.validate_gym_timezone();
create or replace function private.gym_timezone(p_gym_id uuid) returns text
language sql stable security definer set search_path='' as $$
 select timezone from public.gyms where id=p_gym_id
$$;
create or replace function private.gym_server_now() returns timestamptz
language sql stable set search_path='' as $$ select now() $$;
create or replace function private.gym_local_date(p_gym_id uuid) returns date
language sql stable security definer set search_path='' as $$
 select (private.gym_server_now() at time zone private.gym_timezone(p_gym_id))::date
$$;
alter table public.checkins add column if not exists local_date date,
 add column if not exists ticket_consumed boolean,
 add column if not exists already_consumed_today boolean;
-- Archive is populated only in backups/imports; the ledger remains the source of truth.
alter table public.memberships add column if not exists ticket_consumption_archive jsonb;
create table if not exists public.ticket_daily_consumptions (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id) on delete cascade,
 client_id bigint not null references public.clients(id) on delete cascade,
 membership_id bigint not null references public.memberships(id) on delete cascade,
 local_date date not null,
 checkin_id bigint references public.checkins(id) on delete set null deferrable initially deferred,
 units bigint not null default 1 check(units>0),
 legacy boolean not null default false,
 created_at timestamptz not null default now(),
 unique(gym_id,client_id,membership_id,local_date),
 check(legacy or units=1)
);
create index if not exists daily_tickets_membership on public.ticket_daily_consumptions(gym_id,membership_id);
create index if not exists daily_tickets_client on public.ticket_daily_consumptions(client_id);
create index if not exists daily_tickets_checkin on public.ticket_daily_consumptions(checkin_id);
alter table public.ticket_daily_consumptions enable row level security;
revoke all on public.ticket_daily_consumptions from public,anon,authenticated;
grant select on public.ticket_daily_consumptions to authenticated;
drop policy if exists daily_tickets_read on public.ticket_daily_consumptions;
create policy daily_tickets_read on public.ticket_daily_consumptions for select to authenticated
 using(private.user_has_gym_role(gym_id,array['admin','receptionist']));
-- Private transaction-scoped marker, usable only by the existing authorized import RPCs.
create table if not exists private.ticket_import_context (
 transaction_id bigint not null, gym_id uuid not null, primary key(transaction_id,gym_id)
);
alter table private.ticket_import_context enable row level security;
revoke all on private.ticket_import_context from public,anon,authenticated;
lock table public.checkins in share row exclusive mode;
-- Preserve the exact pre-upgrade balance, including historical repeated entries.
insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,checkin_id,units,legacy,created_at)
select ch.gym_id,ch.client_id,ch.membership_id,(ch.checkin_at at time zone private.gym_timezone(ch.gym_id))::date,
 min(ch.id),count(*),true,min(ch.checkin_at)
from public.checkins ch join public.memberships m on m.id=ch.membership_id and m.gym_id=ch.gym_id
join public.plans p on p.id=m.plan_id and p.gym_id=m.gym_id
where ch.result='PERMITIDA' and ch.ticket_consumed is null and coalesce(m.entry_limit,p.entry_limit) is not null
group by ch.gym_id,ch.client_id,ch.membership_id,(ch.checkin_at at time zone private.gym_timezone(ch.gym_id))::date
on conflict(gym_id,client_id,membership_id,local_date) do nothing;
create or replace function private.ticket_consumption_units(p_gym_id uuid,p_membership_id bigint) returns bigint
language sql stable security definer set search_path='' as $$
 select coalesce(sum(units),0)::bigint from public.ticket_daily_consumptions
 where gym_id=p_gym_id and membership_id=p_membership_id
$$;
create or replace function private.ticket_consumed_on(p_gym_id uuid,p_client_id bigint,p_membership_id bigint,p_day date) returns boolean
language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.ticket_daily_consumptions where gym_id=p_gym_id
 and client_id=p_client_id and membership_id=p_membership_id and local_date=p_day)
$$;
create or replace function private.restore_ticket_archive() returns trigger
language plpgsql security definer set search_path='' as $$
declare item jsonb;
begin
 if new.ticket_consumption_archive is null then return new; end if;
 if jsonb_typeof(new.ticket_consumption_archive)<>'array' or jsonb_array_length(new.ticket_consumption_archive)>10000 then
  raise exception 'El respaldo de consumo de tiquetera no es válido.';
 end if;
 for item in select value from jsonb_array_elements(new.ticket_consumption_archive) loop
  insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,units,legacy,created_at)
  values(new.gym_id,new.client_id,new.id,(item->>'local_date')::date,(item->>'units')::bigint,
   coalesce((item->>'legacy')::boolean,false),coalesce((item->>'created_at')::timestamptz,now()));
 end loop; return new;
end $$;
drop trigger if exists restore_ticket_archive on public.memberships;
create trigger restore_ticket_archive after insert on public.memberships
for each row execute function private.restore_ticket_archive();
create or replace function private.consume_daily_ticket() returns trigger
language plpgsql security definer set search_path='' as $$
declare m record; used bigint; importing boolean; first_id bigint;
begin
 importing:=exists(select 1 from private.ticket_import_context where transaction_id=txid_current() and gym_id=new.gym_id);
 new.local_date:=coalesce(case when importing then new.local_date end,
  (new.checkin_at at time zone private.gym_timezone(new.gym_id))::date);
 if not importing then new.ticket_consumed:=false; new.already_consumed_today:=false; end if;
 if new.result<>'PERMITIDA' or new.membership_id is null then return new; end if;
 perform pg_catalog.pg_advisory_xact_lock(new.client_id);
 select mm.*,coalesce(mm.entry_limit,p.entry_limit) as quota into m
 from public.memberships mm join public.plans p on p.id=mm.plan_id and p.gym_id=mm.gym_id
 where mm.id=new.membership_id and mm.gym_id=new.gym_id and mm.client_id=new.client_id for update of mm;
 if not found then raise exception 'La membresía no pertenece a este cliente y gimnasio.'; end if;
 if m.quota is null then return new; end if;
 if importing then
  if m.ticket_consumption_archive is null then
   -- Older backup: each historical approved visit consumed one entry. Preserve that balance.
   insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,checkin_id,legacy,created_at)
   values(new.gym_id,new.client_id,new.membership_id,new.local_date,new.id,true,new.checkin_at)
   on conflict(gym_id,client_id,membership_id,local_date) do update set units=public.ticket_daily_consumptions.units+1;
  end if;
  return new;
 end if;
 if new.notes='Autorización manual del administrador' then return new; end if;
 if m.payment_status<>'posted' or new.local_date not between m.start_date and m.end_date
 or not exists(select 1 from public.clients where id=new.client_id and gym_id=new.gym_id and active) then
  raise exception 'El cliente o su tiquetera no permiten el ingreso.';
 end if;
 if private.ticket_consumed_on(new.gym_id,new.client_id,new.membership_id,new.local_date) then
  new.already_consumed_today:=true; return new;
 end if;
 used:=private.ticket_consumption_units(new.gym_id,new.membership_id)+m.initial_entries_used;
 if used>=m.quota then raise exception 'La tiquetera no tiene entradas disponibles.'; end if;
 insert into public.ticket_daily_consumptions(gym_id,client_id,membership_id,local_date,checkin_id,created_at)
 values(new.gym_id,new.client_id,new.membership_id,new.local_date,new.id,new.checkin_at)
 on conflict(gym_id,client_id,membership_id,local_date) do nothing returning id into first_id;
 new.ticket_consumed:=first_id is not null;
 new.already_consumed_today:=first_id is null;
 return new;
end $$;
drop trigger if exists consume_daily_ticket on public.checkins;
create trigger consume_daily_ticket before insert on public.checkins for each row execute function private.consume_daily_ticket();
create or replace function private.preserve_ticket_history() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 if (old.ticket_consumed is not null or exists(select 1 from public.ticket_daily_consumptions where checkin_id=old.id))
 and row(new.gym_id,new.client_id,new.membership_id,new.checkin_at,new.result,new.local_date,new.ticket_consumed,new.already_consumed_today)
 is distinct from row(old.gym_id,old.client_id,old.membership_id,old.checkin_at,old.result,old.local_date,old.ticket_consumed,old.already_consumed_today) then
  raise exception 'No se puede cambiar el consumo de una entrada registrada. Añade una nota de corrección para conservar la trazabilidad.';
 end if; return new;
end $$;
drop trigger if exists preserve_ticket_history on public.checkins;
create trigger preserve_ticket_history before update on public.checkins for each row execute function private.preserve_ticket_history();
-- Wrap the existing import helpers. No public caller can set the import context.
do $wrap$
declare n text;
begin
 foreach n in array array['ztattuz_import_insert','gymsoft_import_insert'] loop
  if to_regprocedure('private.'||n||'(text,uuid,jsonb)') is not null
  and to_regprocedure('private.'||n||'_before_daily(text,uuid,jsonb)') is null then
   execute format('alter function private.%I(text,uuid,jsonb) rename to %I',n,n||'_before_daily');
   execute format($sql$
    create function private.%1$I(p_table text,p_gym_id uuid,p_row jsonb) returns bigint
    language plpgsql security definer set search_path='' as $body$
    declare result bigint;
    begin
     insert into private.ticket_import_context values(txid_current(),p_gym_id) on conflict do nothing;
     result:=private.%2$I(p_table,p_gym_id,p_row);
     delete from private.ticket_import_context where transaction_id=txid_current() and gym_id=p_gym_id;
     return result;
    end $body$;
    revoke all on function private.%1$I(text,uuid,jsonb) from public,anon,authenticated;
   $sql$,n,n||'_before_daily');
  end if;
 end loop;
end $wrap$;

CREATE OR REPLACE FUNCTION private.membership_snapshot_json(p_gym_id uuid, p_client_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_client record;
    v_membership_id bigint;
    v_start_date date;
    v_end_date date;
    v_entry_limit bigint;
    v_entries_used bigint := 0;
    v_plan_name text := 'Sin plan';
    v_today date := private.gym_local_date(p_gym_id);
    v_consumed boolean := false;
    v_allowed boolean := false;
    v_status text := 'VENCIDO';
begin
    select
        c.id,
        c.document,
        c.first_name,
        c.last_name,
        c.phone,
        c.email,
        coalesce(c.birthdate, c.birth_date) as birthdate,
        c.biometric_identifier, c.active
    into v_client
    from public.clients c
    where c.id = p_client_id
      and c.gym_id = p_gym_id;

    if not found then
        raise exception 'Cliente no encontrado.' using errcode = 'P0002';
    end if;

    select
        m.id,
        m.start_date,
        m.end_date,
        coalesce(m.entry_limit, p.entry_limit),
        coalesce(p.name, 'Sin plan')
    into
        v_membership_id,
        v_start_date,
        v_end_date,
        v_entry_limit,
        v_plan_name
    from public.memberships m
    left join public.plans p
      on p.id = m.plan_id
     and p.gym_id = m.gym_id
    where m.gym_id = p_gym_id AND m.payment_status = 'posted' /* ZTATTUZ_PAYMENT_VOID_FILTER_V1 */
      and m.client_id = p_client_id
    order by
        case
            when v_today between m.start_date and m.end_date then 0
            else 1
        end,
        case when private.ticket_consumed_on(p_gym_id,p_client_id,m.id,v_today) then 0 else 1 end,
        m.end_date desc,
        m.id desc
    limit 1;

    if v_membership_id is not null and v_entry_limit is not null then
        select private.ticket_consumption_units(p_gym_id,v_membership_id) + m.initial_entries_used
        into v_entries_used from public.memberships m where m.gym_id=p_gym_id and m.id=v_membership_id;
        v_consumed:=private.ticket_consumed_on(p_gym_id,p_client_id,v_membership_id,v_today);
    end if;

    if not coalesce(v_client.active, true) then
        v_status := 'INACTIVO';
    elsif v_membership_id is null then
        v_status := 'VENCIDO';
    elsif not (v_today between v_start_date and v_end_date) then
        v_status := 'VENCIDO';
    elsif v_entry_limit is not null
          and v_entries_used >= v_entry_limit and not v_consumed then
        v_status := 'SIN ENTRADAS';
    else
        v_status := 'AL DÍA';
        v_allowed := true;
    end if;

    return jsonb_build_object(
        'already_consumed_today',v_consumed,'local_date',v_today,
        'id', v_client.id, 'biometric_identifier', v_client.biometric_identifier,
        'document', v_client.document,
        'first_name', v_client.first_name,
        'last_name', v_client.last_name,
        'client_name', trim(
            concat_ws(' ', v_client.first_name, v_client.last_name)
        ),
        'phone', coalesce(v_client.phone, ''),
        'email', coalesce(v_client.email, ''),
        'birthdate', coalesce(v_client.birthdate::text, ''),
        'active', coalesce(v_client.active, true),
        'status', v_status,
        'allowed', v_allowed,
        'membership_id', v_membership_id,
        'membership_start', coalesce(v_start_date::text, ''),
        'membership_end', coalesce(v_end_date::text, ''),
        'plan_name', v_plan_name,
        'entry_limit', v_entry_limit,
        'entries_used', v_entries_used,
        'entries_remaining', case
            when v_entry_limit is null then null
            else greatest(v_entry_limit - v_entries_used, 0)
        end
    );
end;
$function$;

create or replace function private.daily_register_checkin(p_gym_id uuid,p_client_id bigint,p_method text,p_override boolean default false)
returns jsonb language plpgsql security definer set search_path='' as $$
declare s jsonb; ch public.checkins; allowed boolean;
begin
 if auth.uid() is null or not private.user_has_gym_role(p_gym_id,array['admin','receptionist'])
 or (p_override and not private.user_has_gym_role(p_gym_id,array['admin'])) then
  raise exception 'No tienes permiso para registrar esta entrada.' using errcode='42501';
 end if;
 perform pg_catalog.pg_advisory_xact_lock(p_client_id);
 perform 1 from public.clients where gym_id=p_gym_id and id=p_client_id for update;
 s:=private.membership_snapshot_json(p_gym_id,p_client_id);
 allowed:=coalesce((s->>'allowed')::boolean,false);
 insert into public.checkins(gym_id,client_id,membership_id,checkin_at,method,result,notes,recorded_by)
 values(p_gym_id,p_client_id,nullif(s->>'membership_id','')::bigint,private.gym_server_now(),
 left(trim(coalesce(p_method,'MANUAL')),80),case when allowed or p_override then 'PERMITIDA' else 'DENEGADA' end,
 case when p_override and not allowed then 'Autorización manual del administrador' else '' end,auth.uid()) returning * into ch;
 if ch.ticket_consumed then
  s:=s||jsonb_build_object('entries_used',(s->>'entries_used')::bigint+1,
    'entries_remaining',greatest((s->>'entries_remaining')::bigint-1,0));
 end if;
 return s||jsonb_build_object('result',ch.result,'checkin_id',ch.id,'checkin_at',ch.checkin_at,
 'override',p_override and not allowed,'ticket_consumed',ch.ticket_consumed,
 'already_consumed_today',ch.already_consumed_today,'local_date',ch.local_date);
end $$;
revoke all on function private.daily_register_checkin(uuid,bigint,text,boolean) from public,anon,authenticated;
grant execute on function private.daily_register_checkin(uuid,bigint,text,boolean) to authenticated;
create or replace function public.reception_register_checkin(p_gym_id uuid,p_client_id bigint,p_method text default 'RECEPCIÓN')
returns jsonb language sql security invoker set search_path='' as $$
 select private.daily_register_checkin(p_gym_id,p_client_id,p_method,false)
$$;
create or replace function public.admin_register_checkin(p_gym_id uuid,p_client_id bigint,p_method text,p_override boolean default false)
returns jsonb language plpgsql security invoker set search_path='' as $$
begin
 if not private.user_has_gym_role(p_gym_id,array['admin']) then raise exception 'Acceso exclusivo de Administración.' using errcode='42501'; end if;
 return private.daily_register_checkin(p_gym_id,p_client_id,p_method,p_override);
end $$;
revoke all on function public.reception_register_checkin(uuid,bigint,text),public.admin_register_checkin(uuid,bigint,text,boolean) from public,anon,authenticated;
grant execute on function public.reception_register_checkin(uuid,bigint,text),public.admin_register_checkin(uuid,bigint,text,boolean) to authenticated;
create or replace function private.ticket_backup_memberships(p_gym_id uuid) returns jsonb
language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_agg(to_jsonb(m)||jsonb_build_object('ticket_consumption_archive',
 (select coalesce(jsonb_agg(jsonb_build_object('local_date',d.local_date,'units',d.units,'legacy',d.legacy,'created_at',d.created_at) order by d.local_date),'[]')
 from public.ticket_daily_consumptions d where d.gym_id=m.gym_id and d.membership_id=m.id)) order by m.id),'[]')
 from public.memberships m where m.gym_id=p_gym_id
$$;
create or replace function public.ticket_backup_memberships(p_gym_id uuid) returns jsonb
language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or not private.user_has_gym_role(p_gym_id,array['admin']) then
  raise exception 'Solo Administración puede exportar membresías.' using errcode='42501'; end if;
 return private.ticket_backup_memberships(p_gym_id);
end $$;
revoke all on function public.ticket_backup_memberships(uuid) from public,anon,authenticated;
grant execute on function public.ticket_backup_memberships(uuid) to authenticated;
create or replace function public.gym_local_clock(p_gym_id uuid) returns jsonb
language plpgsql stable security definer set search_path='' as $$
begin
 if auth.uid() is null or not private.user_has_gym_role(p_gym_id,array['admin','receptionist']) then
  raise exception 'Acceso no autorizado.' using errcode='42501'; end if;
 return jsonb_build_object('now',private.gym_server_now(),'today',private.gym_local_date(p_gym_id),'timezone',private.gym_timezone(p_gym_id));
end $$;
revoke all on function public.gym_local_clock(uuid) from public,anon,authenticated;
grant execute on function public.gym_local_clock(uuid) to authenticated;
-- Existing per-gym reports/renewals must use the same clock and consumption ledger.
do $patch$
declare f record; definition text; updated text;
begin
 for f in select p.oid,n.nspname,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname in ('public','private') and p.prokind='f' and 'p_gym_id'=any(p.proargnames)
 and p.proname not in ('gym_timezone','gym_server_now','gym_local_date') loop
  definition:=pg_get_functiondef(f.oid); updated:=definition;
  updated:=replace(updated,'public.ztattuz_today()','private.gym_local_date(p_gym_id)');
  updated:=replace(updated,'public.gymsoft_today()','private.gym_local_date(p_gym_id)');
  updated:=replace(updated,'private.current_timezone()','private.gym_timezone(p_gym_id)');
  updated:=replace(updated,'AT TIME ZONE ''America/Bogota''','AT TIME ZONE private.gym_timezone(p_gym_id)');
  updated:=replace(updated,'at time zone ''America/Bogota''','at time zone private.gym_timezone(p_gym_id)');
  if f.proname in ('ztattuz_add_membership','add_membership_accumulating_internal') then
   updated:=regexp_replace(updated,'select count\(\*\) \+ m.initial_entries_used\s+from public.checkins ch\s+where ch.gym_id = p_gym_id\s+and ch.client_id = p_client_id\s+and ch.membership_id = m.id\s+and ch.result = ''PERMITIDA''',
    'select private.ticket_consumption_units(p_gym_id,m.id) + m.initial_entries_used','g');
   if position('from public.checkins' in lower(updated))>0 then raise exception 'Revisar función de renovación: %',f.proname; end if;
  end if;
  if f.proname='ticket_followup' then
   updated:=regexp_replace(updated,'select count\(\*\) as used from public.checkins ch\s+where ch.gym_id=p_gym_id and ch.membership_id=m.id and ch.result=''PERMITIDA''',
    'select private.ticket_consumption_units(p_gym_id,m.id) as used','g');
  end if;
  if f.proname in ('owner_editor_snapshot','owner_backup_gym') then
   updated:=replace(updated,'tables:=tables||jsonb_build_object(t,rows);',
    'if t=''memberships'' then rows:=private.ticket_backup_memberships(p_gym_id); end if; tables:=tables||jsonb_build_object(t,rows);');
  end if;
  if updated<>definition then execute updated; end if;
 end loop;
end $patch$;
-- Private helpers are not APIs. Explicitly revoke default PUBLIC execution.
do $$ declare f record; begin
 for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace
 where n.nspname='private' and p.proname=any(array['validate_gym_timezone','gym_timezone','gym_server_now','gym_local_date',
 'ticket_consumption_units','ticket_consumed_on','consume_daily_ticket','preserve_ticket_history','restore_ticket_archive','ticket_backup_memberships']) loop
  execute format('revoke all on function %s from public,anon,authenticated',f.signature);
 end loop;
end $$;
commit;

-- Real event times and readable client names; existing audit rows are not rewritten.
begin;
set local lock_timeout='8s';
set local statement_timeout='90s';
alter table public.audit_logs alter column created_at set default clock_timestamp();
create index if not exists audit_client_history on public.audit_logs(gym_id,entity_id,created_at desc,id desc) where entity_type='clients';
create index if not exists audit_client_name_snapshot on public.audit_logs(gym_id,(details->>'client_id'),created_at desc,id desc) where details ? 'client_name';
create or replace function private.audit_client_name(p_gym uuid,p_client text) returns text
language sql stable security definer set search_path='' as $$
 select coalesce(
  (select nullif(btrim(concat_ws(' ',c.first_name,c.last_name)),'') from public.clients c where c.gym_id=p_gym and c.id=case when p_client ~ '^[0-9]{1,18}$' then p_client::bigint end),
  (select nullif(a.details->>'client_name','') from public.audit_logs a where a.gym_id=p_gym and a.entity_type='clients' and a.entity_id=p_client and nullif(a.details->>'client_name','') is not null order by a.created_at desc,a.id desc limit 1),
  (select nullif(a.details->>'client_name','') from public.audit_logs a where a.gym_id=p_gym and a.details->>'client_id'=p_client and a.details ? 'client_name' and nullif(a.details->>'client_name','') is not null order by a.created_at desc,a.id desc limit 1)
 )
$$;
create or replace function private.audit_readable_summary(p_summary text,p_name text) returns text
language sql immutable set search_path='' as $$
 select regexp_replace(coalesce(p_summary,''),'\mcliente\s+#?\s*[0-9]+\M',replace(coalesce(nullif(p_name,''),'Cliente eliminado (nombre no disponible)'),E'\\',E'\\\\'),'gi')
$$;
create or replace function private.audit_prepare_record() returns trigger
language plpgsql security definer set search_path='' as $$
declare cid text;label text;actor uuid:=auth.uid();begin
 cid:=coalesce(nullif(new.details->>'client_id',''),new.details#>>'{after,client_id}',new.details#>>'{before,client_id}',case when new.entity_type='clients' then new.entity_id end);
 if cid is not null then
  label:=coalesce(nullif(new.details->>'client_name',''),private.audit_client_name(new.gym_id,cid));
  new.details:=new.details||jsonb_build_object('client_id',cid,'client_name',label);
  new.summary:=private.audit_readable_summary(new.summary,label);
 end if;
 -- recorded_by belongs to the original payment; the editor is the current user.
 if actor is not null then
  new.actor_user_id:=actor;
  select coalesce(u.email,'Usuario'),coalesce(gu.role,'authenticated') into new.actor_email,new.actor_role
  from auth.users u left join public.gym_users gu on gu.user_id=u.id and gu.gym_id=new.gym_id where u.id=actor;
 end if;
 return new;
end$$;
drop trigger if exists audit_prepare_record on public.audit_logs;
create trigger audit_prepare_record before insert on public.audit_logs for each row execute function private.audit_prepare_record();
create or replace function private.audit_local_iso(p_time timestamptz,p_zone text) returns text
language sql stable set search_path='' as $$
 select to_char(p_time at time zone p_zone,'YYYY-MM-DD"T"HH24:MI:SS.US') || case when seconds<0 then '-' else '+' end || to_char(make_interval(secs=>abs(seconds)::double precision),'HH24:MI')
 from (select extract(epoch from ((p_time at time zone p_zone)-(p_time at time zone 'UTC'))) seconds) x
$$;
create or replace function public.get_audit_logs(p_gym_id uuid,p_limit integer default 200,p_action text default '') returns jsonb
language plpgsql stable security definer set search_path='' as $$
declare result jsonb;zone text;begin
 if auth.uid() is null or not private.user_has_gym_role(p_gym_id,array['admin']::text[]) then raise exception 'La auditoría es exclusiva del administrador.' using errcode='42501';end if;
 select coalesce(to_jsonb(g)->>'timezone','America/Bogota') into zone from public.gyms g where id=p_gym_id;
 select coalesce(jsonb_agg(to_jsonb(x)||jsonb_build_object('summary',private.audit_readable_summary(x.summary,n.client_name),'client_name',n.client_name,'timezone',zone,'occurred_at',x.created_at,'created_at',private.audit_local_iso(x.created_at,zone),'created_at_local',to_char(x.created_at at time zone zone,'DD/MM/YYYY HH24:MI:SS')) order by x.created_at desc,x.id desc),'[]') into result
 from (select * from public.audit_logs where gym_id=p_gym_id and (btrim(coalesce(p_action,''))='' or action=btrim(p_action)) order by created_at desc,id desc limit least(greatest(coalesce(p_limit,200),1),500)) x
 cross join lateral (select coalesce(nullif(x.details->>'client_name',''),private.audit_client_name(p_gym_id,coalesce(x.details->>'client_id',x.details#>>'{after,client_id}',x.details#>>'{before,client_id}',case when x.entity_type='clients' then x.entity_id end))) client_name) n;
 return result;
end$$;
revoke all on function private.audit_client_name(uuid,text),private.audit_readable_summary(text,text),private.audit_prepare_record(),private.audit_local_iso(timestamptz,text) from public,anon,authenticated;
revoke all on function public.get_audit_logs(uuid,integer,text) from public,anon,authenticated;
grant execute on function public.get_audit_logs(uuid,integer,text) to authenticated;
commit;
