-- Additive upgrade. All new capabilities remain disabled until explicitly configured.
begin;
set local lock_timeout='8s';
set local statement_timeout='90s';
alter table public.marketing_settings
 add column if not exists online_payments_enabled boolean not null default false,
 add column if not exists chatbot_enabled boolean not null default false,
 add column if not exists marketing_automation_enabled boolean not null default false,
 add column if not exists human_pause_minutes integer not null default 120 check(human_pause_minutes between 5 and 10080),
 add column if not exists bot_session_minutes integer not null default 30 check(bot_session_minutes between 5 and 120),
 add column if not exists setup_completed_at timestamptz;
alter table public.clients add column if not exists whatsapp_opt_in_source text not null default '';
alter table public.memberships add column if not exists payment_source text not null default 'MANUAL';
create table if not exists public.marketing_audit(
 id bigint generated by default as identity primary key, gym_id uuid not null references public.gyms(id) on delete cascade,
 actor_id uuid, action text not null, entity_type text not null, entity_id text, details jsonb not null default '{}', created_at timestamptz not null default now());
create index if not exists marketing_audit_gym_date on public.marketing_audit(gym_id,created_at desc);
create table if not exists public.marketing_connections(
 gym_id uuid not null references public.gyms(id) on delete cascade, provider text not null check(provider in ('META','WOMPI')),
 status text not null default 'DISCONNECTED' check(status in ('DISCONNECTED','CONNECTING','CONNECTED','ATTENTION')),
 mode text not null default 'test' check(mode in ('test','prod')), display_number text not null default '',
 provider_account_id text not null default '', phone_number_id text not null default '', coexistence boolean not null default false,
 metadata jsonb not null default '{}', last_checked_at timestamptz, last_error text not null default '', updated_at timestamptz not null default now(), primary key(gym_id,provider));
create unique index if not exists marketing_meta_phone on public.marketing_connections(phone_number_id) where provider='META' and phone_number_id<>'';
create table if not exists private.marketing_credentials(
 gym_id uuid not null references public.gyms(id) on delete cascade,provider text not null check(provider in ('META','WOMPI')),
 secret_id uuid not null, updated_at timestamptz not null default now(),primary key(gym_id,provider));
create table if not exists private.marketing_platform(
 singleton boolean primary key default true check(singleton),production_allowed boolean not null default false,
 meta_config_secret_id uuid,scheduler_secret_id uuid);
insert into private.marketing_platform(singleton) values(true) on conflict do nothing;
create table if not exists public.whatsapp_templates(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 name text not null check(name ~ '^[a-z0-9_]+$' and length(name)<=512), language text not null default 'es_CO',
 category text not null default 'UTILITY' check(category in ('UTILITY','MARKETING','AUTHENTICATION')),
 body text not null check(length(body) between 1 and 1024), variables text[] not null default '{}',
 status text not null default 'DRAFT' check(status in ('DRAFT','PENDING','APPROVED','REJECTED','PAUSED','DISABLED')),
 provider_id text,rejection_reason text,components jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(gym_id,name,language));
create table if not exists public.marketing_automations(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 name text not null check(length(trim(name)) between 1 and 120),enabled boolean not null default false,
 trigger_type text not null check(trigger_type in ('MEMBERSHIP_BEFORE','MEMBERSHIP_TODAY','MEMBERSHIP_AFTER','MEMBERSHIP_OVERDUE_REPEAT','MEMBERSHIP_RENEWED','TICKET_REMAINING','TICKET_EXPIRING','TICKET_CONSUMED','CHECK_IN_SUCCESS','FIRST_CHECK_IN_DAY','EVERY_N_CHECKINS','FIRST_CHECK_IN_RENEWAL','INACTIVITY','BIRTHDAY','BIRTHDAY_BEFORE','MANUAL_PAYMENT','ONLINE_APPROVED','ONLINE_DECLINED','PAYMENT_PENDING','UNUSED_PAYMENT_LINK','CUSTOM_DATE','DAILY','WEEKLY','MONTHLY')),
 trigger_options jsonb not null default '{}',conditions jsonb not null default '[]' check(jsonb_typeof(conditions)='array' and jsonb_array_length(conditions)<=20),
 body text not null check(length(body) between 1 and 4096),include_payment_link boolean not null default false,
 template_id uuid references public.whatsapp_templates(id) on delete restrict,
 frequency jsonb not null default '{"count":1,"hours":24}',created_by uuid,revision integer not null default 1,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),last_run_at timestamptz,deleted_at timestamptz);
create index if not exists marketing_rules_active on public.marketing_automations(gym_id,trigger_type) where enabled and deleted_at is null;
create index if not exists marketing_rules_template on public.marketing_automations(template_id);
create table if not exists public.payment_requests(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 client_id bigint references public.clients(id) on delete set null,membership_id bigint references public.memberships(id) on delete set null,
 plan_id bigint references public.plans(id) on delete set null,plan_snapshot jsonb not null,
 provider text not null default 'WOMPI' check(provider='WOMPI'),mode text not null check(mode in ('test','prod')),
 amount_in_cents bigint not null check(amount_in_cents>0 and amount_in_cents<=10000000000),currency text not null default 'COP' check(currency='COP'),
 reference text not null unique,idempotency_key text not null,status text not null default 'PENDING' check(status in ('PENDING','APPROVED','DECLINED','EXPIRED','VOIDED','ERROR')),
 checkout_url text,expires_at timestamptz not null,created_at timestamptz not null default now(),opened_at timestamptz,paid_at timestamptz,
 renewed_membership_id bigint references public.memberships(id) on delete set null,unique(gym_id,idempotency_key));
create index if not exists payment_requests_gym_date on public.payment_requests(gym_id,created_at desc);
create table if not exists public.payment_transactions(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 payment_request_id uuid not null references public.payment_requests(id) on delete restrict,
 provider_transaction_id text not null,mode text not null check(mode in ('test','prod')),
 status text not null check(status in ('PENDING','APPROVED','DECLINED','VOIDED','ERROR')),
 amount_in_cents bigint not null,currency text not null,reference text not null,provider_created_at timestamptz,processed_at timestamptz not null default now(),
 requires_review boolean not null default false, unique(mode,provider_transaction_id));
create index if not exists payment_transactions_gym_date on public.payment_transactions(gym_id,processed_at desc);
create index if not exists payment_transactions_request on public.payment_transactions(payment_request_id);
create table if not exists public.whatsapp_conversations(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 sender_number text not null check(sender_number ~ '^[1-9][0-9]{7,14}$'),client_id bigint references public.clients(id) on delete set null,
 mode text not null default 'BOT' check(mode in ('BOT','HUMAN','PAUSED')),
 verification_state text not null default 'NEW' check(verification_state in ('NEW','DOB','LINK_REQUEST','VERIFIED','LOCKED')),
 verified_until timestamptz,verified_phone text,pending_action text,failed_attempts integer not null default 0,locked_until timestamptz,
 last_inbound_at timestamptz,last_human_at timestamptz,pause_until timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(gym_id,sender_number));
create table if not exists public.chatbot_link_requests(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 conversation_id uuid not null references public.whatsapp_conversations(id) on delete cascade,supplied_name text not null,birth_date date,
 status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED')),client_id bigint references public.clients(id) on delete set null,
 reviewed_by uuid,reviewed_at timestamptz,created_at timestamptz not null default now());
create unique index if not exists chatbot_one_pending_link on public.chatbot_link_requests(conversation_id) where status='PENDING';
create index if not exists chatbot_link_gym on public.chatbot_link_requests(gym_id,created_at desc);
create table if not exists private.marketing_events(
 id bigint generated by default as identity primary key,gym_id uuid not null references public.gyms(id) on delete cascade,
 client_id bigint references public.clients(id) on delete cascade,event_type text not null,entity_id text not null,
 occurred_at timestamptz not null default now(),payload jsonb not null default '{}',processed_at timestamptz,unique(gym_id,event_type,entity_id));
create index if not exists marketing_events_pending on private.marketing_events(gym_id,id) where processed_at is null;
create table if not exists public.automation_runs(
 id uuid primary key default gen_random_uuid(),gym_id uuid not null references public.gyms(id) on delete cascade,
 automation_id uuid references public.marketing_automations(id) on delete set null,client_id bigint references public.clients(id) on delete set null,
 dedupe_key text not null,status text not null check(status in ('QUEUED','SENT','SKIPPED','NO_CONSENT','FAILED','UNCERTAIN')),
 reason text,executed_at timestamptz not null default now(),unique(gym_id,dedupe_key));
create index if not exists automation_frequency on public.automation_runs(gym_id,automation_id,client_id,executed_at desc);
alter table public.marketing_messages
 add column if not exists automation_id uuid references public.marketing_automations(id) on delete set null,
 add column if not exists conversation_id uuid references public.whatsapp_conversations(id) on delete set null,
 add column if not exists payment_request_id uuid references public.payment_requests(id) on delete set null,
 add column if not exists dedupe_key text,add column if not exists direction text not null default 'OUT' check(direction in ('IN','OUT','HUMAN')),
 add column if not exists body text not null default '',add column if not exists message_payload jsonb not null default '{}',
 add column if not exists claim_id uuid,add column if not exists claimed_at timestamptz,
 add column if not exists delivered_at timestamptz,add column if not exists read_at timestamptz;
do $$declare c record;begin
 for c in select conname from pg_constraint where conrelid='public.marketing_messages'::regclass and
 ((contype='c' and (pg_get_constraintdef(oid) like '%automation_type%' or pg_get_constraintdef(oid) like '%status%')) or (contype='u' and pg_get_constraintdef(oid) like '%automation_type%')) loop
 execute format('alter table public.marketing_messages drop constraint %I',c.conname);end loop;
end$$;
alter table public.marketing_messages add constraint marketing_messages_status_v2 check(status in ('PENDING','PROCESSING','SENT','FAILED','SKIPPED','QUEUED','DELIVERED','READ','NO_CONSENT','UNCERTAIN','RECEIVED'));
create unique index if not exists marketing_messages_legacy_unique on public.marketing_messages(gym_id,client_id,automation_type,source_date) where dedupe_key is null;
create unique index if not exists marketing_messages_dedupe on public.marketing_messages(gym_id,dedupe_key) where dedupe_key is not null;
create unique index if not exists marketing_messages_provider on public.marketing_messages(gym_id,whatsapp_message_id) where whatsapp_message_id<>'';
create table if not exists private.marketing_oauth_states(state_hash text primary key,gym_id uuid not null references public.gyms(id) on delete cascade,user_id uuid not null,expires_at timestamptz not null,used_at timestamptz,created_at timestamptz not null default now());
create table if not exists private.marketing_webhook_events(provider text not null,event_key text not null,gym_id uuid references public.gyms(id) on delete cascade,received_at timestamptz not null default now(),processed_at timestamptz,payload jsonb not null default '{}',primary key(provider,event_key));
create index if not exists marketing_delivery_lookup on private.marketing_webhook_events(gym_id,(payload->>'message_id')) where provider='META_STATUS';
create table if not exists private.marketing_rate_limits(gym_id uuid not null references public.gyms(id) on delete cascade,bucket text not null,window_start timestamptz not null,hits integer not null,primary key(gym_id,bucket,window_start));
create table if not exists private.marketing_sandbox_clients(gym_id uuid primary key references public.gyms(id) on delete cascade,client_id bigint not null references public.clients(id) on delete cascade,created_by uuid,created_at timestamptz not null default now());
-- References are checked even for backend requests; a foreign id never changes tenant.
create or replace function private.marketing_tenant_guard() returns trigger language plpgsql set search_path='' as $$
declare j jsonb:=to_jsonb(new);k text;t text;v boolean;ty text;begin
 if tg_op='UPDATE' and new.gym_id<>old.gym_id then raise exception 'No se puede cambiar el gimnasio.';end if;
 for k,t,ty in select * from (values('client_id','clients','bigint'),('plan_id','plans','bigint'),('membership_id','memberships','bigint'),('renewed_membership_id','memberships','bigint'),('automation_id','marketing_automations','uuid'),('template_id','whatsapp_templates','uuid'),('conversation_id','whatsapp_conversations','uuid'),('payment_request_id','payment_requests','uuid')) a(k,t,ty) loop
 if j->>k is not null then execute format('select exists(select 1 from public.%I where id=$1::%s and gym_id=$2)',t,ty) into v using j->>k,new.gym_id;
 if not v then raise exception 'La relación no pertenece al gimnasio.' using errcode='23503';end if;end if;end loop;return new;end$$;
do $$declare t text;begin
 foreach t in array array['marketing_audit','marketing_connections','whatsapp_templates','marketing_automations','payment_requests','payment_transactions','whatsapp_conversations','chatbot_link_requests','automation_runs'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('revoke all on public.%I from public,anon,authenticated',t);
 execute format('grant select on public.%I to authenticated',t);
 execute format('drop policy if exists marketing_admin_read on public.%I',t);
 execute format('create policy marketing_admin_read on public.%I for select to authenticated using(private.user_has_gym_role(gym_id,array[''admin'']))',t);
 end loop;
 foreach t in array array['whatsapp_conversations','chatbot_link_requests'] loop
 execute format('drop policy if exists marketing_reception_read on public.%I',t);
 execute format('create policy marketing_reception_read on public.%I for select to authenticated using(private.user_has_gym_role(gym_id,array[''receptionist'']))',t);end loop;
 foreach t in array array['marketing_credentials','marketing_platform','marketing_oauth_states','marketing_webhook_events','marketing_rate_limits','marketing_events','marketing_sandbox_clients'] loop
 execute format('alter table private.%I enable row level security',t);execute format('revoke all on private.%I from public,anon,authenticated',t);end loop;
 foreach t in array array['marketing_automations','payment_requests','payment_transactions','whatsapp_conversations','chatbot_link_requests','automation_runs','marketing_messages'] loop
 execute format('drop trigger if exists marketing_tenant_guard on public.%I',t);
 execute format('create trigger marketing_tenant_guard before insert or update on public.%I for each row execute function private.marketing_tenant_guard()',t);end loop;
end$$;

create or replace function private.marketing_audit(p_gym uuid,p_action text,p_entity text,p_id text,p_details jsonb default '{}') returns void language sql security definer set search_path='' as $$
 insert into public.marketing_audit(gym_id,actor_id,action,entity_type,entity_id,details) values(p_gym,auth.uid(),p_action,p_entity,p_id,p_details)
$$;
-- Integration events share the main activity clock and operator identity.
create or replace function private.marketing_audit_to_activity() returns trigger
language plpgsql security definer set search_path='' as $$
declare cid bigint;actor uuid:=new.actor_id;email text;role_name text;label text;begin
 if new.entity_type='client' and new.entity_id ~ '^[0-9]+$' then cid:=new.entity_id::bigint;
 elsif new.entity_type='membership' and new.entity_id ~ '^[0-9]+$' then
 select client_id into cid from public.memberships where gym_id=new.gym_id and id=new.entity_id::bigint;
 elsif new.entity_type='payment_request' then
 select client_id into cid from public.payment_requests where gym_id=new.gym_id and id::text=new.entity_id;
 elsif new.entity_type='conversation' then
 select client_id into cid from public.whatsapp_conversations where gym_id=new.gym_id and id::text=new.entity_id;end if;
 if actor is null and coalesce(new.details->>'responsible_user_id','') ~ '^[a-f0-9-]{36}$' then
 select gu.user_id into actor from public.gym_users gu where gu.gym_id=new.gym_id and gu.user_id::text=new.details->>'responsible_user_id' and gu.role='admin';end if;
 select u.email,gu.role into email,role_name from auth.users u
 left join public.gym_users gu on gu.user_id=u.id and gu.gym_id=new.gym_id where u.id=actor;
 label:=case new.action when 'META_CONNECTED' then 'WhatsApp conectado' when 'META_DISCONNECTED' then 'WhatsApp desconectado'
 when 'WOMPI_CONNECTED' then 'Wompi conectado' when 'WOMPI_DISCONNECTED' then 'Wompi desconectado'
 when 'PAYMENT_PROCESSED' then 'Pago online confirmado' when 'PAYMENT_REQUIRES_REVIEW' then 'Pago online requiere revisión'
 when 'MEMBERSHIP_RENEWED' then 'Membresía renovada online' when 'CHATBOT_VERIFIED' then 'Cliente verificado por chatbot'
 when 'CHATBOT_VERIFICATION_FAILED' then 'Verificación de chatbot fallida' when 'HUMAN_HANDOFF' then 'Chatbot derivado a atención humana'
 when 'HUMAN_MESSAGE' then 'Chatbot pausado por respuesta humana' else initcap(replace(new.action,'_',' ')) end;
 insert into public.audit_logs(gym_id,actor_user_id,actor_email,actor_role,action,entity_type,entity_id,summary,details)
 values(new.gym_id,actor,coalesce(email,'Sistema'),coalesce(role_name,'system'),'MARKETING_'||new.action,
 new.entity_type,new.entity_id,label,new.details||jsonb_build_object('client_id',cid,'integration_audit_id',new.id));
 return new;
end$$;
drop trigger if exists marketing_activity_audit on public.marketing_audit;
create trigger marketing_activity_audit after insert on public.marketing_audit for each row execute function private.marketing_audit_to_activity();
create or replace function private.marketing_message_activity() returns trigger
language plpgsql security definer set search_path='' as $$
declare action text;label text;begin
 if tg_op='UPDATE' and new.status is not distinct from old.status then return new;end if;
 if tg_op='UPDATE' and new.status not in ('SENT','DELIVERED','READ','FAILED','UNCERTAIN','SKIPPED','NO_CONSENT') then return new;end if;
 action:=case when new.direction='HUMAN' then 'HUMAN' when new.direction='IN' then 'RECEIVED' else new.status end;
 label:=case action when 'HUMAN' then 'Respuesta humana por WhatsApp' when 'RECEIVED' then 'Mensaje recibido por WhatsApp'
 when 'QUEUED' then 'Mensaje WhatsApp programado' when 'SENT' then 'Mensaje WhatsApp enviado'
 when 'DELIVERED' then 'Mensaje WhatsApp entregado' when 'READ' then 'Mensaje WhatsApp leído'
 when 'FAILED' then 'Envío WhatsApp fallido' when 'UNCERTAIN' then 'Envío WhatsApp sin confirmación'
 when 'NO_CONSENT' then 'WhatsApp omitido por falta de autorización' when 'SKIPPED' then 'WhatsApp omitido'
 else 'Estado de mensaje WhatsApp actualizado' end;
 insert into public.audit_logs(gym_id,action,entity_type,entity_id,summary,details)
 values(new.gym_id,'MARKETING_MESSAGE_'||action,'marketing_messages',new.id::text,label,
 jsonb_build_object('client_id',new.client_id,'message_id',new.id,'automation_type',new.automation_type,'status',new.status,
 'sent_at',new.sent_at,'delivered_at',new.delivered_at,'read_at',new.read_at));
 return new;
end$$;
drop trigger if exists marketing_message_activity on public.marketing_messages;
create trigger marketing_message_activity after insert or update of status on public.marketing_messages
 for each row execute function private.marketing_message_activity();
create or replace function public.marketing_access(p_gym_id uuid,p_reception boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or not private.user_has_gym_role(p_gym_id,case when p_reception then array['admin','receptionist'] else array['admin'] end) then
 raise exception 'No tienes permiso para administrar Marketing en este gimnasio.' using errcode='42501';end if;
 return jsonb_build_object('gym_id',p_gym_id,'user_id',auth.uid(),'admin',private.user_has_gym_role(p_gym_id,array['admin']));end$$;
create or replace function private.marketing_consent() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if (tg_op='INSERT' and new.whatsapp_opt_in) or (tg_op='UPDATE' and new.whatsapp_opt_in is distinct from old.whatsapp_opt_in) then
 new.whatsapp_opt_in_at:=now();new.whatsapp_opt_in_by:=auth.uid();
 new.whatsapp_opt_in_source:=coalesce(nullif(new.whatsapp_opt_in_source,''),'Registro del personal');
 perform private.marketing_audit(new.gym_id,case when new.whatsapp_opt_in then 'CONSENT_GRANTED' else 'CONSENT_REVOKED' end,'client',new.id::text,jsonb_build_object('source',new.whatsapp_opt_in_source));end if;return new;end$$;
drop trigger if exists marketing_consent on public.clients;
create trigger marketing_consent before insert or update of whatsapp_opt_in on public.clients for each row execute function private.marketing_consent();
create or replace function public.marketing_set_consent(p_gym_id uuid,p_client_id bigint,p_enabled boolean,p_source text default 'Registro del personal') returns void language plpgsql security definer set search_path='' as $$
begin perform public.marketing_access(p_gym_id,true);
 update public.clients set whatsapp_opt_in=p_enabled,whatsapp_opt_in_source=left(p_source,160) where gym_id=p_gym_id and id=p_client_id;
 if not found then raise exception 'Cliente no encontrado.';end if;end$$;
create or replace function private.marketing_validate_rule(p_data jsonb) returns void language plpgsql set search_path='' as $$
declare c jsonb;v text;n integer;h integer;begin
 if length(trim(coalesce(p_data->>'name',''))) not between 1 and 120 or length(coalesce(p_data->>'body','')) not between 1 and 4096 then raise exception 'Completa el nombre y el mensaje.';end if;
 if jsonb_typeof(coalesce(p_data->'conditions','[]'))<>'array' or jsonb_array_length(coalesce(p_data->'conditions','[]'))>20 then raise exception 'Condiciones no válidas.';end if;
 for c in select * from jsonb_array_elements(coalesce(p_data->'conditions','[]')) loop
 if coalesce(c->>'field','')<>all(array['plan_id','plan_type','active','status','entries_remaining','days_remaining','days_absent','whatsapp_opt_in','payment_method','payment_pending','client_type']) or
 coalesce(c->>'op','')<>all(array['eq','ne','lt','lte','gt','gte','in']) or not c ? 'value' then raise exception 'Condición no admitida.';end if;end loop;
 n:=coalesce((p_data->'frequency'->>'count')::integer,1);h:=coalesce((p_data->'frequency'->>'hours')::integer,24);
 if n not between 0 and 100 or h not between 1 and 8760 then raise exception 'Frecuencia no válida.';end if;
 n:=coalesce((p_data->'trigger_options'->>'value')::integer,0);
 if n not between 0 and 3650 or (p_data->>'trigger_type' in ('MEMBERSHIP_OVERDUE_REPEAT','EVERY_N_CHECKINS','INACTIVITY') and n=0) then raise exception 'Intervalo no válido.';end if;
 if coalesce(p_data->'trigger_options'->>'time','09:00') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' then raise exception 'Hora no válida.';end if;
 for v in select m[1] from regexp_matches(p_data->>'body','\{\{([a-z_]+)\}\}','g') m loop
 if v<>all(array['nombre','apellido','gimnasio','plan','precio','fecha_vencimiento','dias_restantes','entradas_restantes','fecha_ultima_entrada','telefono','link_pago']) then raise exception 'Variable no admitida: %',v;end if;end loop;
end$$;
create or replace function private.marketing_rule_ready(p_gym uuid,p_template uuid,p_link boolean,p_body text) returns void language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from public.marketing_connections where gym_id=p_gym and provider='META' and status='CONNECTED') then raise exception 'Conecta WhatsApp para activar la automatización.';end if;
 if not exists(select 1 from public.whatsapp_templates where gym_id=p_gym and id=p_template and status='APPROVED' and body=p_body) then raise exception 'El mensaje necesita una plantilla aprobada por WhatsApp.';end if;
 if p_link and not exists(select 1 from public.marketing_connections where gym_id=p_gym and provider='WOMPI' and status='CONNECTED') then raise exception 'Para enviar links de renovación primero debes activar los pagos online.';end if;end$$;
create or replace function public.marketing_save_automation(p_gym_id uuid,p_data jsonb,p_id uuid default null,p_revision integer default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.marketing_automations;v_enabled boolean:=coalesce((p_data->>'enabled')::boolean,false);v_template uuid:=nullif(p_data->>'template_id','')::uuid;v_link boolean:=coalesce((p_data->>'include_payment_link')::boolean,false);begin
 perform public.marketing_access(p_gym_id);perform private.marketing_validate_rule(p_data);
 if v_enabled then perform private.marketing_rule_ready(p_gym_id,v_template,v_link,p_data->>'body');end if;
 if p_id is null then
 insert into public.marketing_automations(gym_id,name,enabled,trigger_type,trigger_options,conditions,body,include_payment_link,template_id,frequency,created_by)
 values(p_gym_id,trim(p_data->>'name'),v_enabled,p_data->>'trigger_type',coalesce(p_data->'trigger_options','{}'),coalesce(p_data->'conditions','[]'),p_data->>'body',v_link,v_template,coalesce(p_data->'frequency','{"count":1,"hours":24}'),auth.uid()) returning * into r;
 else
 update public.marketing_automations set name=trim(p_data->>'name'),enabled=v_enabled,trigger_type=p_data->>'trigger_type',trigger_options=coalesce(p_data->'trigger_options','{}'),conditions=coalesce(p_data->'conditions','[]'),body=p_data->>'body',include_payment_link=v_link,template_id=v_template,frequency=coalesce(p_data->'frequency','{"count":1,"hours":24}'),revision=revision+1,updated_at=now()
 where id=p_id and gym_id=p_gym_id and revision=p_revision and deleted_at is null returning * into r;
 if not found then raise exception 'La automatización cambió en otro equipo. Actualiza y vuelve a intentarlo.';end if;end if;
 perform private.marketing_audit(p_gym_id,case when p_id is null then 'AUTOMATION_CREATED' else 'AUTOMATION_UPDATED' end,'automation',r.id::text,jsonb_build_object('enabled',r.enabled,'revision',r.revision));return to_jsonb(r);end$$;
create or replace function public.marketing_automation_action(p_gym_id uuid,p_id uuid,p_action text,p_revision integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.marketing_automations;begin perform public.marketing_access(p_gym_id);
 select * into r from public.marketing_automations where gym_id=p_gym_id and id=p_id and deleted_at is null for update;
 if not found or r.revision<>p_revision then raise exception 'Actualiza la lista de automatizaciones.';end if;
 if p_action='duplicate' then return public.marketing_save_automation(p_gym_id,to_jsonb(r)||jsonb_build_object('name',left(r.name,110)||' (copia)','enabled',false));end if;
 if p_action not in ('enable','pause','delete') then raise exception 'Acción no válida.';end if;
 if p_action='enable' then perform private.marketing_rule_ready(p_gym_id,r.template_id,r.include_payment_link,r.body);end if;
 update public.marketing_automations set enabled=p_action='enable',deleted_at=case when p_action='delete' then now() else null end,revision=revision+1,updated_at=now() where id=r.id returning * into r;
 perform private.marketing_audit(p_gym_id,'AUTOMATION_'||upper(p_action),'automation',r.id::text);return to_jsonb(r);end$$;
create or replace function public.marketing_save_template(p_gym_id uuid,p_data jsonb,p_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.whatsapp_templates;begin perform public.marketing_access(p_gym_id);
 if p_id is null then
 insert into public.whatsapp_templates(gym_id,name,language,category,body,variables) values(p_gym_id,p_data->>'name',coalesce(p_data->>'language','es_CO'),coalesce(p_data->>'category','UTILITY'),p_data->>'body',array(select jsonb_array_elements_text(coalesce(p_data->'variables','[]')))) returning * into r;
 else update public.whatsapp_templates set name=p_data->>'name',body=p_data->>'body',category=coalesce(p_data->>'category','UTILITY'),variables=array(select jsonb_array_elements_text(coalesce(p_data->'variables','[]'))),status='DRAFT',updated_at=now() where gym_id=p_gym_id and id=p_id and status in ('DRAFT','REJECTED') returning * into r;
 if not found then raise exception 'Crea otra plantilla para modificar un mensaje que ya está en revisión o aprobado.';end if;end if;
 perform private.marketing_audit(p_gym_id,'TEMPLATE_SAVED','template',r.id::text);return to_jsonb(r);end$$;
create or replace function public.marketing_features(p_gym_id uuid,p_flags jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.marketing_settings;begin perform public.marketing_access(p_gym_id);
 if (coalesce((p_flags->>'whatsapp_enabled')::boolean,false) or coalesce((p_flags->>'chatbot_enabled')::boolean,false) or coalesce((p_flags->>'marketing_automation_enabled')::boolean,false)) and not exists(select 1 from public.marketing_connections where gym_id=p_gym_id and provider='META' and status='CONNECTED') then raise exception 'Conecta WhatsApp primero.';end if;
 if coalesce((p_flags->>'online_payments_enabled')::boolean,false) and not exists(select 1 from public.marketing_connections where gym_id=p_gym_id and provider='WOMPI' and status='CONNECTED') then raise exception 'Conecta Wompi primero.';end if;
 insert into public.marketing_settings(gym_id) values(p_gym_id) on conflict do nothing;
 update public.marketing_settings set whatsapp_enabled=coalesce((p_flags->>'whatsapp_enabled')::boolean,whatsapp_enabled),online_payments_enabled=coalesce((p_flags->>'online_payments_enabled')::boolean,online_payments_enabled),chatbot_enabled=coalesce((p_flags->>'chatbot_enabled')::boolean,chatbot_enabled),marketing_automation_enabled=coalesce((p_flags->>'marketing_automation_enabled')::boolean,marketing_automation_enabled),human_pause_minutes=coalesce((p_flags->>'human_pause_minutes')::integer,human_pause_minutes),bot_session_minutes=coalesce((p_flags->>'bot_session_minutes')::integer,bot_session_minutes),updated_at=now(),updated_by=auth.uid() where gym_id=p_gym_id returning * into r;
 perform private.marketing_audit(p_gym_id,'FEATURES_UPDATED','settings',p_gym_id::text,p_flags);return to_jsonb(r);end$$;
create or replace function public.marketing_summary(p_gym_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare since timestamptz;begin perform public.marketing_access(p_gym_id);
 select date_trunc('month',now() at time zone g.timezone) at time zone g.timezone into since from public.gyms g where id=p_gym_id;
 return jsonb_build_object('settings',(select to_jsonb(s) from public.marketing_settings s where s.gym_id=p_gym_id),'connections',coalesce((select jsonb_agg(c) from public.marketing_connections c where c.gym_id=p_gym_id),'[]'),
 'automations_active',(select count(*) from public.marketing_automations where gym_id=p_gym_id and enabled and deleted_at is null),
 'sent',(select count(*) from public.marketing_messages where gym_id=p_gym_id and direction='OUT' and status in ('SENT','DELIVERED','READ') and created_at>=since),
 'delivered',(select count(*) from public.marketing_messages where gym_id=p_gym_id and direction='OUT' and status in ('DELIVERED','READ') and created_at>=since),
 'read',(select count(*) from public.marketing_messages where gym_id=p_gym_id and direction='OUT' and status='READ' and created_at>=since),
 'queued',(select count(*) from public.marketing_messages where gym_id=p_gym_id and status in ('QUEUED','PROCESSING')),
 'links',(select count(*) from public.payment_requests where gym_id=p_gym_id and created_at>=since),
 'payments_started',(select count(distinct payment_request_id) from public.payment_transactions where gym_id=p_gym_id and processed_at>=since),
 'payments_approved',(select count(*) from public.payment_requests where gym_id=p_gym_id and status='APPROVED' and paid_at>=since),
 'recovered_cents',coalesce((select sum(amount_in_cents) from public.payment_requests p where p.gym_id=p_gym_id and p.status='APPROVED' and p.mode='prod' and p.paid_at>=since and exists(select 1 from public.marketing_messages m where m.gym_id=p_gym_id and m.payment_request_id=p.id and m.automation_id is not null)),0));end$$;
create or replace function public.marketing_conversation_mode(p_gym_id uuid,p_id uuid,p_mode text) returns void language plpgsql security definer set search_path='' as $$
begin perform public.marketing_access(p_gym_id,true);
 if p_mode not in ('BOT','HUMAN','PAUSED') then raise exception 'Estado no válido.';end if;
 update public.whatsapp_conversations set mode=p_mode,last_human_at=case when p_mode='HUMAN' then now() else last_human_at end,pause_until=case when p_mode='HUMAN' then now()+make_interval(mins=>coalesce((select human_pause_minutes from public.marketing_settings where gym_id=p_gym_id),120)) else null end,updated_at=now() where id=p_id and gym_id=p_gym_id;
 if not found then raise exception 'Conversación no encontrada.';end if;perform private.marketing_audit(p_gym_id,'CONVERSATION_'||p_mode,'conversation',p_id::text);end$$;
create or replace function public.marketing_review_link(p_gym_id uuid,p_id uuid,p_client_id bigint,p_approved boolean) returns void language plpgsql security definer set search_path='' as $$
declare r public.chatbot_link_requests;begin perform public.marketing_access(p_gym_id,true);
 select * into r from public.chatbot_link_requests where gym_id=p_gym_id and id=p_id and status='PENDING' for update;
 if not found then raise exception 'La solicitud ya fue atendida.';end if;
 if p_approved and not exists(select 1 from public.clients where id=p_client_id and gym_id=p_gym_id and active) then raise exception 'Cliente no encontrado.';end if;
 update public.chatbot_link_requests set status=case when p_approved then 'APPROVED' else 'REJECTED' end,client_id=case when p_approved then p_client_id end,reviewed_by=auth.uid(),reviewed_at=now() where id=p_id;
 if p_approved then update public.whatsapp_conversations set client_id=p_client_id,verification_state='VERIFIED',verified_phone=sender_number,verified_until=now()+interval '30 minutes',failed_attempts=0,locked_until=null where id=r.conversation_id and gym_id=p_gym_id;end if;
 perform private.marketing_audit(p_gym_id,'CHATBOT_LINK_'||case when p_approved then 'APPROVED' else 'REJECTED' end,'link_request',p_id::text);end$$;

create or replace function private.marketing_operable(p_gym uuid) returns boolean language plpgsql security definer set search_path='' as $$
declare v boolean;begin if not exists(select 1 from public.gyms where id=p_gym) then return false;end if;
 if to_regprocedure('private.subscription_open(uuid)') is not null then execute 'select private.subscription_open($1)' into v using p_gym;return v;end if;return true;end$$;
create or replace function public.marketing_service_credentials(p_gym_id uuid,p_provider text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;begin
 -- Vault stays server-side, never returned by an authenticated desktop RPC.
 execute 'select v.decrypted_secret::jsonb from vault.decrypted_secrets v join private.marketing_credentials c on c.secret_id=v.id where c.gym_id=$1 and c.provider=$2' into v using p_gym_id,p_provider;return v;end$$;
create or replace function public.marketing_service_connect(p_gym_id uuid,p_provider text,p_secrets jsonb,p_display jsonb,p_mode text default 'test') returns void language plpgsql security definer set search_path='' as $$
declare sid uuid;begin
 if p_provider not in ('META','WOMPI') or p_mode not in ('test','prod') or not private.marketing_operable(p_gym_id) then raise exception 'Conexión no permitida.';end if;
 if p_mode='prod' and not (select production_allowed from private.marketing_platform where singleton) then raise exception 'La producción necesita autorización del propietario.';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_gym_id::text||p_provider,0));
 select secret_id into sid from private.marketing_credentials where gym_id=p_gym_id and provider=p_provider;
 if sid is null then execute 'select vault.create_secret($1,$2,$3)' into sid using p_secrets::text,'marketing/'||p_gym_id||'/'||p_provider,'Credenciales privadas de integración';
 else execute 'select vault.update_secret($1,$2)' using sid,p_secrets::text;end if;
 insert into private.marketing_credentials(gym_id,provider,secret_id) values(p_gym_id,p_provider,sid) on conflict(gym_id,provider) do update set secret_id=excluded.secret_id,updated_at=now();
 insert into public.marketing_connections(gym_id,provider,status,mode,display_number,provider_account_id,phone_number_id,coexistence,metadata,last_checked_at)
 values(p_gym_id,p_provider,'CONNECTED',p_mode,coalesce(p_display->>'display_number',''),coalesce(p_display->>'provider_account_id',''),coalesce(p_display->>'phone_number_id',''),coalesce((p_display->>'coexistence')::boolean,false),jsonb_build_object('merchant_name',p_display->>'merchant_name','webhook_confirmed',coalesce((p_display->>'webhook_confirmed')::boolean,false)),now())
 on conflict(gym_id,provider) do update set status='CONNECTED',mode=excluded.mode,display_number=excluded.display_number,provider_account_id=excluded.provider_account_id,phone_number_id=excluded.phone_number_id,coexistence=excluded.coexistence,metadata=excluded.metadata,last_checked_at=now(),last_error='',updated_at=now();
 insert into public.marketing_settings(gym_id) values(p_gym_id) on conflict do nothing;
 perform private.marketing_audit(p_gym_id,p_provider||'_CONNECTED','connection',p_provider,jsonb_build_object('mode',p_mode,'responsible_user_id',p_display->>'actor_user_id'));end$$;
create or replace function public.marketing_disconnect(p_gym_id uuid,p_provider text) returns void language plpgsql security definer set search_path='' as $$
begin perform public.marketing_access(p_gym_id);
 if p_provider not in ('META','WOMPI') then raise exception 'Servicio no válido.';end if;
 update public.marketing_connections set status='DISCONNECTED',updated_at=now() where gym_id=p_gym_id and provider=p_provider;
 if p_provider='META' then update public.marketing_settings set whatsapp_enabled=false,chatbot_enabled=false,marketing_automation_enabled=false where gym_id=p_gym_id;
 else update public.marketing_settings set online_payments_enabled=false where gym_id=p_gym_id;end if;
 -- Existing provider credentials are retained to reconcile payments already in flight.
 -- Disconnecting here never deregisters or migrates an existing WhatsApp Business number.
 perform private.marketing_audit(p_gym_id,p_provider||'_DISCONNECTED','connection',p_provider);end$$;
create or replace function public.marketing_service_limit(p_gym_id uuid,p_bucket text,p_max integer,p_seconds integer) returns boolean language plpgsql security definer set search_path='' as $$
declare n integer;w timestamptz;begin
 if p_max not between 1 and 10000 or p_seconds not between 1 and 86400 or length(p_bucket)>160 then raise exception 'Límite no válido.';end if;
 w:=to_timestamp(floor(extract(epoch from now())/p_seconds)*p_seconds);
 insert into private.marketing_rate_limits(gym_id,bucket,window_start,hits) values(p_gym_id,p_bucket,w,1) on conflict(gym_id,bucket,window_start) do update set hits=private.marketing_rate_limits.hits+1 returning hits into n;return n<=p_max;end$$;
create or replace function public.marketing_service_contexts(p_gym_id uuid,p_after bigint default 0,p_limit integer default 200) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;begin if not private.marketing_operable(p_gym_id) then return '[]';end if;
 select coalesce(jsonb_agg(x),'[]') into v from (select c.id client_id,c.first_name,c.last_name,c.phone,coalesce(c.birth_date,c.birthdate) birth_date,c.active,c.whatsapp_opt_in,c.created_at,
 g.id gym_id,g.name gym_name,g.timezone,private.gym_local_date(g.id) today,now() server_now,
 private.membership_snapshot_json(g.id,c.id) membership,
 (select to_jsonb(p) from public.plans p join public.memberships m on m.plan_id=p.id and m.gym_id=p.gym_id where m.gym_id=g.id and m.client_id=c.id and m.id=(private.membership_snapshot_json(g.id,c.id)->>'membership_id')::bigint limit 1) plan,
 (select max(ch.checkin_at) from public.checkins ch where ch.gym_id=g.id and ch.client_id=c.id and ch.result='PERMITIDA') last_checkin,
 (select count(*) from public.checkins ch where ch.gym_id=g.id and ch.client_id=c.id and ch.result='PERMITIDA') checkin_count
 from public.clients c join public.gyms g on g.id=c.gym_id where c.gym_id=p_gym_id and c.id>p_after order by c.id limit least(greatest(p_limit,1),500)) x;return v;end$$;
create or replace function private.marketing_capture_event() returns trigger language plpgsql security definer set search_path='' as $$
declare et text;data jsonb;begin
 if not exists(select 1 from public.marketing_settings where gym_id=new.gym_id and (marketing_automation_enabled or chatbot_enabled)) or exists(select 1 from private.ticket_import_context where transaction_id=txid_current() and gym_id=new.gym_id) then return new;end if;
 if tg_table_name='checkins' then if new.result<>'PERMITIDA' then return new;end if;et:='CHECK_IN_SUCCESS';
 else if new.payment_status<>'posted' or new.payment_method='Wompi' then return new;end if;et:='MEMBERSHIP_RENEWED';end if;
 data:=to_jsonb(new);
 if tg_table_name='checkins' then data:=data||jsonb_build_object('first_of_day',(select count(*)=1 from public.checkins ch where ch.gym_id=new.gym_id and ch.client_id=new.client_id and ch.result='PERMITIDA' and (ch.checkin_at at time zone (select timezone from public.gyms where id=new.gym_id))::date=private.gym_local_date(new.gym_id)),'first_of_membership',(select count(*)=1 from public.checkins ch where ch.gym_id=new.gym_id and ch.membership_id=new.membership_id and ch.result='PERMITIDA'),'checkin_count',(select count(*) from public.checkins ch where ch.gym_id=new.gym_id and ch.client_id=new.client_id and ch.result='PERMITIDA'));end if;
 insert into private.marketing_events(gym_id,client_id,event_type,entity_id,payload) values(new.gym_id,new.client_id,et,new.id::text,data) on conflict do nothing;return new;end$$;
drop trigger if exists marketing_checkin_event on public.checkins;
create trigger marketing_checkin_event after insert on public.checkins for each row execute function private.marketing_capture_event();
drop trigger if exists marketing_renewal_event on public.memberships;
create trigger marketing_renewal_event after insert on public.memberships for each row execute function private.marketing_capture_event();
create or replace function public.marketing_service_enqueue(p_gym_id uuid,p_automation_id uuid,p_client_id bigint,p_dedupe_key text,p_phone text,p_body text,p_parameters jsonb,p_payment_request_id uuid default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.marketing_automations;c public.clients;t public.whatsapp_templates;v_status text:='QUEUED';reason text;rid uuid;mid bigint;freq_n integer;freq_hours integer;begin
 if not private.marketing_operable(p_gym_id) then return '{"status":"SKIPPED","reason":"INACTIVE_GYM"}';end if;
 select * into a from public.marketing_automations where id=p_automation_id and gym_id=p_gym_id and enabled and deleted_at is null for update;
 if not found or not exists(select 1 from public.marketing_settings where gym_id=p_gym_id and whatsapp_enabled and marketing_automation_enabled) then return '{"status":"SKIPPED","reason":"DISABLED"}';end if;
 if exists(select 1 from public.automation_runs where gym_id=p_gym_id and dedupe_key=p_dedupe_key) then return '{"status":"SKIPPED","reason":"DUPLICATE"}';end if;
 select * into c from public.clients where gym_id=p_gym_id and id=p_client_id;
 if not found then raise exception 'Cliente no encontrado.';end if;
 select * into t from public.whatsapp_templates where gym_id=p_gym_id and id=a.template_id and status='APPROVED' and body=a.body;
 if not found then v_status:='SKIPPED';reason:='TEMPLATE_NOT_APPROVED';end if;
 if not c.whatsapp_opt_in then v_status:='NO_CONSENT';reason:='NO_CONSENT';end if;
 if p_phone !~ '^[1-9][0-9]{7,14}$' then v_status:='SKIPPED';reason:='INVALID_PHONE';end if;
 if exists(select 1 from public.whatsapp_conversations where gym_id=p_gym_id and sender_number=p_phone and mode<>'BOT') then v_status:='SKIPPED';reason:='HUMAN_HANDOFF';end if;
 if not exists(select 1 from public.marketing_connections where gym_id=p_gym_id and provider='META' and status='CONNECTED') then v_status:='SKIPPED';reason:='DISCONNECTED';end if;
 freq_n:=coalesce((a.frequency->>'count')::integer,1);freq_hours:=coalesce((a.frequency->>'hours')::integer,24);
 if v_status='QUEUED' and freq_n>0 and (select count(*) from public.automation_runs ar where ar.gym_id=p_gym_id and ar.automation_id=a.id and ar.client_id=p_client_id and ar.status in ('QUEUED','SENT','UNCERTAIN') and ar.executed_at>now()-make_interval(hours=>freq_hours))>=freq_n then v_status:='SKIPPED';reason:='FREQUENCY';end if;
 insert into public.automation_runs(gym_id,automation_id,client_id,dedupe_key,status,reason) values(p_gym_id,a.id,c.id,p_dedupe_key,v_status,reason) returning id into rid;
 insert into public.marketing_messages(gym_id,client_id,automation_type,source_date,client_name,phone,template_name,language_code,template_parameters,status,automation_id,dedupe_key,body,payment_request_id,error_message)
 values(p_gym_id,c.id,a.trigger_type,private.gym_local_date(p_gym_id),trim(c.first_name||' '||c.last_name),p_phone,coalesce(t.name,''),coalesce(t.language,'es_CO'),p_parameters,v_status,a.id,p_dedupe_key,p_body,p_payment_request_id,coalesce(reason,'')) returning id into mid;
 update public.marketing_automations set last_run_at=now() where id=a.id;return jsonb_build_object('status',v_status,'reason',reason,'run_id',rid,'message_id',mid);end$$;
create or replace function public.marketing_service_claim(p_limit integer default 50,p_message_id bigint default null) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;begin
 -- No automatic resend after an ambiguous provider timeout: Meta has no send idempotency key.
 with stale as (
 update public.marketing_messages set status='UNCERTAIN',error_message='No se pudo confirmar el resultado del envío.',updated_at=now() where status='PROCESSING' and claimed_at<now()-interval '3 minutes' returning gym_id,dedupe_key
 ) update public.automation_runs a set status='UNCERTAIN',reason='PROVIDER_UNCERTAIN' from stale s where a.gym_id=s.gym_id and a.dedupe_key=s.dedupe_key;
 with candidates as(select m.id from public.marketing_messages m join public.marketing_settings s on s.gym_id=m.gym_id join public.marketing_connections c on c.gym_id=m.gym_id and c.provider='META' where m.status='QUEUED' and (p_message_id is null or m.id=p_message_id) and m.scheduled_for<=now() and s.whatsapp_enabled and c.status='CONNECTED' and private.marketing_operable(m.gym_id) order by m.id for update of m skip locked limit least(greatest(p_limit,1),100)),claimed as(update public.marketing_messages m set status='PROCESSING',claim_id=gen_random_uuid(),claimed_at=now(),attempts=attempts+1 from candidates c where m.id=c.id returning m.*) select coalesce(jsonb_agg(claimed),'[]') into v from claimed;return v;end$$;
create or replace function public.marketing_service_send_result(p_id bigint,p_claim_id uuid,p_status text,p_provider_id text default '',p_error text default '') returns boolean language plpgsql security definer set search_path='' as $$
declare r public.marketing_messages;e record;v_gym uuid;begin
 if p_status not in ('SENT','FAILED','SKIPPED','NO_CONSENT','UNCERTAIN') then raise exception 'Estado no válido.';end if;
 if coalesce(p_provider_id,'')<>'' then
 select gym_id into v_gym from public.marketing_messages where id=p_id and claim_id=p_claim_id;
 perform pg_advisory_xact_lock(hashtextextended(v_gym::text||'/delivery/'||p_provider_id,0));
 end if;
 update public.marketing_messages set status=p_status,whatsapp_message_id=p_provider_id,error_message=left(p_error,500),sent_at=case when p_status='SENT' then now() end,updated_at=now() where id=p_id and claim_id=p_claim_id and status in ('PROCESSING','UNCERTAIN') returning * into r;
 if not found then return false;end if;
 update public.automation_runs set status=p_status,reason=left(p_error,500) where gym_id=r.gym_id and dedupe_key=r.dedupe_key;
 -- Provider delivery callbacks can precede the HTTP send response. Replay their
 -- stored, signed states under the same lock instead of losing them.
 if coalesce(p_provider_id,'')<>'' then
 for e in select payload from private.marketing_webhook_events where provider='META_STATUS' and gym_id=r.gym_id and payload->>'message_id'=p_provider_id order by received_at loop
 perform public.marketing_service_status(r.gym_id,p_provider_id,e.payload->>'status',(e.payload->>'at')::timestamptz);
 end loop;end if;return true;end$$;

create or replace function public.marketing_create_test_client(p_gym_id uuid) returns bigint language plpgsql security definer set search_path='' as $$
declare cid bigint;begin perform public.marketing_access(p_gym_id);perform pg_advisory_xact_lock(hashtextextended(p_gym_id::text||'/sandbox',0));
 select client_id into cid from private.marketing_sandbox_clients where gym_id=p_gym_id;if cid is not null then return cid;end if;
 insert into public.clients(gym_id,document,first_name,last_name,active) values(p_gym_id,'TEST-'||gen_random_uuid(),'PRUEBA','Integraciones',true) returning id into cid;
 insert into private.marketing_sandbox_clients(gym_id,client_id,created_by) values(p_gym_id,cid,auth.uid());
 perform private.marketing_audit(p_gym_id,'SANDBOX_CLIENT_CREATED','client',cid::text);return cid;end$$;
create or replace function public.marketing_service_payment_request(p_gym_id uuid,p_client_id bigint,p_plan_id bigint,p_key text) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.payment_requests;p public.plans;conn public.marketing_connections;begin
 if not private.marketing_operable(p_gym_id) then raise exception 'El gimnasio no tiene una suscripción activa.';end if;
 select * into conn from public.marketing_connections where gym_id=p_gym_id and provider='WOMPI' and status='CONNECTED';
 if not found or not exists(select 1 from public.marketing_settings where gym_id=p_gym_id and online_payments_enabled) then raise exception 'Los pagos online todavía no están habilitados.';end if;
 if conn.mode='prod' and not (select production_allowed from private.marketing_platform where singleton) then raise exception 'Producción no autorizada.';end if;
 if conn.mode='test' and not exists(select 1 from private.marketing_sandbox_clients where gym_id=p_gym_id and client_id=p_client_id) then raise exception 'Sandbox utiliza únicamente el cliente de prueba de integraciones.';end if;
 if not exists(select 1 from public.clients where gym_id=p_gym_id and id=p_client_id and active) then raise exception 'Cliente no disponible.';end if;
 select * into p from public.plans where gym_id=p_gym_id and id=p_plan_id and active and price>0;
 if not found then raise exception 'El plan no está disponible para pagos online.';end if;
 if length(p_key) not between 8 and 200 then raise exception 'Referencia de solicitud no válida.';end if;
 insert into public.payment_requests(gym_id,client_id,plan_id,plan_snapshot,mode,amount_in_cents,reference,idempotency_key,expires_at)
 values(p_gym_id,p_client_id,p.id,to_jsonb(p),conn.mode,p.price*100,'GS-'||replace(gen_random_uuid()::text,'-',''),p_key,now()+interval '48 hours') on conflict(gym_id,idempotency_key) do nothing returning * into r;
 if not found then select * into r from public.payment_requests where gym_id=p_gym_id and idempotency_key=p_key;
 if r.client_id<>p_client_id or r.plan_id<>p_plan_id or r.mode<>conn.mode then raise exception 'La referencia ya pertenece a otra solicitud.';end if;end if;return to_jsonb(r);end$$;
-- Reuse the installed, already tested calendar/quota renewal implementation.
-- Only the permission prelude is replaced; this private clone is service-only.
do $$declare def text;before text;sig regprocedure;begin
 sig:=to_regprocedure('private.ztattuz_add_membership(uuid,bigint,bigint,date,bigint,text,text,text)');
 if sig is null then sig:=to_regprocedure('public.add_membership_accumulating_internal(uuid,bigint,bigint,date,bigint,text,text,text)');end if;
 if sig is null then raise exception 'No se encontró el motor actual de renovación.';end if;
 def:=pg_get_functiondef(sig);before:=def;
 def:=regexp_replace(def,'CREATE OR REPLACE FUNCTION (private.ztattuz_add_membership|public.add_membership_accumulating_internal)\(', 'CREATE OR REPLACE FUNCTION private.marketing_apply_membership(');
 def:=replace(def,'p_notes text)','p_notes text, p_plan_snapshot jsonb)');
 def:=regexp_replace(def,'if not private.user_has_gym_role\([\s\S]*?end if;','','i');
 if def=before or position('user_has_gym_role' in def)>0 then raise exception 'Revisa la compatibilidad del motor de renovación antes de continuar.';end if;
 def:=replace(def,'from public.plans p','from jsonb_populate_record(null::public.plans,p_plan_snapshot) p');
 if position('jsonb_populate_record' in def)=0 then raise exception 'No se pudo fijar el plan de la solicitud.';end if;execute def;
end$$;
create or replace function public.marketing_service_apply_payment(p_gym_id uuid,p_transaction jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.payment_requests;existing public.payment_transactions;tid text:=p_transaction->>'id';v_status text:=p_transaction->>'status';v_mode text:=p_transaction->>'mode';v_amount bigint;v_mid bigint;v_end date;v_started timestamptz;begin
 if length(coalesce(tid,'')) not between 1 and 150 or coalesce(v_status,'') not in ('PENDING','APPROVED','DECLINED','VOIDED','ERROR') then raise exception 'Transacción no válida.';end if;
 select * into r from public.payment_requests where gym_id=p_gym_id and reference=p_transaction->>'reference' for update;
 if not found then raise exception 'Referencia de pago desconocida.';end if;
 if (p_transaction->>'amount_in_cents')::bigint is distinct from r.amount_in_cents or (p_transaction->>'currency') is distinct from r.currency or v_mode is distinct from r.mode then raise exception 'El valor, la moneda o el ambiente no coinciden con la solicitud.';end if;
 select * into existing from public.payment_transactions where provider_transaction_id=tid and mode=v_mode;
 if found and (existing.gym_id<>p_gym_id or existing.payment_request_id<>r.id) then raise exception 'Transacción asociada a otra solicitud.';end if;
 if r.status='APPROVED' and existing.status='APPROVED' and v_status='APPROVED' then return jsonb_build_object('duplicate',true,'membership_id',r.renewed_membership_id);end if;
 if p_transaction->>'created_at' is not null and (p_transaction->>'created_at') !~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})$' then
 raise exception 'La fecha de la transacción debe incluir hora y timezone.';end if;
 v_started:=(p_transaction->>'created_at')::timestamptz;
 insert into public.payment_transactions(gym_id,payment_request_id,provider_transaction_id,mode,status,amount_in_cents,currency,reference,provider_created_at)
 values(p_gym_id,r.id,tid,v_mode,v_status,r.amount_in_cents,r.currency,r.reference,v_started)
 on conflict(mode,provider_transaction_id) do update set status=excluded.status,processed_at=now();
 if r.status='APPROVED' then
 -- A second charge or reversal needs review; never renew twice or silently undo access.
 update public.payment_transactions set requires_review=true where mode=v_mode and provider_transaction_id=tid;
 perform private.marketing_audit(p_gym_id,'PAYMENT_REQUIRES_REVIEW','payment_request',r.id::text,jsonb_build_object('transaction_id',tid,'status',v_status));
 return jsonb_build_object('duplicate',true,'requires_review',true,'membership_id',r.renewed_membership_id);end if;
 if v_status='APPROVED' then
 if r.client_id is null or r.plan_id is null or v_started is null or v_started>r.expires_at or v_started<r.created_at-interval '1 minute' then raise exception 'No se puede aplicar este pago automáticamente. Requiere revisión.';end if;
 if v_mode='test' and not exists(select 1 from private.marketing_sandbox_clients where gym_id=p_gym_id and client_id=r.client_id) then raise exception 'Cliente sandbox no válido.';end if;
 v_amount:=case when v_mode='test' then 0 else r.amount_in_cents/100 end;
 if r.amount_in_cents%100<>0 then raise exception 'El valor no corresponde al plan.';end if;
 select m.membership_id,m.end_date into v_mid,v_end from private.marketing_apply_membership(p_gym_id,r.client_id,r.plan_id,private.gym_local_date(p_gym_id),v_amount,'Wompi',r.reference,case when v_mode='test' then 'PRUEBA SANDBOX · sin ingreso real' else 'Renovación online confirmada' end,r.plan_snapshot) m;
 update public.memberships set payment_source=case when v_mode='test' then 'WOMPI_TEST' else 'WOMPI' end,paid_at=now() where id=v_mid and gym_id=p_gym_id;
 update public.payment_requests set status='APPROVED',paid_at=now(),renewed_membership_id=v_mid where id=r.id;
 insert into private.marketing_events(gym_id,client_id,event_type,entity_id,payload) values(p_gym_id,r.client_id,'ONLINE_APPROVED',r.id::text,jsonb_build_object('payment_request_id',r.id,'membership_id',v_mid,'mode',v_mode)) on conflict do nothing;
 perform private.marketing_audit(p_gym_id,'PAYMENT_PROCESSED','payment_request',r.id::text,jsonb_build_object('transaction_id',tid,'mode',v_mode));
 perform private.marketing_audit(p_gym_id,'MEMBERSHIP_RENEWED','membership',v_mid::text,jsonb_build_object('payment_request_id',r.id));
 return jsonb_build_object('duplicate',false,'membership_id',v_mid,'end_date',v_end,'mode',v_mode);
 else
 update public.payment_requests set status=v_status where id=r.id;
 if v_status='DECLINED' then insert into private.marketing_events(gym_id,client_id,event_type,entity_id,payload) values(p_gym_id,r.client_id,'ONLINE_DECLINED',tid,jsonb_build_object('payment_request_id',r.id,'mode',v_mode)) on conflict do nothing;end if;
 return jsonb_build_object('status',v_status,'duplicate',false);end if;
end$$;

create or replace function private.marketing_phone(p_phone text) returns text language sql immutable set search_path='' as $$
 select case when length(d)=10 then '57'||d when d ~ '^[1-9][0-9]{7,14}$' then d else null end from (select regexp_replace(coalesce(p_phone,''),'[^0-9]','','g') d) x
$$;
create index if not exists clients_marketing_phone on public.clients(gym_id,private.marketing_phone(phone));
alter table public.whatsapp_conversations add column if not exists verified_registered_phone text;
create or replace function public.marketing_service_chat(p_gym_id uuid,p_sender text,p_action text,p_data jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare conv public.whatsapp_conversations;c public.clients;cid bigint;num integer;v_date date;mins integer;begin
 if p_sender !~ '^[1-9][0-9]{7,14}$' or not private.marketing_operable(p_gym_id) then raise exception 'Solicitud no válida.';end if;
 if not exists(select 1 from public.marketing_settings where gym_id=p_gym_id and whatsapp_enabled and chatbot_enabled) then return '{"state":"DISABLED"}';end if;
 insert into public.whatsapp_conversations(gym_id,sender_number) values(p_gym_id,p_sender) on conflict do nothing;
 select * into conv from public.whatsapp_conversations where gym_id=p_gym_id and sender_number=p_sender for update;
 if p_action='human_echo' then
 update public.whatsapp_conversations set mode='HUMAN',last_human_at=now(),pause_until=now()+make_interval(mins=>(select human_pause_minutes from public.marketing_settings where gym_id=p_gym_id)),updated_at=now() where id=conv.id;
 perform private.marketing_audit(p_gym_id,'HUMAN_MESSAGE','conversation',conv.id::text);return '{"state":"HUMAN"}';end if;
 if p_action='inbound' then update public.whatsapp_conversations set last_inbound_at=now(),updated_at=now() where id=conv.id;conv.last_inbound_at:=now();end if;
 if conv.mode='HUMAN' and conv.pause_until<=now() then update public.whatsapp_conversations set mode='BOT',pause_until=null where id=conv.id;conv.mode:='BOT';end if;
 if conv.mode<>'BOT' then return jsonb_build_object('state',conv.mode,'conversation_id',conv.id);end if;
 if conv.locked_until>now() then return jsonb_build_object('state','LOCKED','conversation_id',conv.id);end if;
 if conv.client_id is not null then select * into c from public.clients where gym_id=p_gym_id and id=conv.client_id;end if;
 if p_action in ('inbound','session') and conv.verification_state='VERIFIED' and conv.verified_until>now() and conv.verified_phone=p_sender and c.id is not null and conv.verified_registered_phone is not distinct from private.marketing_phone(c.phone) then
 return jsonb_build_object('state','VERIFIED','conversation_id',conv.id,'client_id',c.id,'first_name',c.first_name,'last_inbound_at',coalesce(conv.last_inbound_at,now()),'membership',private.membership_snapshot_json(p_gym_id,c.id));end if;
 if p_action='handoff' then
 update public.whatsapp_conversations set mode='HUMAN',last_human_at=now(),pause_until=now()+make_interval(mins=>(select human_pause_minutes from public.marketing_settings where gym_id=p_gym_id)),updated_at=now() where id=conv.id;
 perform private.marketing_audit(p_gym_id,'HUMAN_HANDOFF','conversation',conv.id::text);return '{"state":"HUMAN"}';end if;
 if p_action='verify' then
 if not public.marketing_service_limit(p_gym_id,'verify/'||p_sender,5,3600) then update public.whatsapp_conversations set locked_until=now()+interval '1 hour',verification_state='LOCKED' where id=conv.id;return '{"state":"LOCKED"}';end if;
 select count(*),min(id) into num,cid from public.clients where gym_id=p_gym_id and private.marketing_phone(phone)=p_sender;
 begin v_date:=(p_data->>'birth_date')::date;exception when others then v_date:=null;end;
 if num=1 then select * into c from public.clients where gym_id=p_gym_id and id=cid;end if;
 if num=1 and v_date is not null and coalesce(c.birth_date,c.birthdate)=v_date then
 select bot_session_minutes into mins from public.marketing_settings where gym_id=p_gym_id;
 update public.whatsapp_conversations set client_id=cid,verification_state='VERIFIED',verified_until=now()+make_interval(mins=>mins),verified_phone=p_sender,verified_registered_phone=private.marketing_phone(c.phone),failed_attempts=0,locked_until=null,updated_at=now() where id=conv.id;
 perform private.marketing_audit(p_gym_id,'CHATBOT_VERIFIED','conversation',conv.id::text);return jsonb_build_object('state','VERIFIED','conversation_id',conv.id,'client_id',cid,'first_name',c.first_name,'last_inbound_at',conv.last_inbound_at,'membership',private.membership_snapshot_json(p_gym_id,cid));end if;
 update public.whatsapp_conversations set failed_attempts=failed_attempts+1,verification_state=case when failed_attempts>=4 then 'LOCKED' else 'DOB' end,locked_until=case when failed_attempts>=4 then now()+interval '1 hour' else null end,verified_until=null,updated_at=now() where id=conv.id;
 perform private.marketing_audit(p_gym_id,'CHATBOT_VERIFICATION_FAILED','conversation',conv.id::text);
 return jsonb_build_object('state','VERIFICATION_FAILED','conversation_id',conv.id);end if;
 if p_action='request_link' then
 if not public.marketing_service_limit(p_gym_id,'link/'||p_sender,3,86400) then return '{"state":"LOCKED"}';end if;
 if length(trim(coalesce(p_data->>'name',''))) not between 2 and 120 then return '{"state":"NEED_LINK_DETAILS"}';end if;
 begin v_date:=(p_data->>'birth_date')::date;exception when others then v_date:=null;end;
 insert into public.chatbot_link_requests(gym_id,conversation_id,supplied_name,birth_date) values(p_gym_id,conv.id,trim(p_data->>'name'),v_date) on conflict(conversation_id) where status='PENDING' do nothing;
 update public.whatsapp_conversations set verification_state='LINK_REQUEST',verified_until=null where id=conv.id;return '{"state":"LINK_PENDING"}';end if;
 if exists(select 1 from public.chatbot_link_requests where gym_id=p_gym_id and conversation_id=conv.id and status='PENDING') then return jsonb_build_object('state','LINK_PENDING','conversation_id',conv.id);end if;
 select count(*) into num from public.clients where gym_id=p_gym_id and private.marketing_phone(phone)=p_sender;
 update public.whatsapp_conversations set verification_state=case when num=1 then 'DOB' else 'LINK_REQUEST' end,verified_until=null where id=conv.id;
 return jsonb_build_object('state',case when num=1 then 'NEED_DOB' else 'NEED_LINK_DETAILS' end,'conversation_id',conv.id,'last_inbound_at',coalesce(conv.last_inbound_at,now()));end$$;
-- Bind staff-approved sessions to the client's current registered phone too.
create or replace function private.marketing_link_verified_phone() returns trigger language plpgsql set search_path='' as $$
begin if new.verification_state='VERIFIED' and (old.verification_state is distinct from new.verification_state or old.verified_until is distinct from new.verified_until) then
 select private.marketing_phone(phone) into new.verified_registered_phone from public.clients where gym_id=new.gym_id and id=new.client_id;end if;return new;end$$;
drop trigger if exists marketing_link_verified_phone on public.whatsapp_conversations;
create trigger marketing_link_verified_phone before update on public.whatsapp_conversations for each row execute function private.marketing_link_verified_phone();
-- One-time operator setup; app credentials never belong to a desktop profile.
create or replace function public.marketing_service_configure_meta(p_data jsonb) returns jsonb
language plpgsql security definer set search_path='' as $$
declare sid uuid;origin text:=p_data->>'onboarding_origin';page text:=p_data->>'onboarding_url';begin
 if jsonb_typeof(p_data) is distinct from 'object' then raise exception 'Configuración de Meta no válida.';end if;
 if coalesce(p_data->>'app_id','') !~ '^[0-9]{5,30}$'
 or coalesce(p_data->>'config_id','') !~ '^[0-9]{5,30}$'
 or length(coalesce(p_data->>'app_secret','')) not between 20 and 512
 or length(coalesce(p_data->>'verify_token','')) not between 32 and 512
 or coalesce(origin,'') !~ '^https://[a-z0-9.-]+(:[0-9]+)?$'
 or coalesce(page,'') !~ '^https://[a-z0-9.-]+(:[0-9]+)?/[^?#]*$'
 or left(page,length(origin)+1)<>origin||'/'
 or exists(select 1 from jsonb_object_keys(p_data) k where k not in ('app_id','config_id','app_secret','verify_token','onboarding_origin','onboarding_url')) then
 raise exception 'Revisa la configuración oficial de Meta y la página HTTPS de autorización.';end if;
 perform pg_advisory_xact_lock(hashtextextended('gymsoft/meta-platform',0));
 select meta_config_secret_id into sid from private.marketing_platform where singleton for update;
 if sid is null then execute 'select vault.create_secret($1,$2,$3)' into sid using p_data::text,'gymsoft_meta_platform','Configuración privada de Meta';
 else execute 'select vault.update_secret($1,$2)' using sid,p_data::text;end if;
 update private.marketing_platform set meta_config_secret_id=sid where singleton;
 return jsonb_build_object('configured',true,'onboarding_url',page);
end$$;
create or replace function public.marketing_service_platform() returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;begin execute 'select v.decrypted_secret::jsonb from vault.decrypted_secrets v join private.marketing_platform p on p.meta_config_secret_id=v.id where p.singleton' into v;return v;end$$;
create or replace function public.marketing_service_oauth(p_hash text,p_gym_id uuid default null,p_user_id uuid default null,p_consume boolean default false) returns jsonb language plpgsql security definer set search_path='' as $$
declare r private.marketing_oauth_states;begin
 if p_hash !~ '^[a-f0-9]{64}$' then raise exception 'Estado no válido.';end if;
 if p_gym_id is not null then insert into private.marketing_oauth_states(state_hash,gym_id,user_id,expires_at) values(p_hash,p_gym_id,p_user_id,now()+interval '10 minutes') returning * into r;
 elsif p_consume then update private.marketing_oauth_states set used_at=now() where state_hash=p_hash and expires_at>now() and used_at is null returning * into r;
 else select * into r from private.marketing_oauth_states where state_hash=p_hash and expires_at>now() and used_at is null;end if;
 if r.state_hash is null then raise exception 'La autorización venció o ya fue utilizada. Vuelve a conectar WhatsApp.';end if;return jsonb_build_object('gym_id',r.gym_id,'user_id',r.user_id);end$$;
create or replace function public.marketing_service_receipt(p_provider text,p_key text,p_gym_id uuid,p_payload jsonb,p_done boolean default false) returns boolean language plpgsql security definer set search_path='' as $$
declare r private.marketing_webhook_events;begin
 if p_done then update private.marketing_webhook_events set processed_at=now() where provider=p_provider and event_key=p_key and gym_id=p_gym_id;return found;end if;
 insert into private.marketing_webhook_events(provider,event_key,gym_id,payload) values(p_provider,p_key,p_gym_id,p_payload) on conflict do nothing;
 select * into r from private.marketing_webhook_events where provider=p_provider and event_key=p_key for update;
 if r.gym_id<>p_gym_id then raise exception 'Evento asociado a otro gimnasio.';end if;return r.processed_at is null;end$$;
create or replace function public.marketing_service_event_batch(p_gym_id uuid,p_limit integer default 100) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;begin
 if not private.marketing_operable(p_gym_id) then return '[]';end if;
 select coalesce(jsonb_agg(x),'[]') into v from (select * from private.marketing_events where gym_id=p_gym_id and processed_at is null order by id limit least(greatest(p_limit,1),200)) x;return v;end$$;
create or replace function public.marketing_service_event_done(p_gym_id uuid,p_ids bigint[]) returns void language sql security definer set search_path='' as $$
 update private.marketing_events set processed_at=now() where gym_id=p_gym_id and id=any(p_ids)
$$;
create or replace function public.marketing_service_status(p_gym_id uuid,p_message_id text,p_status text,p_at timestamptz) returns boolean language plpgsql security definer set search_path='' as $$
declare v_found boolean;begin
 if p_status not in ('SENT','DELIVERED','READ','FAILED') or length(coalesce(p_message_id,'')) not between 1 and 512 or p_at is null or p_at>now()+interval '5 minutes' then return false;end if;
 perform pg_advisory_xact_lock(hashtextextended(p_gym_id::text||'/delivery/'||p_message_id,0));
 insert into private.marketing_webhook_events(provider,event_key,gym_id,payload)
 values('META_STATUS',p_gym_id::text||'/'||p_message_id||'/'||p_status,p_gym_id,jsonb_build_object('message_id',p_message_id,'status',p_status,'at',p_at)) on conflict do nothing;
 update public.marketing_messages set status=case when status='READ' then 'READ' when status='DELIVERED' and p_status in ('SENT','FAILED') then 'DELIVERED' else p_status end,
 sent_at=case when p_status='SENT' then coalesce(sent_at,p_at) else sent_at end,
 delivered_at=case when p_status in ('DELIVERED','READ') then coalesce(delivered_at,p_at) else delivered_at end,read_at=case when p_status='READ' then coalesce(read_at,p_at) else read_at end,updated_at=now() where gym_id=p_gym_id and whatsapp_message_id=p_message_id and direction='OUT';
 v_found:=found;
 if v_found then update private.marketing_webhook_events set processed_at=now() where provider='META_STATUS' and event_key=p_gym_id::text||'/'||p_message_id||'/'||p_status and gym_id=p_gym_id;end if;
 return v_found;end$$;
-- Backend table access is intentionally limited to the integration model.
do $$declare t text;begin foreach t in array array['marketing_settings','marketing_connections','whatsapp_templates','marketing_automations','payment_requests','payment_transactions','whatsapp_conversations','chatbot_link_requests','automation_runs','marketing_messages','marketing_audit'] loop execute format('grant select,insert,update on public.%I to service_role',t);end loop;end$$;

create table if not exists private.marketing_scheduler(
 gym_id uuid primary key references public.gyms(id) on delete cascade,cursor_client bigint not null default 0,
 lease_id uuid,lease_until timestamptz,last_started_at timestamptz,last_finished_at timestamptz,last_error text not null default '');
alter table private.marketing_scheduler enable row level security;
revoke all on private.marketing_scheduler from public,anon,authenticated;
create or replace function public.marketing_service_jobs(p_limit integer default 10) returns jsonb language plpgsql security definer set search_path='' as $$
declare v jsonb;begin
 insert into private.marketing_scheduler(gym_id) select gym_id from public.marketing_settings where marketing_automation_enabled and whatsapp_enabled on conflict do nothing;
 with candidates as(select j.gym_id from private.marketing_scheduler j join public.marketing_settings s using(gym_id) where s.whatsapp_enabled and s.marketing_automation_enabled and private.marketing_operable(j.gym_id) and (j.lease_until is null or j.lease_until<now()) order by j.last_started_at nulls first for update of j skip locked limit least(greatest(p_limit,1),20)),claimed as(update private.marketing_scheduler j set lease_id=gen_random_uuid(),lease_until=now()+interval '2 minutes',last_started_at=now() from candidates c where j.gym_id=c.gym_id returning j.*) select coalesce(jsonb_agg(claimed),'[]') into v from claimed;return v;end$$;
create or replace function public.marketing_service_job_done(p_gym_id uuid,p_lease uuid,p_cursor bigint,p_error text default '') returns void language plpgsql security definer set search_path='' as $$
begin
 update private.marketing_scheduler set cursor_client=p_cursor,lease_until=null,last_finished_at=now(),last_error=left(p_error,200) where gym_id=p_gym_id and lease_id=p_lease;
 update public.marketing_settings set last_worker_at=now(),last_error=left(p_error,200) where gym_id=p_gym_id;end$$;
create or replace function public.marketing_service_scheduler_authorized(p_token text) returns boolean language plpgsql security definer set search_path='' as $$
declare v text;begin execute 'select v.decrypted_secret from vault.decrypted_secrets v join private.marketing_platform p on p.scheduler_secret_id=v.id where p.singleton' into v;
 return v is not null and length(p_token)>=32 and v=p_token;end$$;
create or replace function public.marketing_service_send_guard(p_id bigint,p_claim uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare m public.marketing_messages;c public.clients;conv public.whatsapp_conversations;begin
 select * into m from public.marketing_messages where id=p_id and claim_id=p_claim and status='PROCESSING';
 if not found then return '{"allowed":false,"reason":"STALE_CLAIM"}';end if;
 if not private.marketing_operable(m.gym_id) or not exists(select 1 from public.marketing_settings where gym_id=m.gym_id and whatsapp_enabled) then return '{"allowed":false,"reason":"DISABLED"}';end if;
 select * into c from public.clients where id=m.client_id and gym_id=m.gym_id;
 select * into conv from public.whatsapp_conversations where gym_id=m.gym_id and sender_number=m.phone;
 if conv.mode<>'BOT' and m.automation_type<>'HANDOFF_ACK' then return '{"allowed":false,"reason":"HUMAN_HANDOFF"}';end if;
 if m.automation_id is not null then
 if not coalesce(c.whatsapp_opt_in,false) then return '{"allowed":false,"reason":"NO_CONSENT"}';end if;
 if private.marketing_phone(c.phone) is distinct from m.phone then return '{"allowed":false,"reason":"PHONE_CHANGED"}';end if;
 if not exists(select 1 from public.marketing_automations a join public.whatsapp_templates t on t.id=a.template_id and t.gym_id=a.gym_id where a.id=m.automation_id and a.gym_id=m.gym_id and a.enabled and a.deleted_at is null and t.status='APPROVED' and t.name=m.template_name and t.language=m.language_code and t.body=a.body) then return '{"allowed":false,"reason":"AUTOMATION_CHANGED"}';end if;
 elsif m.automation_type='TEST' then
 if not coalesce(c.whatsapp_opt_in,false) then return '{"allowed":false,"reason":"NO_CONSENT"}';end if;
 if private.marketing_phone(c.phone) is distinct from m.phone then return '{"allowed":false,"reason":"PHONE_CHANGED"}';end if;
 if not exists(select 1 from public.whatsapp_templates where gym_id=m.gym_id and name=m.template_name and language=m.language_code and status='APPROVED') then return '{"allowed":false,"reason":"TEMPLATE_NOT_APPROVED"}';end if;
 elsif m.automation_type in ('CHATBOT','HANDOFF_ACK') and (conv.last_inbound_at is null or conv.last_inbound_at<now()-interval '24 hours') then return '{"allowed":false,"reason":"WINDOW_CLOSED"}';end if;
 return jsonb_build_object('allowed',true,'last_inbound_at',conv.last_inbound_at);end$$;
create or replace function public.marketing_service_queue_reply(p_gym_id uuid,p_sender text,p_key text,p_content jsonb) returns bigint language plpgsql security definer set search_path='' as $$
declare conv public.whatsapp_conversations;mid bigint;begin
 select * into conv from public.whatsapp_conversations where gym_id=p_gym_id and sender_number=p_sender;
 if not found or conv.last_inbound_at<now()-interval '24 hours' then return null;end if;
 insert into public.marketing_messages(gym_id,client_id,conversation_id,automation_type,source_date,phone,template_name,status,dedupe_key,body,message_payload)
 values(p_gym_id,conv.client_id,conv.id,case when coalesce((p_content->>'_handoff_ack')::boolean,false) then 'HANDOFF_ACK' else 'CHATBOT' end,private.gym_local_date(p_gym_id),p_sender,'','QUEUED',p_key,coalesce(p_content->'text'->>'body',p_content->'interactive'->'body'->>'text',''),p_content-'_handoff_ack')
 on conflict(gym_id,dedupe_key) where dedupe_key is not null do nothing returning id into mid;return mid;end$$;
create or replace function public.marketing_service_inbound_record(p_gym_id uuid,p_sender text,p_message_id text,p_body text,p_human boolean default false) returns boolean language plpgsql security definer set search_path='' as $$
declare n bigint;begin
 insert into public.marketing_messages(gym_id,automation_type,source_date,phone,template_name,status,direction,dedupe_key,whatsapp_message_id,body)
 values(p_gym_id,'CHATBOT',private.gym_local_date(p_gym_id),p_sender,'','RECEIVED',case when p_human then 'HUMAN' else 'IN' end,'inbound/'||p_message_id,p_message_id,left(p_body,4096)) on conflict do nothing returning id into n;return n is not null;end$$;
create or replace function public.marketing_service_payment_link(p_gym_id uuid,p_id uuid,p_url text) returns void language plpgsql security definer set search_path='' as $$
begin
 if p_url !~ '^https://checkout.wompi.co/p/\?' then raise exception 'Enlace no válido.';end if;
 update public.payment_requests set checkout_url=p_url where id=p_id and gym_id=p_gym_id and status='PENDING';end$$;
-- Payment links expose only a random reference; opening them never records a payment.
create or replace function public.marketing_service_open_payment(p_reference text) returns jsonb language plpgsql security definer set search_path='' as $$
declare r public.payment_requests;begin
 select * into r from public.payment_requests where reference=p_reference for update;
 if not found then return '{"state":"NOT_FOUND"}';end if;
 if r.status='APPROVED' then return '{"state":"PAID"}';end if;
 if r.expires_at<now() then update public.payment_requests set status='EXPIRED' where id=r.id and status='PENDING';return '{"state":"EXPIRED"}';end if;
 if r.status<>'PENDING' then return '{"state":"UNAVAILABLE"}';end if;
 update public.payment_requests set opened_at=coalesce(opened_at,now()) where id=r.id;return jsonb_build_object('state','READY','checkout_url',r.checkout_url,'gym_id',r.gym_id,'id',r.id);end$$;
grant usage,select on sequence public.marketing_messages_id_seq,public.marketing_audit_id_seq to service_role;

create or replace function public.marketing_lookup_clients(p_gym_id uuid,p_search text default '',p_limit integer default 30) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare r jsonb;begin perform public.marketing_access(p_gym_id,true);
 select coalesce(jsonb_agg(x),'[]') into r from (select id,first_name,last_name,document,phone,whatsapp_opt_in from public.clients where gym_id=p_gym_id and (btrim(p_search)='' or concat_ws(' ',first_name,last_name,document,phone) ilike '%'||replace(replace(replace(left(p_search,120),E'\\',E'\\\\'),'%',E'\\%'),'_',E'\\_')||'%') order by first_name,last_name,id limit least(greatest(p_limit,1),100)) x;return r;end$$;
create or replace function public.marketing_history(p_gym_id uuid,p_kind text,p_offset integer default 0,p_limit integer default 100) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare r jsonb;begin perform public.marketing_access(p_gym_id);if p_offset<0 or p_offset>1000000 or p_limit not between 1 and 200 then raise exception 'Página no válida.';end if;
 if p_kind='messages' then
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc,x.id desc),'[]') into r from (select m.*,p.status payment_status,p.reference payment_reference from public.marketing_messages m left join public.payment_requests p on p.id=m.payment_request_id and p.gym_id=m.gym_id where m.gym_id=p_gym_id order by m.created_at desc,m.id desc offset p_offset limit p_limit) x;
 elsif p_kind='payments' then
 select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc,x.id desc),'[]') into r from (select p.*,coalesce(nullif(btrim(concat_ws(' ',c.first_name,c.last_name)),''),'Cliente eliminado') client_name,(select t.provider_transaction_id from public.payment_transactions t where t.payment_request_id=p.id and t.gym_id=p_gym_id order by t.processed_at desc limit 1) transaction_id,(select t.provider_created_at from public.payment_transactions t where t.payment_request_id=p.id and t.gym_id=p_gym_id order by t.processed_at desc limit 1) provider_created_at from public.payment_requests p left join public.clients c on c.id=p.client_id and c.gym_id=p.gym_id where p.gym_id=p_gym_id order by p.created_at desc,p.id desc offset p_offset limit p_limit) x;
 else raise exception 'Historial no válido.';end if;return r;end$$;
create or replace function public.marketing_workspace(p_gym_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin perform public.marketing_access(p_gym_id);
 return jsonb_build_object('summary',public.marketing_summary(p_gym_id),
 'automations',coalesce((select jsonb_agg(a order by a.created_at desc) from public.marketing_automations a where a.gym_id=p_gym_id and a.deleted_at is null),'[]'),
 'templates',coalesce((select jsonb_agg(t order by t.name) from public.whatsapp_templates t where t.gym_id=p_gym_id),'[]'),
 'plans',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'price',p.price,'entry_limit',p.entry_limit,'active',p.active) order by p.name) from public.plans p where p.gym_id=p_gym_id),'[]'),
 'conversations',coalesce((select jsonb_agg(x) from (select c.id,c.sender_number,c.mode,c.verification_state,c.last_inbound_at,c.last_human_at,c.pause_until from public.whatsapp_conversations c where c.gym_id=p_gym_id order by c.updated_at desc limit 100) x),'[]'),
 'links',coalesce((select jsonb_agg(x) from (select l.*,c.sender_number from public.chatbot_link_requests l join public.whatsapp_conversations c on c.id=l.conversation_id and c.gym_id=l.gym_id where l.gym_id=p_gym_id and l.status='PENDING' order by l.created_at limit 100) x),'[]'),
 'messages',public.marketing_history(p_gym_id,'messages'), 'payments',public.marketing_history(p_gym_id,'payments'),
 'health',jsonb_build_object('last_worker_at',(select last_finished_at from private.marketing_scheduler where gym_id=p_gym_id),'worker_error',(select last_error from private.marketing_scheduler where gym_id=p_gym_id),'recent_errors',(select count(*) from public.marketing_messages where gym_id=p_gym_id and status in ('FAILED','UNCERTAIN') and created_at>now()-interval '7 days')));
end$$;
create or replace function public.marketing_activate_setup(p_gym_id uuid,p_rule_ids uuid[],p_chatbot boolean default true) returns jsonb language plpgsql security definer set search_path='' as $$
declare a public.marketing_automations;n integer:=0;begin perform public.marketing_access(p_gym_id);
 if cardinality(p_rule_ids)>30 then raise exception 'Selecciona hasta 30 automatizaciones.';end if;
 for a in select * from public.marketing_automations where gym_id=p_gym_id and deleted_at is null and id=any(p_rule_ids) order by id for update loop
 perform private.marketing_rule_ready(p_gym_id,a.template_id,a.include_payment_link,a.body);n:=n+1;end loop;
 if n<>cardinality(p_rule_ids) then raise exception 'Actualiza la selección de automatizaciones.';end if;
 perform public.marketing_features(p_gym_id,jsonb_build_object('whatsapp_enabled',true,'chatbot_enabled',p_chatbot,'marketing_automation_enabled',n>0));
 update public.marketing_automations set enabled=true,revision=revision+1,updated_at=now() where gym_id=p_gym_id and id=any(p_rule_ids);
 perform private.marketing_audit(p_gym_id,'SETUP_ACTIVATED','settings',p_gym_id::text,jsonb_build_object('rules',p_rule_ids,'chatbot',p_chatbot));return jsonb_build_object('active',n,'chatbot',p_chatbot);
end$$;
create or replace function public.marketing_service_gym(p_gym_id uuid) returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('id',id,'name',name,'timezone',timezone) from public.gyms where id=p_gym_id$$;
-- Owner access uses the existing private owner authorization, never a client claim.
do $outer$begin if to_regprocedure('private.require_owner()') is not null then
 execute $fn$create or replace function public.owner_marketing_status(p_gym_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $body$
 begin perform private.require_owner();return jsonb_build_object('connections',coalesce((select jsonb_agg(jsonb_build_object('provider',provider,'status',status,'mode',mode,'last_checked_at',last_checked_at)) from public.marketing_connections where gym_id=p_gym_id),'[]'),'chatbot_enabled',coalesce((select chatbot_enabled from public.marketing_settings where gym_id=p_gym_id),false),'automations_active',(select count(*) from public.marketing_automations where gym_id=p_gym_id and enabled and deleted_at is null),'last_execution',(select last_finished_at from private.marketing_scheduler where gym_id=p_gym_id),'errors',(select count(*) from public.marketing_messages where gym_id=p_gym_id and status in ('FAILED','UNCERTAIN') and created_at>now()-interval '7 days'));end $body$ $fn$;
 execute 'revoke all on function public.owner_marketing_status(uuid) from public,anon,authenticated';execute 'grant execute on function public.owner_marketing_status(uuid) to authenticated';
 end if;end$outer$;
create or replace function public.marketing_service_test_message(p_gym_id uuid,p_client_id bigint,p_template_id uuid,p_key text,p_body text,p_parameters jsonb) returns bigint language plpgsql security definer set search_path='' as $$
declare c public.clients;t public.whatsapp_templates;mid bigint;begin
 if not private.marketing_operable(p_gym_id) then raise exception 'Gimnasio no disponible.';end if;
 if length(p_key) not between 8 and 160 then raise exception 'Identificador de prueba no válido.';end if;
 select id into mid from public.marketing_messages where gym_id=p_gym_id and dedupe_key='test/'||p_key;
 if found then return mid;end if;
 select * into c from public.clients where gym_id=p_gym_id and id=p_client_id;
 if c.id is null or not c.whatsapp_opt_in or private.marketing_phone(c.phone) is null then raise exception 'El cliente debe autorizar WhatsApp y tener un teléfono válido.';end if;
 select * into t from public.whatsapp_templates where gym_id=p_gym_id and id=p_template_id and status='APPROVED';
 if not found or t.body like '%{{link_pago}}%' then raise exception 'Selecciona una plantilla aprobada sin enlace de pago.';end if;
 if not public.marketing_service_limit(p_gym_id,'test-message/'||p_client_id,3,3600) then raise exception 'Ya se enviaron tres pruebas a este cliente durante esta hora.';end if;
 insert into public.marketing_messages(gym_id,client_id,automation_type,source_date,client_name,phone,template_name,language_code,template_parameters,status,dedupe_key,body)
 values(p_gym_id,c.id,'TEST',private.gym_local_date(p_gym_id),btrim(concat_ws(' ',c.first_name,c.last_name)),private.marketing_phone(c.phone),t.name,t.language,p_parameters,'QUEUED','test/'||p_key,p_body) on conflict(gym_id,dedupe_key) where dedupe_key is not null do nothing returning id into mid;
 if mid is null then select id into mid from public.marketing_messages where gym_id=p_gym_id and dedupe_key='test/'||p_key;end if;
 perform private.marketing_audit(p_gym_id,'TEST_MESSAGE_QUEUED','message',mid::text,jsonb_build_object('client_id',c.id));return mid;end$$;
create or replace function public.marketing_reception_workspace(p_gym_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin perform public.marketing_access(p_gym_id,true);
 return jsonb_build_object('connected',exists(select 1 from public.marketing_connections where gym_id=p_gym_id and provider='META' and status='CONNECTED'),
 'conversations',coalesce((select jsonb_agg(x) from (select id,sender_number,mode,last_inbound_at,last_human_at,pause_until from public.whatsapp_conversations where gym_id=p_gym_id order by updated_at desc limit 100) x),'[]'),
 'links',coalesce((select jsonb_agg(x) from (select l.id,l.supplied_name,l.created_at,c.sender_number from public.chatbot_link_requests l join public.whatsapp_conversations c on c.id=l.conversation_id and c.gym_id=l.gym_id where l.gym_id=p_gym_id and l.status='PENDING' order by l.created_at limit 100) x),'[]'));
end$$;

do $$declare r record;begin
 for r in select p.oid::regprocedure f,n.nspname,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('private','public') and p.proname like 'marketing_%' loop
 execute format('revoke all on function %s from public,anon,authenticated,service_role',r.f);
 if r.nspname='public' then execute format('grant execute on function %s to %I',r.f,case when r.proname like 'marketing_service_%' then 'service_role' else 'authenticated' end);end if;
 end loop;
end$$;
grant execute on function private.marketing_phone(text) to authenticated,service_role;
commit;
