import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {database,root} from './migrations.mjs';
const venv=path.join(root,process.platform==='win32'?'.venv/Scripts/python.exe':'.venv/bin/python');
const python=process.env.PYTHON||(fs.existsSync(venv)?venv:(process.platform==='win32'?'python':'python3'));
const payload=JSON.parse(execFileSync(python,[path.join(root,'tests/owner_payloads.py')],{encoding:'utf8'}));
const db=await database();
let checks=0;
const O='10000000-0000-4000-8000-000000000001',A='20000000-0000-4000-8000-000000000001',R='30000000-0000-4000-8000-000000000001';
const sid='90000000-0000-4000-8000-000000000001';
async function user(id){
 await db.exec('RESET ROLE');
 await db.query("SELECT set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[id,JSON.stringify({sub:id,session_id:id===A?sid:'90000000-0000-4000-8000-000000000002'})]);
 await db.exec('SET ROLE authenticated');
}
async function rpc(name,params={}){
 assert.match(name,/^[a-z_]+$/);
 for(const key of Object.keys(params))assert.match(key,/^p_[a-z_]+$/);
 const args=Object.keys(params).map((key,i)=>`${key} => $${i+1}`).join(',');
 return (await db.query(`SELECT public.${name}(${args}) as data`,Object.values(params))).rows[0].data;
}
function ok(value,label){assert.ok(value,label);checks++;}
async function denied(fn,regex){await assert.rejects(fn,regex);checks++;}
try{
 for(const [id,email] of [[O,'owner@example.test'],[A,'admin@example.test'],[R,'reception@example.test']])await db.query('INSERT INTO auth.users(id,email) VALUES($1,$2)',[id,email]);
 await db.query('INSERT INTO private.software_owners(user_id) VALUES($1)',[O]);
 await user(O);
 const gym=await rpc('owner_create_gym',payload.create);
 const other=await rpc('owner_create_gym',{...payload.create,p_name:'Otro gimnasio',p_email:'other@example.test'});
 const id=gym.gym_id;
 const detail=()=>rpc('owner_gym_detail',{p_gym_id:id});
 const state=async()=> (await rpc('owner_list_gyms')).find(g=>g.id===id);
 ok(id!==other.gym_id,'gym ids unique');
 const renewal={...payload.renew,p_gym_id:id};
 const paid=await rpc('owner_renew',renewal);
 ok(paid.reference==='UI-RECIBO-001'&&Number(paid.amount)===400000&&paid.months===2,'Python renewal payload accepted by server');
 const repeated=await rpc('owner_renew',renewal);
 ok(repeated.id===paid.id&&repeated.period_until===paid.period_until,'retry same payment does not extend twice');
 ok((await detail()).payments.length===1,'one payment only');
 await denied(()=>rpc('owner_renew',{...renewal,p_amount:'1.00'}),/otros datos/);
 await denied(()=>rpc('owner_renew',{...renewal,p_reference:''}),/Completa/);
 await rpc('owner_update_contract',{...payload.contract,p_gym_id:id});
 let row=await state();
 ok(Number(row.monthly_price)===150000&&row.max_devices===3&&row.max_users===4,'contract fields updated');
 await rpc('owner_set_status',{p_gym_id:id,p_status:'suspended',p_reason:'Prueba de suspensión'});
 ok((await state()).effective_status==='suspended','suspend');
 await rpc('owner_set_status',{p_gym_id:id,p_status:'active',p_reason:'Pago confirmado'});
 ok((await state()).effective_status==='active','reactivate');
 await rpc('owner_set_status',{p_gym_id:id,p_status:'cancelled',p_reason:'Baja solicitada'});
 await rpc('owner_grant_grace',{...payload.grace,p_gym_id:id});
 ok((await state()).effective_status==='cancelled','grace cannot bypass cancelled subscription');
 await rpc('owner_set_status',{p_gym_id:id,p_status:'active',p_reason:'Reactivación solicitada'});
 await db.exec('RESET ROLE');
 await db.query("UPDATE private.subscriptions SET expires_at=now()-interval '1 day',grace_until=null WHERE gym_id=$1",[id]);
 await user(O);ok((await state()).effective_status==='expired','expiration is effective');
 await rpc('owner_grant_grace',{...payload.grace,p_gym_id:id});
 ok((await state()).effective_status==='grace','valid grace works');
 const code=await rpc('owner_invite_user',{...payload.invite,p_gym_id:id});
 ok(typeof code==='string'&&code.length>20,'reception invitation');
 await user(A);await rpc('commercial_accept_invite',{p_code:gym.activation_code});
 const hash='d'.repeat(64);
 let access=await rpc('commercial_check_license',{p_device_hash:hash,p_device_name:'PC Admin test'});
 ok(access.state==='device_pending','new pc stays pending');
 await user(O);let d=await detail();let device=d.devices[0];
 await rpc('owner_set_device',{p_device_id:device.id,p_blocked:false,p_reason:'Equipo verificado'});
 ok((await detail()).devices[0].approved,'authorize pc');
 await user(A);ok((await rpc('commercial_check_license',{p_device_hash:hash,p_device_name:'PC Admin test'})).allowed,'authorized pc allowed');
 await user(R);await rpc('commercial_accept_invite',{p_code:code});
 await rpc('commercial_check_license',{p_device_hash:hash,p_device_name:'PC compartido'});
 const exp=await rpc('reception_create_expense',{p_gym_id:id,p_expense_date:'2026-09-07',p_category:'Limpieza',p_description:'Gasto desde Recepción',p_vendor:'',p_amount:5000,p_payment_method:'Efectivo',p_payment_reference:'REC-1',p_receipt_reference:'',p_notes:''});
 ok(exp!==null,'reception creates expense through safe RPC');
 await user(O);d=await detail();
 ok(d.users.some(u=>u.user_id===R&&u.role==='receptionist'),'reception role assigned');
 await rpc('owner_set_user',{p_user_id:R,p_enabled:false,p_reason:'Usuario dado de baja'});
 ok((await detail()).users.find(u=>u.user_id===R).enabled===false,'disable user');
 await user(R);await denied(()=>rpc('reception_list_clients',{p_gym_id:id,p_search:''}),/autoriz|permiso/i);
 await user(O);await rpc('owner_set_user',{p_user_id:R,p_enabled:true,p_reason:'Usuario reactivado'});
 ok((await detail()).users.find(u=>u.user_id===R).enabled===true,'enable user');
 await rpc('owner_set_device',{p_device_id:device.id,p_blocked:true,p_reason:'Equipo perdido'});
 ok((await detail()).devices[0].blocked,'block device');
 await user(A);await denied(()=>rpc('reception_list_clients',{p_gym_id:id,p_search:''}),/autoriz|permiso/i);
 await user(O);await rpc('owner_set_device',{p_device_id:device.id,p_blocked:false,p_reason:'Equipo recuperado'});
 await user(A);
 const client=(await db.query("INSERT INTO public.clients(gym_id,document,first_name) VALUES($1,'UI-01','Prueba') RETURNING id",[id])).rows[0].id;
 const plan=(await db.query('SELECT id FROM public.plans WHERE gym_id=$1 LIMIT 1',[id])).rows[0].id;
 const m=(await db.query("SELECT * FROM public.add_membership_accumulating($1,$2,$3,null,50000,'Efectivo','','Prueba UI')",[id,client,plan])).rows[0].membership_id;
 let changed=await rpc('gymsoft_change_payment',{p_gym_id:id,p_membership_id:m,p_expected_revision:0,p_action:'correct',p_reason:'Corrección de valor',p_amount:45000,p_payment_method:'Transferencia',p_payment_reference:'CORREGIDO-1'});
 ok(Number(changed.amount)===45000&&Number(changed.payment_revision)===1,'edit payment without replacing its id');
 const list=await rpc('gymsoft_client_payments',{p_gym_id:id,p_client_id:client});
 ok(list.rows.some(x=>x.id===m&&Number(x.amount)===45000),'Clientes y pagos reads correction');
 let finance=await rpc('get_finance_dashboard',{p_gym_id:id,p_date_from:null,p_date_to:null});
 ok(Number(finance.total_income)===45000,'Finance shows corrected total');
 ok(finance.payments.some(p=>p.id===m&&p.client_id===client),'Finance can locate selected client payment');
 await denied(()=>rpc('gymsoft_change_payment',{p_gym_id:id,p_membership_id:m,p_expected_revision:0,p_action:'correct',p_reason:'Intento anterior',p_amount:999,p_payment_method:'Efectivo'}),/actualiz|cambi|recarg|versi/i);
 const history=await rpc('gymsoft_payment_history',{p_gym_id:id,p_membership_id:m});
 ok(history.length>0,'correction audited');
 changed=await rpc('gymsoft_change_payment',{p_gym_id:id,p_membership_id:m,p_expected_revision:1,p_action:'void',p_reason:'Registro duplicado'});
 ok(changed.payment_status==='void','void retains record');
 finance=await rpc('get_finance_dashboard',{p_gym_id:id,p_date_from:null,p_date_to:null});
 ok(Number(finance.total_income)===0,'void removed from income');
 await user(O);
 const backup=await rpc('owner_backup_gym',{p_gym_id:id});
 ok(backup.tables.accounting_expenses.some(e=>e.description==='Gasto desde Recepción'),'reception expense included in gym backup');
 ok(backup.tables.clients.every(c=>c.gym_id===id),'backup does not mix gyms');
 ok((await detail()).events.length>=12,'owner operations audited');
 ok((await rpc('owner_gym_detail',{p_gym_id:other.gym_id})).payments.length===0,'other gym has no owner payment');
 console.log(`PASS: ${checks} owner and payment flows using Python form payloads and local PostgreSQL.`);
}catch(error){console.error('FAILED after',checks,'checks:',error.message,error.detail||'');process.exitCode=1;}
finally{await db.close();}
