-- Instalación exclusiva en un proyecto NUEVO y vacío de Supabase.
-- La comprobación sucede antes de crear o modificar objetos.
do $$ begin
 if to_regclass('public.gyms') is not null or to_regclass('public.clients') is not null then
  raise exception 'Este proyecto ya contiene un sistema de gimnasios. Usa un proyecto nuevo y vacío.';
 end if;
end $$;
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create table public.gyms (
 id uuid primary key default gen_random_uuid(), name text not null check(length(trim(name)) between 1 and 120),
 join_code uuid not null unique default gen_random_uuid(), timezone text not null default 'America/Bogota',
 created_at timestamptz not null default now()
);
create table public.gym_users (
 gym_id uuid not null references public.gyms(id),
 user_id uuid primary key references auth.users(id),
 role text not null check(role in ('admin','receptionist')),
 enabled boolean not null default true, created_at timestamptz not null default now()
);
create index on public.gym_users(gym_id, user_id);

create table public.clients (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), document text not null,
 full_name text not null default '', first_name text not null, last_name text not null default '',
 phone text not null default '', email text not null default '',
 birth_date date, birthdate date, emergency_contact text not null default '',
 medical_notes text not null default '', biometric_identifier text not null default '',
 photo_path text not null default '', active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(gym_id,document)
);
create unique index clients_gym_biometric_unique on public.clients(gym_id,biometric_identifier)
 where biometric_identifier <> '';
create table public.plans (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), name text not null,
 duration_days integer not null check(duration_days>0), price bigint not null check(price>=0),
 entry_limit bigint check(entry_limit>0), active boolean not null default true,
 unique(gym_id,name)
);
create table public.memberships (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), client_id bigint not null references public.clients(id),
 plan_id bigint not null references public.plans(id), start_date date not null, end_date date not null,
 amount bigint not null check(amount>=0), amount_paid bigint not null default 0 check(amount_paid>=0),
 entry_limit bigint check(entry_limit>0), payment_method text not null,
 payment_reference text not null default '', paid_at timestamptz not null default now(),
 notes text not null default '', recorded_by uuid, check(end_date>=start_date)
);
create table public.checkins (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), client_id bigint not null references public.clients(id),
 membership_id bigint references public.memberships(id), checkin_at timestamptz not null default now(),
 method text not null, result text not null check(result in ('PERMITIDA','DENEGADA')),
 notes text not null default '', recorded_by uuid
);
create table public.trainers (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), name text not null, full_name text not null default '',
 phone text not null default '', email text not null default '', specialty text not null default '',
 active boolean not null default true
);
create table public.routines (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), client_id bigint not null references public.clients(id),
 trainer_id bigint references public.trainers(id), name text not null, goal text not null default '',
 start_date date not null, notes text not null default '', active boolean not null default true
);
create table public.exercises (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), routine_id bigint not null references public.routines(id) on delete cascade,
 day_name text not null, name text not null, sets text not null default '', reps text not null default '',
 weight text not null default '', notes text not null default '', position integer not null default 0
);
create table public.classes (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), trainer_id bigint references public.trainers(id),
 name text not null, starts_at timestamptz not null, capacity integer not null check(capacity>0),
 notes text not null default '', status text not null default 'PROGRAMADA'
);
create table public.reservations (
 id bigint generated by default as identity primary key,
 gym_id uuid not null references public.gyms(id), class_id bigint not null references public.classes(id) on delete cascade,
 client_id bigint not null references public.clients(id), status text not null default 'RESERVADA',
 created_at timestamptz not null default now(), unique(gym_id,class_id,client_id)
);
create index on public.memberships(gym_id,client_id,end_date desc);
create index on public.checkins(gym_id,client_id,checkin_at desc);
create index on public.classes(gym_id,starts_at);

-- Funciones de compatibilidad para los módulos operativos. La migración
-- comercial sustituye el permiso básico por rol + suscripción + sesión.
create function private.user_has_gym_role(p_gym_id uuid,p_roles text[])
returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.gym_users where gym_id=p_gym_id and user_id=auth.uid() and enabled and role=any(p_roles))
$$;
create function private.client_belongs_to_gym(p_client_id bigint,p_gym_id uuid)
returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.clients where id=p_client_id and gym_id=p_gym_id)
$$;
create function public.gymsoft_today() returns date language sql stable security definer set search_path='' as $$
 select (now() at time zone coalesce((select g.timezone from public.gyms g join public.gym_users u on u.gym_id=g.id where u.user_id=auth.uid()),'America/Bogota'))::date
$$;
create function public.gymsoft_now() returns timestamptz language sql stable set search_path='' as $$ select now() $$;
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
