begin;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create or replace function private.user_has_gym_role(
    p_gym_id uuid,
    p_roles text[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.gym_users gu
        where gu.user_id = (select auth.uid())
          and gu.gym_id = p_gym_id
          and gu.role = any(p_roles)
    );
$$;

revoke all on function private.user_has_gym_role(uuid, text[])
    from public, anon, authenticated;
grant execute on function private.user_has_gym_role(uuid, text[])
    to authenticated;

create or replace function private.client_belongs_to_gym(
    p_client_id bigint,
    p_gym_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.clients c
        where c.id = p_client_id
          and c.gym_id = p_gym_id
    );
$$;

revoke all on function private.client_belongs_to_gym(bigint, uuid)
    from public, anon, authenticated;
grant execute on function private.client_belongs_to_gym(bigint, uuid)
    to authenticated;

create or replace function private.plan_belongs_to_gym(
    p_plan_id bigint,
    p_gym_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.plans p
        where p.id = p_plan_id
          and p.gym_id = p_gym_id
          and p.active = true
    );
$$;

revoke all on function private.plan_belongs_to_gym(bigint, uuid)
    from public, anon, authenticated;
grant execute on function private.plan_belongs_to_gym(bigint, uuid)
    to authenticated;

alter table public.memberships
    add column if not exists recorded_by uuid;

alter table public.checkins
    add column if not exists recorded_by uuid;

alter table public.clients
    add column if not exists created_by uuid;

do $$
declare
    v_constraint record;
begin
    for v_constraint in
        select
            c.conname
        from pg_constraint c
        where c.conrelid = 'public.gym_users'::regclass
          and c.contype = 'c'
          and pg_get_constraintdef(c.oid) ilike '%role%'
    loop
        execute format(
            'alter table public.gym_users drop constraint %I',
            v_constraint.conname
        );
    end loop;

    alter table public.gym_users
        add constraint gym_users_role_check
        check (role in ('admin', 'receptionist'));
end;
$$;

create table if not exists public.staff_invites (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    code uuid not null unique default gen_random_uuid(),
    role text not null default 'receptionist'
        check (role = 'receptionist'),
    created_by uuid not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '7 days'),
    used_by uuid,
    used_at timestamptz
);

create index if not exists idx_staff_invites_gym
    on public.staff_invites(gym_id, created_at desc);

create index if not exists idx_staff_invites_code
    on public.staff_invites(code);

create table if not exists public.gym_events (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    event_type text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_gym_events_gym_date
    on public.gym_events(gym_id, created_at desc);

alter table public.gyms enable row level security;
alter table public.gym_users enable row level security;
alter table public.clients enable row level security;
alter table public.plans enable row level security;
alter table public.memberships enable row level security;
alter table public.checkins enable row level security;
alter table public.trainers enable row level security;
alter table public.routines enable row level security;
alter table public.exercises enable row level security;
alter table public.classes enable row level security;
alter table public.reservations enable row level security;
alter table public.staff_invites enable row level security;
alter table public.gym_events enable row level security;

drop policy if exists gym_read on public.gyms;
drop policy if exists gym_update on public.gyms;
drop policy if exists gym_access on public.gyms;
drop policy if exists gyms_staff_read on public.gyms;
drop policy if exists gyms_admin_read on public.gyms;
drop policy if exists gyms_admin_update on public.gyms;

create policy gyms_admin_read
on public.gyms
for select
to authenticated
using (
    private.user_has_gym_role(id, array['admin']::text[])
);

create policy gyms_admin_update
on public.gyms
for update
to authenticated
using (
    private.user_has_gym_role(id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(id, array['admin']::text[])
);

drop policy if exists gym_users_read on public.gym_users;
drop policy if exists gym_access on public.gym_users;
drop policy if exists gym_users_self_read on public.gym_users;
drop policy if exists gym_users_admin_all on public.gym_users;

create policy gym_users_self_read
on public.gym_users
for select
to authenticated
using (user_id = (select auth.uid()));

create policy gym_users_admin_all
on public.gym_users
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.clients;
drop policy if exists clients_admin_all on public.clients;

create policy clients_admin_all
on public.clients
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.plans;
drop policy if exists plans_staff_read on public.plans;
drop policy if exists plans_admin_all on public.plans;

create policy plans_staff_read
on public.plans
for select
to authenticated
using (
    private.user_has_gym_role(
        gym_id,
        array['admin', 'receptionist']::text[]
    )
);

create policy plans_admin_all
on public.plans
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.memberships;
drop policy if exists memberships_admin_all on public.memberships;

create policy memberships_admin_all
on public.memberships
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.checkins;
drop policy if exists checkins_admin_all on public.checkins;

create policy checkins_admin_all
on public.checkins
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.trainers;
drop policy if exists trainers_admin_all on public.trainers;

create policy trainers_admin_all
on public.trainers
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.routines;
drop policy if exists routines_admin_all on public.routines;

create policy routines_admin_all
on public.routines
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.exercises;
drop policy if exists exercises_admin_all on public.exercises;

create policy exercises_admin_all
on public.exercises
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.classes;
drop policy if exists classes_admin_all on public.classes;

create policy classes_admin_all
on public.classes
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_access on public.reservations;
drop policy if exists reservations_admin_all on public.reservations;

create policy reservations_admin_all
on public.reservations
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists staff_invites_admin_all on public.staff_invites;

create policy staff_invites_admin_all
on public.staff_invites
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists gym_events_staff_read on public.gym_events;

create policy gym_events_staff_read
on public.gym_events
for select
to authenticated
using (
    private.user_has_gym_role(
        gym_id,
        array['admin', 'receptionist']::text[]
    )
);

grant select, insert, update, delete
    on public.staff_invites to authenticated;
grant select on public.gym_events to authenticated;

create or replace function private.notify_gym_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_gym_id uuid;
begin
    if tg_op = 'DELETE' then
        v_gym_id := old.gym_id;
    else
        v_gym_id := new.gym_id;
    end if;

    insert into public.gym_events(gym_id, event_type)
    values (v_gym_id, tg_table_name || ':' || lower(tg_op));

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

revoke all on function private.notify_gym_change() from public;

drop trigger if exists gymsoft_clients_event on public.clients;
create trigger gymsoft_clients_event
after insert or update or delete on public.clients
for each row execute function private.notify_gym_change();

drop trigger if exists gymsoft_plans_event on public.plans;
create trigger gymsoft_plans_event
after insert or update or delete on public.plans
for each row execute function private.notify_gym_change();

drop trigger if exists gymsoft_memberships_event on public.memberships;
create trigger gymsoft_memberships_event
after insert or update or delete on public.memberships
for each row execute function private.notify_gym_change();

drop trigger if exists gymsoft_checkins_event on public.checkins;
create trigger gymsoft_checkins_event
after insert or update or delete on public.checkins
for each row execute function private.notify_gym_change();

do $$
begin
    if exists (
        select 1
        from pg_publication
        where pubname = 'supabase_realtime'
    ) and not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'gym_events'
    ) then
        execute 'alter publication supabase_realtime add table public.gym_events';
    end if;
end;
$$;

create or replace function private.membership_snapshot_json(
    p_gym_id uuid,
    p_client_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_client record;
    v_membership_id bigint;
    v_start_date date;
    v_end_date date;
    v_entry_limit bigint;
    v_entries_used bigint := 0;
    v_plan_name text := 'Sin plan';
    v_today date := public.gymsoft_today();
    v_allowed boolean := false;
    v_status text := 'VENCIDO';
begin
    select
        c.id,
        c.document,
        c.first_name,
        c.last_name,
        c.phone,
        c.email,
        coalesce(c.birthdate, c.birth_date) as birthdate,
        c.active
    into v_client
    from public.clients c
    where c.id = p_client_id
      and c.gym_id = p_gym_id;

    if not found then
        raise exception 'Cliente no encontrado.' using errcode = 'P0002';
    end if;

    select
        m.id,
        m.start_date,
        m.end_date,
        coalesce(m.entry_limit, p.entry_limit),
        coalesce(p.name, 'Sin plan')
    into
        v_membership_id,
        v_start_date,
        v_end_date,
        v_entry_limit,
        v_plan_name
    from public.memberships m
    left join public.plans p
      on p.id = m.plan_id
     and p.gym_id = m.gym_id
    where m.gym_id = p_gym_id
      and m.client_id = p_client_id
    order by
        case
            when v_today between m.start_date and m.end_date then 0
            else 1
        end,
        m.end_date desc,
        m.id desc
    limit 1;

    if v_membership_id is not null and v_entry_limit is not null then
        select count(*)
        into v_entries_used
        from public.checkins ch
        where ch.gym_id = p_gym_id
          and ch.membership_id = v_membership_id
          and ch.result = 'PERMITIDA';
    end if;

    if not coalesce(v_client.active, true) then
        v_status := 'INACTIVO';
    elsif v_membership_id is null then
        v_status := 'VENCIDO';
    elsif not (v_today between v_start_date and v_end_date) then
        v_status := 'VENCIDO';
    elsif v_entry_limit is not null
          and v_entries_used >= v_entry_limit then
        v_status := 'SIN ENTRADAS';
    else
        v_status := 'AL DÍA';
        v_allowed := true;
    end if;

    return jsonb_build_object(
        'id', v_client.id,
        'document', v_client.document,
        'first_name', v_client.first_name,
        'last_name', v_client.last_name,
        'client_name', trim(
            concat_ws(' ', v_client.first_name, v_client.last_name)
        ),
        'phone', coalesce(v_client.phone, ''),
        'email', coalesce(v_client.email, ''),
        'birthdate', coalesce(v_client.birthdate::text, ''),
        'active', coalesce(v_client.active, true),
        'status', v_status,
        'allowed', v_allowed,
        'membership_id', v_membership_id,
        'membership_start', coalesce(v_start_date::text, ''),
        'membership_end', coalesce(v_end_date::text, ''),
        'plan_name', v_plan_name,
        'entry_limit', v_entry_limit,
        'entries_used', v_entries_used,
        'entries_remaining', case
            when v_entry_limit is null then null
            else greatest(v_entry_limit - v_entries_used, 0)
        end
    );
end;
$$;

revoke all on function private.membership_snapshot_json(uuid, bigint)
    from public, anon, authenticated;
grant execute on function private.membership_snapshot_json(uuid, bigint)
    to authenticated;

create or replace function public.reception_list_clients(
    p_gym_id uuid,
    p_search text default ''
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para ver estos clientes.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            private.membership_snapshot_json(p_gym_id, c.id)
            order by c.first_name, c.last_name, c.id
        ),
        '[]'::jsonb
    )
    into v_result
    from public.clients c
    where c.gym_id = p_gym_id
      and (
          trim(coalesce(p_search, '')) = ''
          or c.document ilike '%' || trim(p_search) || '%'
          or concat_ws(' ', c.first_name, c.last_name)
              ilike '%' || trim(p_search) || '%'
          or coalesce(c.phone, '') ilike '%' || trim(p_search) || '%'
      );

    return v_result;
end;
$$;

revoke all on function public.reception_list_clients(uuid, text)
    from public, anon, authenticated;
grant execute on function public.reception_list_clients(uuid, text)
    to authenticated;

create or replace function public.reception_membership_snapshot(
    p_gym_id uuid,
    p_client_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para consultar este cliente.'
            using errcode = '42501';
    end if;

    return private.membership_snapshot_json(
        p_gym_id,
        p_client_id
    );
end;
$$;

revoke all on function public.reception_membership_snapshot(uuid, bigint)
    from public, anon, authenticated;
grant execute on function public.reception_membership_snapshot(uuid, bigint)
    to authenticated;

create or replace function public.reception_save_client(
    p_gym_id uuid,
    p_client_id bigint,
    p_document text,
    p_first_name text,
    p_last_name text,
    p_phone text default '',
    p_email text default '',
    p_birthdate date default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_client_id bigint;
    v_user_id uuid := (select auth.uid());
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para guardar clientes.'
            using errcode = '42501';
    end if;

    if trim(coalesce(p_document, '')) = ''
       or trim(coalesce(p_first_name, '')) = '' then
        raise exception 'El documento y el nombre son obligatorios.'
            using errcode = '22023';
    end if;

    if p_client_id is null then
        insert into public.clients(
            gym_id,
            document,
            full_name,
            first_name,
            last_name,
            phone,
            email,
            birth_date,
            birthdate,
            emergency_contact,
            medical_notes,
            photo_path,
            active,
            created_by
        )
        values (
            p_gym_id,
            trim(p_document),
            trim(concat_ws(' ', p_first_name, p_last_name)),
            trim(p_first_name),
            trim(coalesce(p_last_name, '')),
            trim(coalesce(p_phone, '')),
            trim(coalesce(p_email, '')),
            p_birthdate,
            p_birthdate,
            '',
            '',
            '',
            true,
            v_user_id
        )
        returning id into v_client_id;
    else
        if not private.client_belongs_to_gym(
            p_client_id,
            p_gym_id
        ) then
            raise exception 'Cliente no encontrado.' using errcode = 'P0002';
        end if;

        update public.clients
        set
            document = trim(p_document),
            full_name = trim(concat_ws(' ', p_first_name, p_last_name)),
            first_name = trim(p_first_name),
            last_name = trim(coalesce(p_last_name, '')),
            phone = trim(coalesce(p_phone, '')),
            email = trim(coalesce(p_email, '')),
            birth_date = p_birthdate,
            birthdate = p_birthdate
        where id = p_client_id
          and gym_id = p_gym_id
        returning id into v_client_id;
    end if;

    return v_client_id;
end;
$$;

revoke all on function public.reception_save_client(
    uuid, bigint, text, text, text, text, text, date
) from public, anon, authenticated;
grant execute on function public.reception_save_client(
    uuid, bigint, text, text, text, text, text, date
) to authenticated;

do $$
begin
    if to_regprocedure(
        'public.add_membership_accumulating_internal(uuid,bigint,bigint,date,bigint,text,text,text)'
    ) is null then
        alter function public.add_membership_accumulating(
            uuid,
            bigint,
            bigint,
            date,
            bigint,
            text,
            text,
            text
        ) rename to add_membership_accumulating_internal;
    end if;
end;
$$;

revoke all on function public.add_membership_accumulating_internal(
    uuid, bigint, bigint, date, bigint, text, text, text
) from public, anon, authenticated;

create or replace function public.add_membership_accumulating(
    p_gym_id uuid,
    p_client_id bigint,
    p_plan_id bigint,
    p_requested_start date,
    p_amount bigint,
    p_payment_method text,
    p_payment_reference text,
    p_notes text
)
returns table(
    membership_id bigint,
    start_date date,
    end_date date
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_membership_id bigint;
    v_start_date date;
    v_end_date date;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para registrar pagos.'
            using errcode = '42501';
    end if;

    if not private.client_belongs_to_gym(p_client_id, p_gym_id)
       or not private.plan_belongs_to_gym(p_plan_id, p_gym_id) then
        raise exception 'El cliente o el plan no pertenece al gimnasio.'
            using errcode = '23503';
    end if;

    if coalesce(p_amount, 0) < 0 then
        raise exception 'El valor pagado no puede ser negativo.'
            using errcode = '22023';
    end if;

    perform 1
    from public.add_membership_accumulating_internal(
        p_gym_id,
        p_client_id,
        p_plan_id,
        p_requested_start,
        p_amount,
        p_payment_method,
        p_payment_reference,
        p_notes
    );

    select
        m.id,
        m.start_date,
        m.end_date
    into
        v_membership_id,
        v_start_date,
        v_end_date
    from public.memberships m
    where m.gym_id = p_gym_id
      and m.client_id = p_client_id
    order by m.id desc
    limit 1;

    if v_membership_id is null then
        raise exception 'La función de pagos no creó la membresía.'
            using errcode = 'P0001';
    end if;

    update public.memberships
    set recorded_by = (select auth.uid())
    where id = v_membership_id
      and gym_id = p_gym_id;

    return query
    select v_membership_id, v_start_date, v_end_date;
end;
$$;

revoke all on function public.add_membership_accumulating(
    uuid, bigint, bigint, date, bigint, text, text, text
) from public, anon, authenticated;
grant execute on function public.add_membership_accumulating(
    uuid, bigint, bigint, date, bigint, text, text, text
) to authenticated;

create or replace function public.reception_register_checkin(
    p_gym_id uuid,
    p_client_id bigint,
    p_method text default 'RECEPCIÓN'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_snapshot jsonb;
    v_membership_id bigint;
    v_allowed boolean;
    v_result text;
    v_checkin_at timestamptz := public.gymsoft_now();
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para registrar entradas.'
            using errcode = '42501';
    end if;

    v_snapshot := private.membership_snapshot_json(
        p_gym_id,
        p_client_id
    );
    v_membership_id := nullif(
        v_snapshot ->> 'membership_id',
        ''
    )::bigint;

    if v_membership_id is not null then
        perform 1
        from public.memberships m
        where m.id = v_membership_id
          and m.gym_id = p_gym_id
        for update;

        v_snapshot := private.membership_snapshot_json(
            p_gym_id,
            p_client_id
        );
    end if;

    v_allowed := coalesce(
        (v_snapshot ->> 'allowed')::boolean,
        false
    );
    v_result := case
        when v_allowed then 'PERMITIDA'
        else 'DENEGADA'
    end;

    insert into public.checkins(
        gym_id,
        client_id,
        membership_id,
        checkin_at,
        method,
        result,
        notes,
        recorded_by
    )
    values (
        p_gym_id,
        p_client_id,
        v_membership_id,
        v_checkin_at,
        left(trim(coalesce(p_method, 'RECEPCIÓN')), 80),
        v_result,
        '',
        (select auth.uid())
    );

    if v_allowed
       and (v_snapshot ->> 'entry_limit') is not null then
        v_snapshot := jsonb_set(
            v_snapshot,
            '{entries_used}',
            to_jsonb((v_snapshot ->> 'entries_used')::bigint + 1)
        );
        v_snapshot := jsonb_set(
            v_snapshot,
            '{entries_remaining}',
            to_jsonb(
                greatest(
                    (v_snapshot ->> 'entries_remaining')::bigint - 1,
                    0
                )
            )
        );
    end if;

    return v_snapshot || jsonb_build_object(
        'result', v_result,
        'checkin_at', v_checkin_at,
        'override', false
    );
end;
$$;

revoke all on function public.reception_register_checkin(
    uuid, bigint, text
) from public, anon, authenticated;
grant execute on function public.reception_register_checkin(
    uuid, bigint, text
) to authenticated;

create or replace function public.reception_list_checkins(
    p_gym_id uuid,
    p_limit integer default 40
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para consultar entradas.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', recent.id,
                'client_id', recent.client_id,
                'document', recent.document,
                'client_name', recent.client_name,
                'checkin_at', recent.checkin_at,
                'method', recent.method,
                'result', recent.result
            )
            order by recent.checkin_at desc, recent.id desc
        ),
        '[]'::jsonb
    )
    into v_result
    from (
        select
            ch.id,
            ch.client_id,
            c.document,
            trim(concat_ws(' ', c.first_name, c.last_name))
                as client_name,
            ch.checkin_at,
            ch.method,
            ch.result
        from public.checkins ch
        join public.clients c
          on c.id = ch.client_id
         and c.gym_id = ch.gym_id
        where ch.gym_id = p_gym_id
        order by ch.checkin_at desc, ch.id desc
        limit least(greatest(coalesce(p_limit, 40), 1), 100)
    ) recent;

    return v_result;
end;
$$;

revoke all on function public.reception_list_checkins(uuid, integer)
    from public, anon, authenticated;
grant execute on function public.reception_list_checkins(uuid, integer)
    to authenticated;

create or replace function public.reception_account_context()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    select jsonb_build_object(
        'gym_id', gu.gym_id,
        'gym_name', g.name,
        'role', gu.role
    )
    into v_result
    from public.gym_users gu
    join public.gyms g
      on g.id = gu.gym_id
    where gu.user_id = (select auth.uid())
      and gu.role in ('admin', 'receptionist')
    order by gu.gym_id
    limit 1;

    if v_result is null then
        raise exception 'Esta cuenta todavía no pertenece a un gimnasio.'
            using errcode = 'P0002';
    end if;

    return v_result;
end;
$$;

revoke all on function public.reception_account_context()
    from public, anon, authenticated;
grant execute on function public.reception_account_context()
    to authenticated;

create or replace function public.reception_list_memberships(
    p_gym_id uuid,
    p_client_id bigint,
    p_limit integer default 30
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para consultar pagos.'
            using errcode = '42501';
    end if;

    if not private.client_belongs_to_gym(
        p_client_id,
        p_gym_id
    ) then
        raise exception 'Cliente no encontrado.' using errcode = 'P0002';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', recent.id,
                'plan_id', recent.plan_id,
                'plan_name', recent.plan_name,
                'start_date', recent.start_date,
                'end_date', recent.end_date,
                'amount', recent.amount,
                'payment_method', recent.payment_method,
                'payment_reference', recent.payment_reference,
                'paid_at', recent.paid_at,
                'notes', recent.notes
            )
            order by recent.paid_at desc, recent.id desc
        ),
        '[]'::jsonb
    )
    into v_result
    from (
        select
            m.id,
            m.plan_id,
            coalesce(p.name, 'Sin plan') as plan_name,
            m.start_date,
            m.end_date,
            coalesce(m.amount, m.amount_paid, 0)::bigint as amount,
            coalesce(m.payment_method, '') as payment_method,
            coalesce(m.payment_reference, '') as payment_reference,
            m.paid_at,
            coalesce(m.notes, '') as notes
        from public.memberships m
        left join public.plans p
          on p.id = m.plan_id
         and p.gym_id = m.gym_id
        where m.gym_id = p_gym_id
          and m.client_id = p_client_id
        order by m.paid_at desc, m.id desc
        limit least(greatest(coalesce(p_limit, 30), 1), 100)
    ) recent;

    return v_result;
end;
$$;

revoke all on function public.reception_list_memberships(
    uuid, bigint, integer
) from public, anon, authenticated;
grant execute on function public.reception_list_memberships(
    uuid, bigint, integer
) to authenticated;

create or replace function public.create_reception_invite()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_gym_id uuid;
    v_code uuid;
begin
    select gu.gym_id
    into v_gym_id
    from public.gym_users gu
    where gu.user_id = (select auth.uid())
      and gu.role = 'admin'
    order by gu.gym_id
    limit 1;

    if v_gym_id is null then
        raise exception 'Solo un administrador puede crear invitaciones.'
            using errcode = '42501';
    end if;

    update public.staff_invites
    set expires_at = now()
    where gym_id = v_gym_id
      and used_at is null
      and expires_at > now();

    insert into public.staff_invites(
        gym_id,
        role,
        created_by
    )
    values (
        v_gym_id,
        'receptionist',
        (select auth.uid())
    )
    returning code into v_code;

    return v_code;
end;
$$;

revoke all on function public.create_reception_invite()
    from public, anon, authenticated;
grant execute on function public.create_reception_invite()
    to authenticated;

create or replace function public.redeem_reception_invite(
    p_code uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_invite record;
    v_user_id uuid := (select auth.uid());
begin
    if v_user_id is null then
        raise exception 'Debes iniciar sesión.' using errcode = '42501';
    end if;

    if exists (
        select 1
        from public.gym_users gu
        where gu.user_id = v_user_id
    ) then
        raise exception 'Esta cuenta ya pertenece a un gimnasio.'
            using errcode = '23505';
    end if;

    select si.*
    into v_invite
    from public.staff_invites si
    where si.code = p_code
      and si.role = 'receptionist'
      and si.used_at is null
      and si.expires_at > now()
    for update;

    if not found then
        raise exception 'La invitación no existe o ya venció.'
            using errcode = '22023';
    end if;

    insert into public.gym_users(
        gym_id,
        user_id,
        role
    )
    values (
        v_invite.gym_id,
        v_user_id,
        'receptionist'
    );

    update public.staff_invites
    set
        used_by = v_user_id,
        used_at = now()
    where id = v_invite.id;

    return v_invite.gym_id;
end;
$$;

revoke all on function public.redeem_reception_invite(uuid)
    from public, anon, authenticated;
grant execute on function public.redeem_reception_invite(uuid)
    to authenticated;

do $$
begin
    if to_regprocedure(
        'public.get_attendance_statistics_internal(uuid,integer)'
    ) is null then
        alter function public.get_attendance_statistics(
            uuid,
            integer
        ) rename to get_attendance_statistics_internal;
    end if;
end;
$$;

revoke all on function public.get_attendance_statistics_internal(
    uuid,
    integer
) from public, anon, authenticated;

create or replace function public.get_attendance_statistics(
    p_gym_id uuid,
    p_days integer default 30
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'Las estadísticas son exclusivas del administrador.'
            using errcode = '42501';
    end if;

    return public.get_attendance_statistics_internal(
        p_gym_id,
        p_days
    );
end;
$$;

revoke all on function public.get_attendance_statistics(uuid, integer)
    from public, anon, authenticated;
grant execute on function public.get_attendance_statistics(uuid, integer)
    to authenticated;

commit;

select
    'SEGURIDAD DE RECEPCIÓN INSTALADA' as resultado,
    count(*) filter (where role = 'admin') as administradores,
    count(*) filter (where role = 'receptionist') as recepcionistas
from public.gym_users;
