begin;

-- Corrige el registro de pagos sin depender de los nombres de las
-- columnas devueltas por la función histórica.
create or replace function public.add_membership_accumulating(
    p_gym_id uuid,
    p_client_id bigint,
    p_plan_id bigint,
    p_requested_start date,
    p_amount bigint,
    p_payment_method text,
    p_payment_reference text,
    p_notes text
)
returns table(
    membership_id bigint,
    start_date date,
    end_date date
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_membership_id bigint;
    v_start_date date;
    v_end_date date;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para registrar pagos.'
            using errcode = '42501';
    end if;

    if not private.client_belongs_to_gym(p_client_id, p_gym_id)
       or not private.plan_belongs_to_gym(p_plan_id, p_gym_id) then
        raise exception 'El cliente o el plan no pertenece al gimnasio.'
            using errcode = '23503';
    end if;

    if coalesce(p_amount, 0) < 0 then
        raise exception 'El valor pagado no puede ser negativo.'
            using errcode = '22023';
    end if;

    -- Ejecutar la función original y descartar su forma de retorno.
    -- De este modo funciona aunque sus columnas se llamen de otra manera.
    perform 1
    from public.add_membership_accumulating_internal(
        p_gym_id,
        p_client_id,
        p_plan_id,
        p_requested_start,
        p_amount,
        p_payment_method,
        p_payment_reference,
        p_notes
    );

    select
        m.id,
        m.start_date,
        m.end_date
    into
        v_membership_id,
        v_start_date,
        v_end_date
    from public.memberships m
    where m.gym_id = p_gym_id
      and m.client_id = p_client_id
    order by m.id desc
    limit 1;

    if v_membership_id is null then
        raise exception 'La función de pagos no creó la membresía.'
            using errcode = 'P0001';
    end if;

    update public.memberships
    set recorded_by = (select auth.uid())
    where id = v_membership_id
      and gym_id = p_gym_id;

    return query
    select v_membership_id, v_start_date, v_end_date;
end;
$$;

revoke all on function public.add_membership_accumulating(
    uuid, bigint, bigint, date, bigint, text, text, text
) from public, anon, authenticated;
grant execute on function public.add_membership_accumulating(
    uuid, bigint, bigint, date, bigint, text, text, text
) to authenticated;


-- Registro inmutable de actividad administrativa y operativa.
create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    actor_user_id uuid,
    actor_email text not null default 'Sistema',
    actor_role text not null default 'system',
    action text not null,
    entity_type text not null,
    entity_id text,
    summary text not null default '',
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_gym_date
    on public.audit_logs(gym_id, created_at desc);

create index if not exists idx_audit_logs_gym_action
    on public.audit_logs(gym_id, action, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_admin_read on public.audit_logs;

create policy audit_logs_admin_read
on public.audit_logs
for select
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

revoke all on public.audit_logs from public, anon, authenticated;
grant select on public.audit_logs to authenticated;


create or replace function private.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_row jsonb;
    v_old_row jsonb;
    v_gym_id uuid;
    v_actor_user_id uuid;
    v_actor_email text := 'Sistema';
    v_actor_role text := 'system';
    v_action text;
    v_entity_id text;
    v_summary text := '';
    v_details jsonb := '{}'::jsonb;
begin
    if tg_op = 'DELETE' then
        v_row := to_jsonb(old);
    else
        v_row := to_jsonb(new);
    end if;

    if tg_op = 'UPDATE' then
        v_old_row := to_jsonb(old);

        -- El envoltorio de pagos completa recorded_by justo después
        -- de insertar. Ese cambio técnico no debe crear un log duplicado.
        if tg_table_name = 'memberships'
           and (v_row - 'recorded_by') = (v_old_row - 'recorded_by') then
            return new;
        end if;
    end if;

    v_gym_id := nullif(v_row ->> 'gym_id', '')::uuid;
    v_actor_user_id := coalesce(
        nullif(v_row ->> 'recorded_by', '')::uuid,
        (select auth.uid())
    );

    if v_actor_user_id is not null then
        select coalesce(gu.role, 'authenticated')
        into v_actor_role
        from public.gym_users gu
        where gu.gym_id = v_gym_id
          and gu.user_id = v_actor_user_id
        limit 1;

        v_actor_role := coalesce(v_actor_role, 'authenticated');
    end if;

    begin
        v_actor_email := coalesce(
            nullif(auth.jwt() ->> 'email', ''),
            case
                when v_actor_user_id is null then 'Sistema'
                else 'Usuario ' || left(v_actor_user_id::text, 8)
            end
        );
    exception when others then
        v_actor_email := case
            when v_actor_user_id is null then 'Sistema'
            else 'Usuario ' || left(v_actor_user_id::text, 8)
        end;
    end;

    if tg_table_name = 'memberships' then
        v_action := case tg_op
            when 'INSERT' then 'PAGO_REGISTRADO'
            when 'UPDATE' then 'PAGO_EDITADO'
            else 'PAGO_ELIMINADO'
        end;
        v_entity_id := v_row ->> 'id';
        v_summary := concat(
            'Pago de $',
            coalesce(v_row ->> 'amount', v_row ->> 'amount_paid', '0'),
            ' para el cliente #',
            coalesce(v_row ->> 'client_id', '—')
        );
        v_details := jsonb_build_object(
            'client_id', v_row ->> 'client_id',
            'plan_id', v_row ->> 'plan_id',
            'start_date', v_row ->> 'start_date',
            'end_date', v_row ->> 'end_date',
            'amount', coalesce(
                v_row ->> 'amount',
                v_row ->> 'amount_paid',
                '0'
            ),
            'payment_method', coalesce(
                v_row ->> 'payment_method',
                ''
            )
        );
    elsif tg_table_name = 'checkins' then
        v_action := 'ENTRADA_REGISTRADA';
        v_entity_id := v_row ->> 'id';
        v_summary := concat(
            'Entrada ',
            coalesce(v_row ->> 'result', 'registrada'),
            ' para el cliente #',
            coalesce(v_row ->> 'client_id', '—')
        );
        v_details := jsonb_build_object(
            'client_id', v_row ->> 'client_id',
            'result', v_row ->> 'result',
            'method', v_row ->> 'method'
        );
    elsif tg_table_name = 'clients' then
        v_action := case tg_op
            when 'INSERT' then 'CLIENTE_CREADO'
            when 'UPDATE' then 'CLIENTE_EDITADO'
            else 'CLIENTE_ELIMINADO'
        end;
        v_entity_id := v_row ->> 'id';
        v_summary := concat(
            coalesce(v_row ->> 'first_name', ''),
            ' ',
            coalesce(v_row ->> 'last_name', ''),
            ' · ',
            coalesce(v_row ->> 'document', '')
        );
        v_details := jsonb_build_object(
            'document', v_row ->> 'document',
            'client_name', trim(concat_ws(
                ' ',
                v_row ->> 'first_name',
                v_row ->> 'last_name'
            ))
        );
    elsif tg_table_name = 'plans' then
        v_action := case tg_op
            when 'INSERT' then 'PLAN_CREADO'
            when 'UPDATE' then 'PLAN_EDITADO'
            else 'PLAN_ELIMINADO'
        end;
        v_entity_id := v_row ->> 'id';
        v_summary := concat(
            coalesce(v_row ->> 'name', 'Plan'),
            ' · $',
            coalesce(v_row ->> 'price', '0')
        );
        v_details := jsonb_build_object(
            'name', v_row ->> 'name',
            'duration_days', v_row ->> 'duration_days',
            'price', v_row ->> 'price',
            'active', v_row ->> 'active'
        );
    elsif tg_table_name = 'gym_users' then
        v_action := case tg_op
            when 'INSERT' then 'USUARIO_AGREGADO'
            when 'UPDATE' then 'USUARIO_EDITADO'
            else 'USUARIO_ELIMINADO'
        end;
        v_entity_id := v_row ->> 'user_id';
        v_summary := concat(
            'Usuario ',
            left(coalesce(v_row ->> 'user_id', ''), 8),
            ' · ',
            coalesce(v_row ->> 'role', '')
        );
        v_details := jsonb_build_object(
            'user_id', v_row ->> 'user_id',
            'role', v_row ->> 'role'
        );
    else
        if tg_op = 'DELETE' then
            return old;
        end if;

        return new;
    end if;

    insert into public.audit_logs(
        gym_id,
        actor_user_id,
        actor_email,
        actor_role,
        action,
        entity_type,
        entity_id,
        summary,
        details
    )
    values (
        v_gym_id,
        v_actor_user_id,
        v_actor_email,
        v_actor_role,
        v_action,
        tg_table_name,
        v_entity_id,
        trim(v_summary),
        v_details
    );

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

revoke all on function private.write_audit_log()
    from public, anon, authenticated;


drop trigger if exists gymsoft_audit_memberships on public.memberships;
create trigger gymsoft_audit_memberships
after insert or update or delete on public.memberships
for each row execute function private.write_audit_log();

drop trigger if exists gymsoft_audit_checkins on public.checkins;
create trigger gymsoft_audit_checkins
after insert or delete on public.checkins
for each row execute function private.write_audit_log();

drop trigger if exists gymsoft_audit_clients on public.clients;
create trigger gymsoft_audit_clients
after insert or update or delete on public.clients
for each row execute function private.write_audit_log();

drop trigger if exists gymsoft_audit_plans on public.plans;
create trigger gymsoft_audit_plans
after insert or update or delete on public.plans
for each row execute function private.write_audit_log();

drop trigger if exists gymsoft_audit_gym_users on public.gym_users;
create trigger gymsoft_audit_gym_users
after insert or update or delete on public.gym_users
for each row execute function private.write_audit_log();


create or replace function public.get_finance_dashboard(
    p_gym_id uuid,
    p_date_from date default null,
    p_date_to date default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_from date := coalesce(
        p_date_from,
        date_trunc('month', public.gymsoft_today())::date
    );
    v_to date := coalesce(p_date_to, public.gymsoft_today());
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'Las finanzas son exclusivas del administrador.'
            using errcode = '42501';
    end if;

    if v_from > v_to then
        raise exception 'La fecha inicial no puede superar la fecha final.'
            using errcode = '22023';
    end if;

    if (v_to - v_from) > 730 then
        raise exception 'El período máximo permitido es de 730 días.'
            using errcode = '22023';
    end if;

    with payments as (
        select
            m.id,
            m.client_id,
            trim(concat_ws(' ', c.first_name, c.last_name))
                as client_name,
            c.document,
            coalesce(p.name, 'Sin plan') as plan_name,
            coalesce(m.amount, m.amount_paid, 0)::bigint as amount,
            coalesce(m.payment_method, 'SIN DEFINIR') as payment_method,
            coalesce(m.payment_reference, '') as payment_reference,
            m.start_date,
            m.end_date,
            m.paid_at,
            m.recorded_by,
            coalesce(
                nullif(a.actor_email, ''),
                case
                    when m.recorded_by is null then 'Anterior al registro'
                    else 'Usuario ' || left(m.recorded_by::text, 8)
                end
            ) as actor_email,
            coalesce(
                nullif(a.actor_role, ''),
                case
                    when m.recorded_by is null then 'system'
                    else 'authenticated'
                end
            ) as actor_role,
            (m.paid_at at time zone 'America/Bogota')::date as paid_date
        from public.memberships m
        join public.clients c
          on c.id = m.client_id
         and c.gym_id = m.gym_id
        left join public.plans p
          on p.id = m.plan_id
         and p.gym_id = m.gym_id
        left join lateral (
            select
                al.actor_email,
                al.actor_role
            from public.audit_logs al
            where al.gym_id = m.gym_id
              and al.entity_type = 'memberships'
              and al.entity_id = m.id::text
              and al.action = 'PAGO_REGISTRADO'
            order by al.created_at asc, al.id asc
            limit 1
        ) a on true
        where m.gym_id = p_gym_id
          and (m.paid_at at time zone 'America/Bogota')::date
              between v_from and v_to
    )
    select jsonb_build_object(
        'date_from', v_from,
        'date_to', v_to,
        'total_income', coalesce((
            select sum(amount) from payments
        ), 0),
        'payment_count', (
            select count(*) from payments
        ),
        'average_payment', coalesce((
            select round(avg(amount))::bigint from payments
        ), 0),
        'by_method', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'label', grouped.payment_method,
                    'count', grouped.payment_count,
                    'total', grouped.total
                )
                order by grouped.total desc, grouped.payment_method
            )
            from (
                select
                    payment_method,
                    count(*) as payment_count,
                    sum(amount)::bigint as total
                from payments
                group by payment_method
            ) grouped
        ), '[]'::jsonb),
        'by_plan', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'label', grouped.plan_name,
                    'count', grouped.payment_count,
                    'total', grouped.total
                )
                order by grouped.total desc, grouped.plan_name
            )
            from (
                select
                    plan_name,
                    count(*) as payment_count,
                    sum(amount)::bigint as total
                from payments
                group by plan_name
            ) grouped
        ), '[]'::jsonb),
        'by_day', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'date', grouped.paid_date,
                    'count', grouped.payment_count,
                    'total', grouped.total
                )
                order by grouped.paid_date
            )
            from (
                select
                    paid_date,
                    count(*) as payment_count,
                    sum(amount)::bigint as total
                from payments
                group by paid_date
            ) grouped
        ), '[]'::jsonb),
        'payments', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'id', item.id,
                    'client_id', item.client_id,
                    'client_name', item.client_name,
                    'document', item.document,
                    'plan_name', item.plan_name,
                    'amount', item.amount,
                    'payment_method', item.payment_method,
                    'payment_reference', item.payment_reference,
                    'start_date', item.start_date,
                    'end_date', item.end_date,
                    'paid_at', item.paid_at,
                    'actor_email', item.actor_email,
                    'actor_role', item.actor_role
                )
                order by item.paid_at desc, item.id desc
            )
            from payments item
        ), '[]'::jsonb)
    )
    into v_result;

    return v_result;
end;
$$;

revoke all on function public.get_finance_dashboard(
    uuid, date, date
) from public, anon, authenticated;
grant execute on function public.get_finance_dashboard(
    uuid, date, date
) to authenticated;


create or replace function public.get_audit_logs(
    p_gym_id uuid,
    p_limit integer default 200,
    p_action text default ''
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'La auditoría es exclusiva del administrador.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', recent.id,
                'actor_user_id', recent.actor_user_id,
                'actor_email', recent.actor_email,
                'actor_role', recent.actor_role,
                'action', recent.action,
                'entity_type', recent.entity_type,
                'entity_id', recent.entity_id,
                'summary', recent.summary,
                'details', recent.details,
                'created_at', recent.created_at
            )
            order by recent.created_at desc, recent.id desc
        ),
        '[]'::jsonb
    )
    into v_result
    from (
        select al.*
        from public.audit_logs al
        where al.gym_id = p_gym_id
          and (
              trim(coalesce(p_action, '')) = ''
              or al.action = trim(p_action)
          )
        order by al.created_at desc, al.id desc
        limit least(greatest(coalesce(p_limit, 200), 1), 500)
    ) recent;

    return v_result;
end;
$$;

revoke all on function public.get_audit_logs(
    uuid, integer, text
) from public, anon, authenticated;
grant execute on function public.get_audit_logs(
    uuid, integer, text
) to authenticated;

commit;

select
    'PAGOS, FINANZAS Y AUDITORÍA INSTALADOS' as resultado,
    count(*) as registros_de_auditoria
from public.audit_logs;
