begin;

create table if not exists public.store_products (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    name text not null,
    sku text not null default '',
    sale_price bigint not null check (sale_price >= 0),
    stock_quantity integer not null default 0
        check (stock_quantity >= 0),
    low_stock_threshold integer not null default 5
        check (low_stock_threshold >= 0),
    active boolean not null default true,
    created_by uuid,
    updated_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (length(trim(name)) > 0)
);

create unique index if not exists store_products_gym_name_unique
    on public.store_products(gym_id, lower(trim(name)));

create unique index if not exists store_products_gym_sku_unique
    on public.store_products(gym_id, lower(trim(sku)))
    where trim(sku) <> '';

create index if not exists store_products_gym_active_name
    on public.store_products(gym_id, active, name);

create table if not exists public.store_sales (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    product_id bigint not null
        references public.store_products(id) on delete restrict,
    product_name text not null,
    product_sku text not null default '',
    quantity integer not null check (quantity > 0),
    unit_price bigint not null check (unit_price >= 0),
    total_amount bigint not null check (total_amount >= 0),
    payment_method text not null default 'EFECTIVO',
    payment_reference text not null default '',
    customer_name text not null default '',
    notes text not null default '',
    sold_by uuid,
    sold_at timestamptz not null default now()
);

create index if not exists store_sales_gym_date
    on public.store_sales(gym_id, sold_at desc);

create index if not exists store_sales_gym_product
    on public.store_sales(gym_id, product_id, sold_at desc);

alter table public.store_products enable row level security;
alter table public.store_sales enable row level security;

drop policy if exists store_products_admin_all
    on public.store_products;
create policy store_products_admin_all
on public.store_products
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists store_sales_admin_all
    on public.store_sales;
create policy store_sales_admin_all
on public.store_sales
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

revoke all on public.store_products
    from public, anon, authenticated;
revoke all on public.store_sales
    from public, anon, authenticated;
grant select, insert, update, delete
    on public.store_products to authenticated;
grant select, insert, update, delete
    on public.store_sales to authenticated;


create or replace function public.admin_list_store_products(
    p_gym_id uuid,
    p_search text default '',
    p_include_inactive boolean default true
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_search text := trim(coalesce(p_search, ''));
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'La tienda administrativa es exclusiva del administrador.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', p.id,
                'name', p.name,
                'sku', p.sku,
                'sale_price', p.sale_price,
                'stock_quantity', p.stock_quantity,
                'low_stock_threshold', p.low_stock_threshold,
                'active', p.active,
                'stock_status', case
                    when not p.active then 'INACTIVO'
                    when p.stock_quantity = 0 then 'AGOTADO'
                    when p.stock_quantity <= p.low_stock_threshold
                        then 'POCAS UNIDADES'
                    else 'DISPONIBLE'
                end,
                'created_at', p.created_at,
                'updated_at', p.updated_at
            )
            order by p.active desc, p.name
        ),
        '[]'::jsonb
    )
    into v_result
    from public.store_products p
    where p.gym_id = p_gym_id
      and (p_include_inactive or p.active)
      and (
          v_search = ''
          or p.name ilike '%' || v_search || '%'
          or p.sku ilike '%' || v_search || '%'
      );

    return v_result;
end;
$$;

revoke all on function public.admin_list_store_products(
    uuid, text, boolean
) from public, anon, authenticated;
grant execute on function public.admin_list_store_products(
    uuid, text, boolean
) to authenticated;


create or replace function public.admin_save_store_product(
    p_gym_id uuid,
    p_product_id bigint,
    p_name text,
    p_sku text,
    p_sale_price bigint,
    p_stock_quantity integer,
    p_low_stock_threshold integer,
    p_active boolean
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_product_id bigint;
    v_user_id uuid := (select auth.uid());
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'Solo el administrador puede modificar productos.'
            using errcode = '42501';
    end if;

    if trim(coalesce(p_name, '')) = ''
       or coalesce(p_sale_price, -1) < 0
       or coalesce(p_stock_quantity, -1) < 0
       or coalesce(p_low_stock_threshold, -1) < 0 then
        raise exception 'Revisa el nombre, precio y cantidades del producto.'
            using errcode = '22023';
    end if;

    if p_product_id is null then
        insert into public.store_products(
            gym_id,
            name,
            sku,
            sale_price,
            stock_quantity,
            low_stock_threshold,
            active,
            created_by,
            updated_by
        )
        values (
            p_gym_id,
            trim(p_name),
            upper(trim(coalesce(p_sku, ''))),
            p_sale_price,
            p_stock_quantity,
            p_low_stock_threshold,
            coalesce(p_active, true),
            v_user_id,
            v_user_id
        )
        returning id into v_product_id;
    else
        update public.store_products
        set
            name = trim(p_name),
            sku = upper(trim(coalesce(p_sku, ''))),
            sale_price = p_sale_price,
            stock_quantity = p_stock_quantity,
            low_stock_threshold = p_low_stock_threshold,
            active = coalesce(p_active, true),
            updated_by = v_user_id,
            updated_at = now()
        where id = p_product_id
          and gym_id = p_gym_id
        returning id into v_product_id;

        if v_product_id is null then
            raise exception 'Producto no encontrado.'
                using errcode = 'P0002';
        end if;
    end if;

    return v_product_id;
end;
$$;

revoke all on function public.admin_save_store_product(
    uuid, bigint, text, text, bigint, integer, integer, boolean
) from public, anon, authenticated;
grant execute on function public.admin_save_store_product(
    uuid, bigint, text, text, bigint, integer, integer, boolean
) to authenticated;


create or replace function public.reception_list_store_products(
    p_gym_id uuid,
    p_search text default ''
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_search text := trim(coalesce(p_search, ''));
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para consultar la tienda.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', p.id,
                'name', p.name,
                'sku', p.sku,
                'sale_price', p.sale_price,
                'stock_quantity', p.stock_quantity,
                'low_stock_threshold', p.low_stock_threshold,
                'available', p.stock_quantity > 0
            )
            order by (p.stock_quantity > 0) desc, p.name
        ),
        '[]'::jsonb
    )
    into v_result
    from public.store_products p
    where p.gym_id = p_gym_id
      and p.active = true
      and (
          v_search = ''
          or p.name ilike '%' || v_search || '%'
          or p.sku ilike '%' || v_search || '%'
      );

    return v_result;
end;
$$;

revoke all on function public.reception_list_store_products(
    uuid, text
) from public, anon, authenticated;
grant execute on function public.reception_list_store_products(
    uuid, text
) to authenticated;


create or replace function public.register_store_sale(
    p_gym_id uuid,
    p_product_id bigint,
    p_quantity integer,
    p_payment_method text,
    p_payment_reference text,
    p_customer_name text,
    p_notes text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_product record;
    v_sale_id bigint;
    v_sold_at timestamptz;
    v_total bigint;
    v_remaining integer;
    v_payment_method text := upper(
        coalesce(nullif(trim(p_payment_method), ''), 'EFECTIVO')
    );
    v_user_id uuid := (select auth.uid());
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin', 'receptionist']::text[]
    ) then
        raise exception 'No tienes permiso para registrar ventas.'
            using errcode = '42501';
    end if;

    if coalesce(p_quantity, 0) <= 0 then
        raise exception 'La cantidad debe ser mayor que cero.'
            using errcode = '22023';
    end if;

    if v_payment_method not in (
        'EFECTIVO',
        'TRANSFERENCIA',
        'TARJETA',
        'OTRO'
    ) then
        raise exception 'El método de pago no es válido.'
            using errcode = '22023';
    end if;

    select p.*
    into v_product
    from public.store_products p
    where p.id = p_product_id
      and p.gym_id = p_gym_id
    for update;

    if not found or not coalesce(v_product.active, false) then
        raise exception 'El producto no existe o está desactivado.'
            using errcode = 'P0002';
    end if;

    if v_product.stock_quantity < p_quantity then
        raise exception 'Existencias insuficientes. Disponibles: %.',
            v_product.stock_quantity
            using errcode = '22023';
    end if;

    v_total := v_product.sale_price * p_quantity;
    v_remaining := v_product.stock_quantity - p_quantity;

    update public.store_products
    set
        stock_quantity = v_remaining,
        updated_by = v_user_id,
        updated_at = now()
    where id = v_product.id
      and gym_id = p_gym_id;

    insert into public.store_sales(
        gym_id,
        product_id,
        product_name,
        product_sku,
        quantity,
        unit_price,
        total_amount,
        payment_method,
        payment_reference,
        customer_name,
        notes,
        sold_by
    )
    values (
        p_gym_id,
        v_product.id,
        v_product.name,
        v_product.sku,
        p_quantity,
        v_product.sale_price,
        v_total,
        v_payment_method,
        trim(coalesce(p_payment_reference, '')),
        trim(coalesce(p_customer_name, '')),
        trim(coalesce(p_notes, '')),
        v_user_id
    )
    returning id, sold_at into v_sale_id, v_sold_at;

    return jsonb_build_object(
        'sale_id', v_sale_id,
        'product_id', v_product.id,
        'product_name', v_product.name,
        'quantity', p_quantity,
        'unit_price', v_product.sale_price,
        'total_amount', v_total,
        'stock_remaining', v_remaining,
        'sold_at', v_sold_at
    );
end;
$$;

revoke all on function public.register_store_sale(
    uuid, bigint, integer, text, text, text, text
) from public, anon, authenticated;
grant execute on function public.register_store_sale(
    uuid, bigint, integer, text, text, text, text
) to authenticated;


create or replace function private.insert_store_audit(
    p_gym_id uuid,
    p_actor_user_id uuid,
    p_action text,
    p_entity_type text,
    p_entity_id text,
    p_summary text,
    p_details jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actor_email text;
    v_actor_role text;
begin
    select coalesce(gu.role, 'authenticated')
    into v_actor_role
    from public.gym_users gu
    where gu.gym_id = p_gym_id
      and gu.user_id = p_actor_user_id
    limit 1;

    v_actor_role := coalesce(v_actor_role, 'system');

    begin
        v_actor_email := coalesce(
            nullif(auth.jwt() ->> 'email', ''),
            case
                when p_actor_user_id is null then 'Sistema'
                else 'Usuario ' || left(p_actor_user_id::text, 8)
            end
        );
    exception when others then
        v_actor_email := case
            when p_actor_user_id is null then 'Sistema'
            else 'Usuario ' || left(p_actor_user_id::text, 8)
        end;
    end;

    insert into public.audit_logs(
        gym_id,
        actor_user_id,
        actor_email,
        actor_role,
        action,
        entity_type,
        entity_id,
        summary,
        details
    )
    values (
        p_gym_id,
        p_actor_user_id,
        v_actor_email,
        v_actor_role,
        p_action,
        p_entity_type,
        p_entity_id,
        trim(coalesce(p_summary, '')),
        coalesce(p_details, '{}'::jsonb)
    );
end;
$$;

revoke all on function private.insert_store_audit(
    uuid, uuid, text, text, text, text, jsonb
) from public, anon, authenticated;


create or replace function private.audit_store_product()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_row jsonb;
    v_action text;
    v_actor uuid;
    v_summary text;
    v_details jsonb;
begin
    v_row := case
        when tg_op = 'DELETE' then to_jsonb(old)
        else to_jsonb(new)
    end;
    v_action := case tg_op
        when 'INSERT' then 'PRODUCTO_CREADO'
        when 'UPDATE' then 'PRODUCTO_EDITADO'
        else 'PRODUCTO_ELIMINADO'
    end;
    v_actor := coalesce(
        nullif(v_row ->> 'updated_by', '')::uuid,
        nullif(v_row ->> 'created_by', '')::uuid,
        (select auth.uid())
    );

    if tg_op = 'UPDATE' then
        v_summary := concat(
            new.name,
            ' · Precio $', old.sale_price, ' → $', new.sale_price,
            ' · Stock ', old.stock_quantity, ' → ', new.stock_quantity
        );
        v_details := jsonb_build_object(
            'before', jsonb_build_object(
                'name', old.name,
                'sku', old.sku,
                'sale_price', old.sale_price,
                'stock_quantity', old.stock_quantity,
                'active', old.active
            ),
            'after', jsonb_build_object(
                'name', new.name,
                'sku', new.sku,
                'sale_price', new.sale_price,
                'stock_quantity', new.stock_quantity,
                'active', new.active
            )
        );
    else
        v_summary := concat(
            coalesce(v_row ->> 'name', 'Producto'),
            ' · $', coalesce(v_row ->> 'sale_price', '0'),
            ' · Stock ', coalesce(v_row ->> 'stock_quantity', '0')
        );
        v_details := jsonb_build_object(
            'name', v_row ->> 'name',
            'sku', v_row ->> 'sku',
            'sale_price', v_row ->> 'sale_price',
            'stock_quantity', v_row ->> 'stock_quantity',
            'active', v_row ->> 'active'
        );
    end if;

    perform private.insert_store_audit(
        nullif(v_row ->> 'gym_id', '')::uuid,
        v_actor,
        v_action,
        'store_products',
        v_row ->> 'id',
        v_summary,
        v_details
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

revoke all on function private.audit_store_product()
    from public, anon, authenticated;


create or replace function private.audit_store_sale()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    perform private.insert_store_audit(
        new.gym_id,
        coalesce(new.sold_by, (select auth.uid())),
        'VENTA_TIENDA',
        'store_sales',
        new.id::text,
        concat(
            new.quantity, ' × ', new.product_name,
            ' · $', new.total_amount,
            ' · ', new.payment_method
        ),
        jsonb_build_object(
            'product_id', new.product_id,
            'product_name', new.product_name,
            'quantity', new.quantity,
            'unit_price', new.unit_price,
            'total_amount', new.total_amount,
            'payment_method', new.payment_method,
            'customer_name', new.customer_name
        )
    );
    return new;
end;
$$;

revoke all on function private.audit_store_sale()
    from public, anon, authenticated;

drop trigger if exists gymsoft_audit_store_products
    on public.store_products;
create trigger gymsoft_audit_store_products
after insert or update or delete on public.store_products
for each row execute function private.audit_store_product();

drop trigger if exists gymsoft_audit_store_sales
    on public.store_sales;
create trigger gymsoft_audit_store_sales
after insert on public.store_sales
for each row execute function private.audit_store_sale();

drop trigger if exists gymsoft_store_products_event
    on public.store_products;
create trigger gymsoft_store_products_event
after insert or update or delete on public.store_products
for each row execute function private.notify_gym_change();

drop trigger if exists gymsoft_store_sales_event
    on public.store_sales;
create trigger gymsoft_store_sales_event
after insert on public.store_sales
for each row execute function private.notify_gym_change();


create or replace function public.admin_list_store_sales(
    p_gym_id uuid,
    p_limit integer default 100
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'Las ventas son exclusivas del administrador.'
            using errcode = '42501';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', recent.id,
                'product_id', recent.product_id,
                'product_name', recent.product_name,
                'product_sku', recent.product_sku,
                'quantity', recent.quantity,
                'unit_price', recent.unit_price,
                'total_amount', recent.total_amount,
                'payment_method', recent.payment_method,
                'payment_reference', recent.payment_reference,
                'customer_name', recent.customer_name,
                'notes', recent.notes,
                'sold_by', recent.sold_by,
                'sold_at', recent.sold_at,
                'actor_email', recent.actor_email,
                'actor_role', recent.actor_role
            )
            order by recent.sold_at desc, recent.id desc
        ),
        '[]'::jsonb
    )
    into v_result
    from (
        select
            s.*,
            coalesce(al.actor_email, 'Sistema') as actor_email,
            coalesce(al.actor_role, 'system') as actor_role
        from public.store_sales s
        left join lateral (
            select a.actor_email, a.actor_role
            from public.audit_logs a
            where a.gym_id = s.gym_id
              and a.entity_type = 'store_sales'
              and a.entity_id = s.id::text
              and a.action = 'VENTA_TIENDA'
            order by a.id desc
            limit 1
        ) al on true
        where s.gym_id = p_gym_id
        order by s.sold_at desc, s.id desc
        limit least(greatest(coalesce(p_limit, 100), 1), 500)
    ) recent;

    return v_result;
end;
$$;

revoke all on function public.admin_list_store_sales(
    uuid, integer
) from public, anon, authenticated;
grant execute on function public.admin_list_store_sales(
    uuid, integer
) to authenticated;


create or replace function public.admin_store_finance(
    p_gym_id uuid,
    p_date_from date,
    p_date_to date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_from date := coalesce(
        p_date_from,
        date_trunc('month', public.gymsoft_today())::date
    );
    v_to date := coalesce(p_date_to, public.gymsoft_today());
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'Las finanzas son exclusivas del administrador.'
            using errcode = '42501';
    end if;

    if v_from > v_to or (v_to - v_from) > 730 then
        raise exception 'El período de consulta no es válido.'
            using errcode = '22023';
    end if;

    with sales as (
        select
            s.*,
            (s.sold_at at time zone 'America/Bogota')::date as sold_date,
            coalesce(al.actor_email, 'Sistema') as actor_email,
            coalesce(al.actor_role, 'system') as actor_role
        from public.store_sales s
        left join lateral (
            select a.actor_email, a.actor_role
            from public.audit_logs a
            where a.gym_id = s.gym_id
              and a.entity_type = 'store_sales'
              and a.entity_id = s.id::text
              and a.action = 'VENTA_TIENDA'
            order by a.id desc
            limit 1
        ) al on true
        where s.gym_id = p_gym_id
          and (s.sold_at at time zone 'America/Bogota')::date
              between v_from and v_to
    )
    select jsonb_build_object(
        'date_from', v_from,
        'date_to', v_to,
        'store_income', coalesce((
            select sum(total_amount) from sales
        ), 0),
        'sale_count', (select count(*) from sales),
        'average_sale', coalesce((
            select round(avg(total_amount))::bigint from sales
        ), 0),
        'by_product', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'label', grouped.product_name,
                    'count', grouped.units_sold,
                    'transactions', grouped.sale_count,
                    'total', grouped.total
                )
                order by grouped.total desc, grouped.product_name
            )
            from (
                select
                    product_name,
                    sum(quantity)::bigint as units_sold,
                    count(*) as sale_count,
                    sum(total_amount)::bigint as total
                from sales
                group by product_name
            ) grouped
        ), '[]'::jsonb),
        'by_method', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'label', grouped.payment_method,
                    'count', grouped.sale_count,
                    'total', grouped.total
                )
                order by grouped.total desc, grouped.payment_method
            )
            from (
                select
                    payment_method,
                    count(*) as sale_count,
                    sum(total_amount)::bigint as total
                from sales
                group by payment_method
            ) grouped
        ), '[]'::jsonb),
        'sales', coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'id', s.id,
                    'product_name', s.product_name,
                    'product_sku', s.product_sku,
                    'quantity', s.quantity,
                    'unit_price', s.unit_price,
                    'total_amount', s.total_amount,
                    'payment_method', s.payment_method,
                    'payment_reference', s.payment_reference,
                    'customer_name', s.customer_name,
                    'sold_at', s.sold_at,
                    'actor_email', s.actor_email,
                    'actor_role', s.actor_role
                )
                order by s.sold_at desc, s.id desc
            )
            from sales s
        ), '[]'::jsonb)
    )
    into v_result;

    return v_result;
end;
$$;

revoke all on function public.admin_store_finance(
    uuid, date, date
) from public, anon, authenticated;
grant execute on function public.admin_store_finance(
    uuid, date, date
) to authenticated;

commit;

select
    'TIENDA INSTALADA' as resultado,
    count(*) as productos
from public.store_products;
