begin;

-- GymSoft 1.4
-- Tiquetera de 15 entradas, contabilidad y jornadas controladas por Admin.

-- Solo las compras nuevas toman el nuevo límite. Las membresías ya vendidas
-- conservan el valor guardado en memberships.entry_limit.
update public.plans
set entry_limit = 15
where lower(trim(name)) = 'tiquetera';

alter table public.trainers
    add column if not exists hourly_rate bigint not null default 0,
    add column if not exists hire_date date,
    add column if not exists notes text not null default '',
    add column if not exists created_by uuid;

alter table public.trainers
    drop constraint if exists trainers_hourly_rate_check;

alter table public.trainers
    add constraint trainers_hourly_rate_check
    check (hourly_rate >= 0);

create table if not exists public.accounting_expenses (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    expense_date date not null,
    category text not null,
    description text not null,
    vendor text not null default '',
    amount bigint not null check (amount > 0),
    payment_method text not null default 'Efectivo',
    payment_reference text not null default '',
    receipt_reference text not null default '',
    notes text not null default '',
    recorded_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_accounting_expenses_gym_date
    on public.accounting_expenses(gym_id, expense_date desc, id desc);

create table if not exists public.staff_shifts (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    trainer_id bigint not null references public.trainers(id) on delete cascade,
    check_in_at timestamptz not null default now(),
    check_out_at timestamptz,
    hourly_rate_snapshot bigint not null default 0
        check (hourly_rate_snapshot >= 0),
    notes text not null default '',
    recorded_by uuid,
    created_at timestamptz not null default now(),
    check (check_out_at is null or check_out_at >= check_in_at)
);

create index if not exists idx_staff_shifts_gym_date
    on public.staff_shifts(gym_id, check_in_at desc);

create index if not exists idx_staff_shifts_trainer_date
    on public.staff_shifts(trainer_id, check_in_at desc);

create unique index if not exists idx_staff_shifts_one_open
    on public.staff_shifts(trainer_id)
    where check_out_at is null;

alter table public.accounting_expenses enable row level security;
alter table public.staff_shifts enable row level security;

drop policy if exists accounting_expenses_admin_all
    on public.accounting_expenses;
create policy accounting_expenses_admin_all
on public.accounting_expenses
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists staff_shifts_admin_all on public.staff_shifts;
create policy staff_shifts_admin_all
on public.staff_shifts
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

grant select, insert, update, delete
    on public.accounting_expenses to authenticated;
grant select, insert, update, delete
    on public.staff_shifts to authenticated;
grant usage, select on sequence public.accounting_expenses_id_seq
    to authenticated;
grant usage, select on sequence public.staff_shifts_id_seq
    to authenticated;

drop trigger if exists gymsoft_notify_accounting_expenses
    on public.accounting_expenses;
create trigger gymsoft_notify_accounting_expenses
after insert or update or delete on public.accounting_expenses
for each row execute function private.notify_gym_change();

drop trigger if exists gymsoft_notify_staff_shifts
    on public.staff_shifts;
create trigger gymsoft_notify_staff_shifts
after insert or update or delete on public.staff_shifts
for each row execute function private.notify_gym_change();

create or replace function private.write_staff_accounting_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_row jsonb;
    v_gym_id uuid;
    v_actor uuid;
    v_email text;
    v_role text;
    v_action text;
    v_summary text;
begin
    v_row := case
        when tg_op = 'DELETE' then to_jsonb(old)
        else to_jsonb(new)
    end;
    v_gym_id := (v_row ->> 'gym_id')::uuid;
    v_actor := coalesce(
        nullif(v_row ->> 'recorded_by', '')::uuid,
        nullif(v_row ->> 'created_by', '')::uuid,
        (select auth.uid())
    );

    select coalesce(gu.role, 'authenticated')
    into v_role
    from public.gym_users gu
    where gu.gym_id = v_gym_id
      and gu.user_id = v_actor
    limit 1;

    v_role := coalesce(v_role, 'system');
    v_email := coalesce(
        nullif(auth.jwt() ->> 'email', ''),
        case
            when v_actor is null then 'Sistema'
            else 'Usuario ' || left(v_actor::text, 8)
        end
    );

    if tg_table_name = 'accounting_expenses' then
        v_action := case tg_op
            when 'INSERT' then 'EGRESO_REGISTRADO'
            when 'UPDATE' then 'EGRESO_EDITADO'
            else 'EGRESO_ELIMINADO'
        end;
        v_summary := concat(
            coalesce(v_row ->> 'category', 'Egreso'),
            ' · $', coalesce(v_row ->> 'amount', '0'),
            ' · ', coalesce(v_row ->> 'description', '')
        );
    elsif tg_table_name = 'staff_shifts' then
        v_action := case
            when tg_op = 'INSERT' then 'JORNADA_INICIADA'
            when tg_op = 'DELETE' then 'JORNADA_ELIMINADA'
            when old.check_out_at is null and new.check_out_at is not null
                then 'JORNADA_FINALIZADA'
            else 'JORNADA_EDITADA'
        end;
        v_summary := concat(
            'Entrenador #', coalesce(v_row ->> 'trainer_id', '—'),
            ' · ', coalesce(v_row ->> 'check_in_at', ''),
            case
                when nullif(v_row ->> 'check_out_at', '') is null
                    then ' · jornada activa'
                else ' · salida ' || (v_row ->> 'check_out_at')
            end
        );
    elsif tg_table_name = 'trainers' then
        v_action := case tg_op
            when 'INSERT' then 'ENTRENADOR_CREADO'
            when 'UPDATE' then 'ENTRENADOR_EDITADO'
            else 'ENTRENADOR_ELIMINADO'
        end;
        v_summary := concat(
            coalesce(v_row ->> 'name', 'Entrenador'),
            ' · $', coalesce(v_row ->> 'hourly_rate', '0'), '/hora'
        );
    else
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    insert into public.audit_logs(
        gym_id,
        actor_user_id,
        actor_email,
        actor_role,
        action,
        entity_type,
        entity_id,
        summary,
        details
    )
    values (
        v_gym_id,
        v_actor,
        v_email,
        v_role,
        v_action,
        tg_table_name,
        v_row ->> 'id',
        trim(v_summary),
        v_row
    );

    if tg_op = 'DELETE' then
        return old;
    end if;

    return new;
end;
$$;

revoke all on function private.write_staff_accounting_audit()
    from public, anon, authenticated;

drop trigger if exists gymsoft_audit_accounting_expenses
    on public.accounting_expenses;
create trigger gymsoft_audit_accounting_expenses
after insert or update or delete on public.accounting_expenses
for each row execute function private.write_staff_accounting_audit();

drop trigger if exists gymsoft_audit_staff_shifts on public.staff_shifts;
create trigger gymsoft_audit_staff_shifts
after insert or update or delete on public.staff_shifts
for each row execute function private.write_staff_accounting_audit();

drop trigger if exists gymsoft_audit_trainers_staff on public.trainers;
create trigger gymsoft_audit_trainers_staff
after insert or update or delete on public.trainers
for each row execute function private.write_staff_accounting_audit();

create or replace function public.admin_staff_clock(
    p_gym_id uuid,
    p_trainer_id bigint,
    p_action text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_trainer public.trainers%rowtype;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'Solo el administrador puede controlar jornadas.'
            using errcode = '42501';
    end if;

    select t.* into v_trainer
    from public.trainers t
    where t.id = p_trainer_id
      and t.gym_id = p_gym_id
      and t.active = true;

    if not found then
        raise exception 'El trabajador no existe o está inactivo.'
            using errcode = '23503';
    end if;

    if upper(trim(p_action)) = 'IN' then
        if exists (
            select 1 from public.staff_shifts s
            where s.trainer_id = p_trainer_id
              and s.check_out_at is null
        ) then
            raise exception 'El trabajador ya tiene una jornada activa.'
                using errcode = '23505';
        end if;

        insert into public.staff_shifts(
            gym_id,
            trainer_id,
            hourly_rate_snapshot,
            recorded_by
        ) values (
            p_gym_id,
            p_trainer_id,
            v_trainer.hourly_rate,
            (select auth.uid())
        );
    elsif upper(trim(p_action)) = 'OUT' then
        update public.staff_shifts
        set check_out_at = now(), recorded_by = (select auth.uid())
        where trainer_id = p_trainer_id
          and gym_id = p_gym_id
          and check_out_at is null;

        if not found then
            raise exception 'El trabajador no tiene una jornada activa.'
                using errcode = 'P0002';
        end if;
    else
        raise exception 'La acción debe ser IN u OUT.'
            using errcode = '22023';
    end if;
end;
$$;

revoke all on function public.admin_staff_clock(uuid, bigint, text)
    from public, anon, authenticated;
grant execute on function public.admin_staff_clock(uuid, bigint, text)
    to authenticated;

create or replace function public.admin_staff_dashboard(
    p_gym_id uuid,
    p_date_from date,
    p_date_to date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'La información de personal es administrativa.'
            using errcode = '42501';
    end if;

    if p_date_from is null or p_date_to is null or p_date_from > p_date_to then
        raise exception 'El período de jornadas no es válido.'
            using errcode = '22023';
    end if;

    with shift_values as (
        select
            s.*,
            greatest(
                extract(epoch from (
                    coalesce(s.check_out_at, now()) - s.check_in_at
                ))::bigint,
                0
            ) as duration_seconds
        from public.staff_shifts s
        where s.gym_id = p_gym_id
          and (s.check_in_at at time zone 'America/Bogota')::date
              between p_date_from and p_date_to
    ), worker_values as (
        select
            t.*,
            coalesce((
                select sum(s.duration_seconds)
                from shift_values s
                where s.trainer_id = t.id
            ), 0)::bigint as period_seconds,
            coalesce((
                select round(sum(
                    s.duration_seconds * s.hourly_rate_snapshot / 3600.0
                ))::bigint
                from shift_values s
                where s.trainer_id = t.id
            ), 0)::bigint as estimated_pay,
            (
                select s.check_in_at
                from public.staff_shifts s
                where s.trainer_id = t.id
                  and s.check_out_at is null
                order by s.check_in_at desc
                limit 1
            ) as current_check_in
        from public.trainers t
        where t.gym_id = p_gym_id
    )
    select jsonb_build_object(
        'active_staff', (
            select count(*) from worker_values w where w.active = true
        ),
        'working_now', (
            select count(*) from worker_values w
            where w.current_check_in is not null
        ),
        'total_seconds', coalesce((
            select sum(w.period_seconds) from worker_values w
        ), 0),
        'estimated_payroll', coalesce((
            select sum(w.estimated_pay) from worker_values w
        ), 0),
        'workers', coalesce((
            select jsonb_agg(jsonb_build_object(
                'id', w.id,
                'name', w.name,
                'phone', w.phone,
                'email', w.email,
                'specialty', w.specialty,
                'hourly_rate', w.hourly_rate,
                'hire_date', w.hire_date,
                'notes', w.notes,
                'active', w.active,
                'current_check_in', w.current_check_in,
                'period_seconds', w.period_seconds,
                'estimated_pay', w.estimated_pay
            ) order by w.active desc, w.name)
            from worker_values w
        ), '[]'::jsonb),
        'shifts', coalesce((
            select jsonb_agg(jsonb_build_object(
                'id', s.id,
                'trainer_id', s.trainer_id,
                'trainer_name', t.name,
                'check_in_at', s.check_in_at,
                'check_out_at', s.check_out_at,
                'duration_seconds', s.duration_seconds,
                'hourly_rate', s.hourly_rate_snapshot,
                'estimated_pay', round(
                    s.duration_seconds * s.hourly_rate_snapshot / 3600.0
                )::bigint
            ) order by s.check_in_at desc)
            from shift_values s
            join public.trainers t on t.id = s.trainer_id
        ), '[]'::jsonb)
    ) into v_result;

    return v_result;
end;
$$;

revoke all on function public.admin_staff_dashboard(uuid, date, date)
    from public, anon, authenticated;
grant execute on function public.admin_staff_dashboard(uuid, date, date)
    to authenticated;

create or replace function public.admin_accounting_expenses(
    p_gym_id uuid,
    p_date_from date,
    p_date_to date
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_result jsonb;
begin
    if not private.user_has_gym_role(
        p_gym_id,
        array['admin']::text[]
    ) then
        raise exception 'La contabilidad es exclusiva del administrador.'
            using errcode = '42501';
    end if;

    if p_date_from is null or p_date_to is null or p_date_from > p_date_to then
        raise exception 'El período contable no es válido.'
            using errcode = '22023';
    end if;

    with expenses as (
        select
            e.*,
            coalesce(
                nullif(a.actor_email, ''),
                case
                    when e.recorded_by is null then 'Sistema'
                    else 'Usuario ' || left(e.recorded_by::text, 8)
                end
            ) as actor_email,
            coalesce(nullif(a.actor_role, ''), 'admin') as actor_role
        from public.accounting_expenses e
        left join lateral (
            select al.actor_email, al.actor_role
            from public.audit_logs al
            where al.gym_id = e.gym_id
              and al.entity_type = 'accounting_expenses'
              and al.entity_id = e.id::text
              and al.action = 'EGRESO_REGISTRADO'
            order by al.created_at asc, al.id asc
            limit 1
        ) a on true
        where e.gym_id = p_gym_id
          and e.expense_date between p_date_from and p_date_to
    )
    select jsonb_build_object(
        'total_expenses', coalesce((select sum(amount) from expenses), 0),
        'expense_count', (select count(*) from expenses),
        'by_category', coalesce((
            select jsonb_agg(jsonb_build_object(
                'label', grouped.category,
                'count', grouped.expense_count,
                'total', grouped.total
            ) order by grouped.total desc, grouped.category)
            from (
                select category, count(*) expense_count, sum(amount) total
                from expenses
                group by category
            ) grouped
        ), '[]'::jsonb),
        'expenses', coalesce((
            select jsonb_agg(jsonb_build_object(
                'id', e.id,
                'expense_date', e.expense_date,
                'category', e.category,
                'description', e.description,
                'vendor', e.vendor,
                'amount', e.amount,
                'payment_method', e.payment_method,
                'payment_reference', e.payment_reference,
                'receipt_reference', e.receipt_reference,
                'notes', e.notes,
                'actor_email', e.actor_email,
                'actor_role', e.actor_role,
                'created_at', e.created_at
            ) order by e.expense_date desc, e.id desc)
            from expenses e
        ), '[]'::jsonb)
    ) into v_result;

    return v_result;
end;
$$;

revoke all on function public.admin_accounting_expenses(uuid, date, date)
    from public, anon, authenticated;
grant execute on function public.admin_accounting_expenses(uuid, date, date)
    to authenticated;

commit;

select
    'GymSoft 1.4 INSTALADO' as resultado,
    15 as entradas_para_nuevas_tiqueteras,
    count(*) as trabajadores_registrados
from public.trainers;
