begin;

alter table public.clients
    add column if not exists whatsapp_opt_in boolean not null default false,
    add column if not exists whatsapp_opt_in_at timestamptz,
    add column if not exists whatsapp_opt_in_by uuid;

create table if not exists public.marketing_settings (
    gym_id uuid primary key references public.gyms(id) on delete cascade,
    whatsapp_enabled boolean not null default false,
    birthday_enabled boolean not null default true,
    expiring_enabled boolean not null default true,
    expired_enabled boolean not null default true,
    send_hour smallint not null default 9
        check (send_hour between 0 and 23),
    warning_days smallint not null default 5
        check (warning_days between 1 and 30),
    timezone text not null default 'America/Bogota',
    language_code text not null default 'es_CO',
    default_country_code text not null default '57',
    birthday_template text not null default 'gymsoft_cumpleanos',
    expiring_template text not null default 'gymsoft_membresia_vence',
    expired_template text not null default 'gymsoft_membresia_vencida',
    birthday_extra text not null default
        'Esperamos que disfrutes tu día. Pregunta por tu beneficio de cumpleaños.',
    expiring_extra text not null default
        'Renueva a tiempo para continuar entrenando sin interrupciones.',
    expired_extra text not null default
        'Te esperamos para renovar y volver a entrenar con nosotros.',
    waba_id text not null default '',
    phone_number_id text not null default '',
    graph_api_version text not null default 'v23.0',
    last_worker_at timestamptz,
    last_error text not null default '',
    updated_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.marketing_messages (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    client_id bigint references public.clients(id) on delete set null,
    automation_type text not null
        check (automation_type in ('BIRTHDAY', 'EXPIRING', 'EXPIRED')),
    source_date date not null,
    client_name text not null default '',
    phone text not null,
    template_name text not null,
    language_code text not null default 'es_CO',
    template_parameters jsonb not null default '[]'::jsonb,
    status text not null default 'PENDING'
        check (status in (
            'PENDING', 'PROCESSING', 'SENT', 'FAILED', 'SKIPPED'
        )),
    attempts smallint not null default 0,
    whatsapp_message_id text not null default '',
    error_message text not null default '',
    scheduled_for timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    sent_at timestamptz,
    unique (gym_id, client_id, automation_type, source_date)
);

create index if not exists idx_marketing_messages_gym_date
    on public.marketing_messages(gym_id, created_at desc);

create index if not exists idx_marketing_messages_pending
    on public.marketing_messages(status, scheduled_for)
    where status in ('PENDING', 'FAILED');

create index if not exists idx_clients_whatsapp_opt_in
    on public.clients(gym_id, whatsapp_opt_in)
    where whatsapp_opt_in = true;

alter table public.marketing_settings enable row level security;
alter table public.marketing_messages enable row level security;

drop policy if exists marketing_settings_admin_all
    on public.marketing_settings;
create policy marketing_settings_admin_all
on public.marketing_settings
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

drop policy if exists marketing_messages_admin_read
    on public.marketing_messages;
create policy marketing_messages_admin_read
on public.marketing_messages
for select
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

revoke all on public.marketing_settings
    from public, anon, authenticated;
grant select, insert, update on public.marketing_settings
    to authenticated;

revoke all on public.marketing_messages
    from public, anon, authenticated;
grant select on public.marketing_messages
    to authenticated;

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'marketing_messages'
    ) then
        alter publication supabase_realtime
            add table public.marketing_messages;
    end if;

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'marketing_settings'
    ) then
        alter publication supabase_realtime
            add table public.marketing_settings;
    end if;
end;
$$;

commit;

select
    'MARKETING 1.6 INSTALADO' as resultado,
    count(*) filter (where whatsapp_opt_in) as contactos_autorizados,
    count(*) filter (where not whatsapp_opt_in) as pendientes_autorizacion
from public.clients;
