begin;

-- GymSoft 2.0.4 · gastos creados desde Recepción.
-- Recepción puede CREAR un gasto, pero no puede leer, editar ni eliminar
-- la contabilidad. El administrador conserva el acceso completo.

create table if not exists public.accounting_expenses (
    id bigint generated by default as identity primary key,
    gym_id uuid not null references public.gyms(id) on delete cascade,
    expense_date date not null,
    category text not null,
    description text not null,
    vendor text not null default '',
    amount bigint not null check (amount > 0),
    payment_method text not null default 'Efectivo',
    payment_reference text not null default '',
    receipt_reference text not null default '',
    notes text not null default '',
    recorded_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.accounting_expenses
    add column if not exists expense_date date,
    add column if not exists category text,
    add column if not exists description text,
    add column if not exists vendor text not null default '',
    add column if not exists amount bigint,
    add column if not exists payment_method text not null default 'Efectivo',
    add column if not exists payment_reference text not null default '',
    add column if not exists receipt_reference text not null default '',
    add column if not exists notes text not null default '',
    add column if not exists recorded_by uuid,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

create index if not exists idx_accounting_expenses_gym_date
    on public.accounting_expenses(gym_id, expense_date desc, id desc);

alter table public.accounting_expenses enable row level security;

-- No se abre la tabla a Recepción. La única vía de escritura para esa cuenta
-- es la función validada de abajo; las finanzas siguen siendo solo Admin.
drop policy if exists accounting_expenses_reception_insert
    on public.accounting_expenses;
drop policy if exists accounting_expenses_staff_insert
    on public.accounting_expenses;
drop policy if exists accounting_expenses_admin_all
    on public.accounting_expenses;
create policy accounting_expenses_admin_all
on public.accounting_expenses
for all
to authenticated
using (
    private.user_has_gym_role(gym_id, array['admin']::text[])
)
with check (
    private.user_has_gym_role(gym_id, array['admin']::text[])
);

grant select, insert, update, delete
    on public.accounting_expenses to authenticated;
grant usage, select on sequence public.accounting_expenses_id_seq
    to authenticated;

create or replace function public.reception_create_expense(
    p_gym_id uuid,
    p_expense_date date,
    p_category text,
    p_description text,
    p_vendor text,
    p_amount bigint,
    p_payment_method text,
    p_payment_reference text,
    p_receipt_reference text,
    p_notes text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_id bigint;
    v_category text := btrim(coalesce(p_category, ''));
    v_description text := btrim(coalesce(p_description, ''));
    v_vendor text := btrim(coalesce(p_vendor, ''));
    v_method text := btrim(coalesce(p_payment_method, ''));
    v_payment_reference text := btrim(coalesce(p_payment_reference, ''));
    v_receipt_reference text := btrim(coalesce(p_receipt_reference, ''));
    v_notes text := btrim(coalesce(p_notes, ''));
begin
    if p_gym_id is null
       or not private.user_has_gym_role(
           p_gym_id,
           array['admin', 'receptionist']::text[]
       ) then
        raise exception 'Esta cuenta no puede registrar gastos.'
            using errcode = '42501';
    end if;

    if p_expense_date is null then
        raise exception 'La fecha del gasto es obligatoria.'
            using errcode = '22023';
    end if;

    if v_category = '' or length(v_category) > 80 then
        raise exception 'La categoría del gasto no es válida.'
            using errcode = '22023';
    end if;

    if v_description = '' or length(v_description) > 240 then
        raise exception 'El concepto del gasto es obligatorio y debe ser corto.'
            using errcode = '22023';
    end if;

    if length(v_vendor) > 160
       or length(v_method) > 40
       or length(v_payment_reference) > 120
       or length(v_receipt_reference) > 120
       or length(v_notes) > 500 then
        raise exception 'Uno de los datos del gasto supera el límite permitido.'
            using errcode = '22023';
    end if;

    if p_amount is null or p_amount <= 0 or p_amount > 1000000000000000 then
        raise exception 'El valor del gasto debe ser mayor que cero.'
            using errcode = '22023';
    end if;

    if v_method = '' then
        v_method := 'Efectivo';
    end if;

    insert into public.accounting_expenses(
        gym_id,
        expense_date,
        category,
        description,
        vendor,
        amount,
        payment_method,
        payment_reference,
        receipt_reference,
        notes,
        recorded_by
    )
    values (
        p_gym_id,
        p_expense_date,
        v_category,
        v_description,
        v_vendor,
        p_amount,
        v_method,
        v_payment_reference,
        v_receipt_reference,
        v_notes,
        (select auth.uid())
    )
    returning id into v_id;

    return v_id;
end;
$$;

revoke all on function public.reception_create_expense(
    uuid, date, text, text, text, bigint, text, text, text, text
) from public, anon, authenticated;
grant execute on function public.reception_create_expense(
    uuid, date, text, text, text, bigint, text, text, text, text
) to authenticated;

-- Mantiene la actualización en tiempo real y la auditoría ya instaladas.
-- Los bloques condicionales permiten ejecutar este archivo aunque una
-- instalación antigua todavía no tenga alguno de esos triggers.
do $$
begin
    if to_regprocedure('private.notify_gym_change()') is not null then
        execute 'drop trigger if exists gymsoft_notify_accounting_expenses on public.accounting_expenses';
        execute 'create trigger gymsoft_notify_accounting_expenses '
            || 'after insert or update or delete on public.accounting_expenses '
            || 'for each row execute function private.notify_gym_change()';
    end if;

    if to_regprocedure('private.write_staff_accounting_audit()') is not null then
        execute 'drop trigger if exists gymsoft_audit_accounting_expenses on public.accounting_expenses';
        execute 'create trigger gymsoft_audit_accounting_expenses '
            || 'after insert or update or delete on public.accounting_expenses '
            || 'for each row execute function private.write_staff_accounting_audit()';
    end if;
end;
$$;

commit;

select
    'GASTOS DE RECEPCIÓN INSTALADOS' as resultado,
    to_regprocedure(
        'public.reception_create_expense(uuid,date,text,text,text,bigint,text,text,text,text)'
    ) is not null as funcion_creada,
    exists (
        select 1
        from pg_trigger
        where tgname = 'gymsoft_audit_accounting_expenses'
          and not tgisinternal
    ) as auditoria_activa;
